import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:wyrmtone/presets/matribox_angels_product_plan.dart';
import 'package:wyrmtone/presets/matribox_chain_slot.dart';
import 'package:wyrmtone/presets/matribox_evidence_v2.dart';
import 'package:wyrmtone/presets/matribox_family_expansion_certification.dart';
import 'package:wyrmtone/presets/matribox_full_live_session.dart';
import 'package:wyrmtone/presets/matribox_hardware_evidence.dart';
import 'package:wyrmtone/presets/matribox_model_library.dart';
import 'package:wyrmtone/presets/matribox_raw_backup_service.dart';
import 'package:wyrmtone/presets/matribox_tone_transfer_plan.dart';
import 'package:wyrmtone/presets/matribox_tone_transfer_session.dart';
import 'package:wyrmtone/presets/matribox_transfer_catalog.dart';

import '../tool/native_manufacturer_catalog.dart';
import 'support/matribox_big_capture_snapshots.dart';
import 'support/matribox_full_live_helpers.dart';
import 'support/matribox_tone_transfer_support.dart';

const _goldenPath = 'android/app/src/test/kotlin/de/neevel/wyrmtone/MatriboxToneTransferGolden.kt';
final _hash = 'ab' * 32;

String _kotlinValue(Object? v) => switch (v) {
  String() => '"$v"',
  double() => '$v',
  int() => '$v',
  _ => throw StateError('$v'),
};

String kotlinFixture(Map<String, Object?> request) {
  final b = StringBuffer()
    ..writeln('package de.neevel.wyrmtone')
    ..writeln()
    ..writeln('// GENERATED by test/matribox_tone_transfer_product_test.dart from the production path')
    ..writeln('// (Sound Engine V2 -> target -> known BEFORE P01 -> plan -> contract). Do not edit.')
    ..writeln('object MatriboxToneTransferGolden {')
    ..writeln('    const val PLAN_ID = "${request['planId']}"')
    ..writeln('    const val BACKUP_HASH = "${request['backupHash']}"')
    ..writeln('    val operations: List<Map<String, Any?>> = listOf(');
  for (final op in (request['operations'] as List).cast<Map<String, Object?>>()) {
    b.writeln('        mapOf(${op.entries.map((e) => '"${e.key}" to ${_kotlinValue(e.value)}').join(', ')}),');
  }
  b
    ..writeln('    )')
    ..writeln('}');
  return b.toString();
}

void main() {
  final rec = angelsRecommendation();
  final library = MatriboxModelLibrary.fromVendor(toneCatalog);

  MatriboxToneTransferPlan productPlan({MatriboxHardwareLedger? ledger, bool transport = true, current}) =>
      MatriboxToneTransferPlan.build(
        current: current ?? beforeLayout(),
        target: rec.target,
        ledger: ledger ?? MatriboxHardwareLedger.product(),
        backupSha256: _hash,
        presetNumber: 11,
        isUserBank: true,
        transportAvailable: transport,
        library: library,
      );

  group('evidence ledger of the productive transport', () {
    test('exactly the real CERTIFIED operations of Angels and FAMILY_EXPANSION, equal to what the certification plans derive', () {
      MatriboxFullLiveRecord certified(String planId, int n) => MatriboxFullLiveRecord(
        planId: planId, beforeBackupPath: 'x', beforeBackupSha256: 'x', runOutcome: 'success',
        completed: n, total: n, sentAt: DateTime.utc(2026),
      ).withReadback('certified', DateTime.utc(2026), 'y');
      final angelsPlan = AngelsProductPlan(library: library);
      final familyPlan = FamilyExpansionP01Plan(library);
      final derived = MatriboxHardwareLedger.baseline()
          .withCertification(angelsPlan, certified(AngelsProductPlan.planIdValue, 11))
          .withCertification(familyPlan, certified(FamilyExpansionP01Plan.planIdValue, 23));
      final product = MatriboxHardwareLedger.product();
      expect(product.exact, derived.exact);
      expect(product.exactModels, derived.exactModels);
      expect(product.exactToggles, derived.exactToggles);
      expect(product.modelSlots, isEmpty); // no Full Live generalization in the productive ledger
      expect(product.toggleConfirmed, isFalse);
    });

    test('after the promotion: families are FAMILY_CONFIRMED, everything structurally unsafe stays BLOCKED', () {
      final v2 = MatriboxEvidenceV2(library: library, samples: ActiveSamples.fromLedger(MatriboxHardwareLedger.product(), library));
      MatriboxTransferModel m(MatriboxChainSlot s, String n) => library.byName(s, n)!;
      // select family: every slot, any manufacturer model; the certified ones are exact
      expect(v2.modelSelect(MatriboxChainSlot.fx2, m(MatriboxChainSlot.fx2, 'Boost')).level, EvidenceLevel.exactOperationConfirmed);
      expect(v2.modelSelect(MatriboxChainSlot.fx1, m(MatriboxChainSlot.fx1, 'Skreamer')).level, EvidenceLevel.familyConfirmed);
      expect(v2.modelSelect(MatriboxChainSlot.cab, m(MatriboxChainSlot.cab, 'Brit75 4x12')).level, EvidenceLevel.familyConfirmed);
      expect(v2.modelSelect(MatriboxChainSlot.amp, m(MatriboxChainSlot.amp, 'Sol 100 LD')).level, EvidenceLevel.familyConfirmed);
      // parameter families
      final sol = m(MatriboxChainSlot.amp, 'Sol 100 OD');
      expect(v2.parameter(MatriboxChainSlot.amp, sol, sol.algorithm.parameter('Master'), 50).sendable, isTrue);
      final eq = m(MatriboxChainSlot.eq, 'Guitar EQ');
      expect(v2.parameter(MatriboxChainSlot.eq, eq, eq.algorithm.parameter('800Hz'), -12).sendable, isTrue);
      // block CC: all nine slots, both directions
      for (final slot in MatriboxChainSlot.values) {
        expect(v2.blockToggle(slot, true).sendable, isTrue, reason: slot.label);
        expect(v2.blockToggle(slot, false).sendable, isTrue, reason: slot.label);
      }
      // still BLOCKED: bind/Sync, enumerations, User IR, signed outside EQ, FX1/FX2 definition conflicts
      final chorus = m(MatriboxChainSlot.mod, 'Chorus A');
      expect(v2.parameter(MatriboxChainSlot.mod, chorus, chorus.algorithm.parameter('Rate'), 3.7).level, EvidenceLevel.blocked);
      expect(v2.parameter(MatriboxChainSlot.mod, chorus, chorus.algorithm.parameter('Sync'), 1).level, EvidenceLevel.blocked);
      final ac = m(MatriboxChainSlot.fx2, 'AC Sim');
      expect(v2.parameter(MatriboxChainSlot.fx2, ac, ac.algorithm.parameter('Mode'), 1).level, EvidenceLevel.blocked);
      final modRvb = m(MatriboxChainSlot.rvb, 'Mod RVB');
      expect(v2.parameter(MatriboxChainSlot.rvb, modRvb, modRvb.algorithm.parameter('Lo End'), -10).sendable, isFalse);
      expect(v2.modelSelect(MatriboxChainSlot.cab, m(MatriboxChainSlot.cab, 'User IR 7')).level, EvidenceLevel.blocked);
    });

    test('the native table (Kotlin, generated) is exactly what the Dart decisions produce', () {
      final source = File(nativeCatalogPath).readAsStringSync().replaceAll('\r\n', '\n');
      expect(source, renderNativeManufacturerCatalog(toneCatalog).replaceAll('\r\n', '\n'), reason: 'run dart run tool/generate_native_manufacturer_catalog.dart');
      final catalog = File('android/app/src/main/kotlin/de/neevel/wyrmtone/MatriboxToneTransferCatalog.kt').readAsStringSync();
      expect(catalog, contains('MatriboxManufacturerData'));
      expect(catalog, isNot(contains('ConfirmedModel(')));
    });
  });

  group('Angels product case from the production path (not hard-coded)', () {
    test('Recommendation -> target -> known BEFORE P01 -> exactly the 11 certified operations, all evidence-eligible', () {
      final plan = productPlan();
      final s = plan.summary;
      expect((s.modelsChanged, s.parametersChanged, s.blocksEnabled + s.blocksDisabled), (2, 5, 4));
      expect((s.blocked, s.unsupported, s.incomplete, s.unknownCurrent), (0, 0, 0, 0));
      expect(plan.overall, ToneTransferOverall.ready);
      expect(plan.operations.map((e) => '${e.slot.label} ${e.subject} ${e.target}'), [
        'FX1 BLOCK OFF',
        'FX2 MODEL Boost',
        'FX2 BLOCK ON',
        'AMP gain 67',
        'AMP presence 59',
        'AMP bass 41',
        'AMP middle 59',
        'AMP treble 61',
        'CAB MODEL Sol 4x12',
        'CAB BLOCK ON',
        'EQ BLOCK OFF',
      ]);
      // the same list as the certified hardware run
      final certified = AngelsProductPlan(library: library, target: rec.target);
      expect(certified.blockers(beforeLayout()), isEmpty);
      expect(plan.operations.map((e) => e.bytes!.join(',')), certified.operations.map((o) => o.bytes.join(',')));
    });

    test('the same request against a different current P01: same TARGET, different DIFF', () {
      final other = beforeLayoutWithAmp(0x07000035);
      final a = productPlan();
      final b = productPlan(current: other);
      expect(rec.target.toJson().toString(), angelsRecommendation().target.toJson().toString());
      expect(b.summary.blocked, 0); // the Sol 100 OD select is FAMILY/EXACT confirmed now
      expect(b.operations.length, greaterThan(a.operations.length)); // select + all AMP parameters instead of a few
    });

    test('the closed contract: names and values only, no bytes / algorithm ids / indices; equals the Kotlin golden', () {
      final request = productPlan().toContractRequest();
      expect(request.keys.toSet(), {'planId', 'targetBank', 'targetSlot', 'backupHash', 'operations'});
      expect(request['targetBank'], 'USER');
      expect(request['targetSlot'], 11);
      expect(request['planId'], matches(RegExp(r'^[0-9a-f]{64}$')));
      final ops = (request['operations'] as List).cast<Map<String, Object?>>();
      expect(ops, [
        {'type': 'DISABLE_BLOCK', 'slot': 'FX1'},
        {'type': 'SELECT_MODEL', 'slot': 'FX2', 'model': 'Boost'},
        {'type': 'ENABLE_BLOCK', 'slot': 'FX2'},
        {'type': 'SET_PARAMETER', 'slot': 'AMP', 'model': 'Sol 100 OD', 'parameter': 'Gain', 'value': 67.0},
        {'type': 'SET_PARAMETER', 'slot': 'AMP', 'model': 'Sol 100 OD', 'parameter': 'PRES', 'value': 59.0},
        {'type': 'SET_PARAMETER', 'slot': 'AMP', 'model': 'Sol 100 OD', 'parameter': 'Bass', 'value': 41.0},
        {'type': 'SET_PARAMETER', 'slot': 'AMP', 'model': 'Sol 100 OD', 'parameter': 'Middle', 'value': 59.0},
        {'type': 'SET_PARAMETER', 'slot': 'AMP', 'model': 'Sol 100 OD', 'parameter': 'Treble', 'value': 61.0},
        {'type': 'SELECT_MODEL', 'slot': 'CAB', 'model': 'Sol 4x12'},
        {'type': 'ENABLE_BLOCK', 'slot': 'CAB'},
        {'type': 'DISABLE_BLOCK', 'slot': 'EQ'},
      ]);
      for (final op in ops) {
        expect(op.keys.any((k) => {'bytes', 'code', 'index', 'sysex', 'algorithm', 'wireIndex'}.contains(k)), isFalse);
      }
      // Kotlin golden: generated from this very path (set GENERATE_TONE_TRANSFER_FIXTURE=1 to rewrite it)
      final generated = kotlinFixture(request);
      if (Platform.environment['GENERATE_TONE_TRANSFER_FIXTURE'] == '1') File(_goldenPath).writeAsStringSync(generated);
      expect(File(_goldenPath).readAsStringSync().replaceAll('\r\n', '\n'), generated);
    });

    test('an evidence-blocked, unsupported or incomplete plan has no contract to send', () {
      final blocked = productPlan(ledger: MatriboxHardwareLedger.baseline());
      expect(blocked.sendable, isFalse);
      expect(() => blocked.toContractRequest(), returnsNormally); // only operations() of eligible entries are exported
      expect((blocked.toContractRequest()['operations'] as List).length, lessThan(11));
      final noTransport = productPlan(transport: false);
      expect(noTransport.sendable, isFalse);
    });
  });

  group('workflow states', () {
    late Directory tempDir;
    late MatriboxToneTransferStore store;
    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('tone_product');
      store = MatriboxToneTransferStore(File('${tempDir.path}/tone_transfer.state'));
    });
    tearDown(() {
      if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
    });

    Future<MatriboxToneTransferRecord> sentRecord({RecordingTransfer? channel}) async {
      final read = ToneReadChannel(hexParts(bigBeforeRawPartsHex));
      final prepared = await MatriboxToneTransferSession(
        backupService: _service(read, tempDir),
        ledger: MatriboxHardwareLedger.product(),
        channel: channel ?? RecordingTransfer(),
        library: library,
      ).prepare(rec.target, targetSlot: 11);
      await MatriboxToneTransferExecutor(channel: channel ?? RecordingTransfer(), store: store).execute(prepared);
      return (await store.load())!;
    }

    test('LIVE_WRITE_COMPLETE -> AWAITING_MANUAL_SAVE sends zero MIDI and claims nothing', () async {
      final channel = RecordingTransfer();
      final record = await sentRecord(channel: channel);
      expect(record.state, ToneTransferRecordState.liveWriteComplete);
      expect(record.sessionToken, 'gen-1');
      final before = channel.executions.length;
      final updated = await MatriboxToneTransferCheckpoint.confirmManualSave(record, store);
      expect(updated.state, ToneTransferRecordState.awaitingManualSave);
      expect(updated.persistence, isNull);
      expect(updated.readbackOutcome, isNull);
      expect(channel.executions.length, before); // the checkpoint has no access to any transport
    });

    test('a readback before the manual-save checkpoint is refused and never reads the device', () async {
      final record = await sentRecord();
      final read = ToneReadChannel(savedAfter());
      final result = await MatriboxToneTransferReadback.run(record: record, backupService: _service(read, tempDir), store: store);
      expect(result.outcome, ToneReadbackOutcome.notAwaitingSave);
      expect(read.reads, 0);
      expect((await store.load())!.state, ToneTransferRecordState.liveWriteComplete);
    });

    test('VERIFIED only from a fresh readback of the saved state after the checkpoint', () async {
      var record = await sentRecord();
      record = await MatriboxToneTransferCheckpoint.confirmManualSave(record, store);
      final read = ToneReadChannel(savedAfter());
      final result = await MatriboxToneTransferReadback.run(record: record, backupService: _service(read, tempDir), store: store);
      expect(result.outcome, ToneReadbackOutcome.certified);
      expect(read.reads, 1); // a fresh read
      final verified = (await store.load())!;
      expect(verified.state, ToneTransferRecordState.verified);
      expect(verified.persistence, 'MANUAL_SAVE_PERSISTENCE_VERIFIED');
      expect(verified.toJson().keys.any((k) => k.toLowerCase().contains('qme2')), isFalse);
    });

    test('TARGET_MISMATCH allows a re-read but no resend; the re-read can still verify', () async {
      var record = await sentRecord();
      record = await MatriboxToneTransferCheckpoint.confirmManualSave(record, store);
      final read = ToneReadChannel(hexParts(bigBeforeRawPartsHex)); // not saved on the device
      final first = await MatriboxToneTransferReadback.run(record: record, backupService: _service(read, tempDir), store: store);
      expect(first.outcome, ToneReadbackOutcome.targetMismatch);
      final failed = (await store.load())!;
      expect(failed.state, ToneTransferRecordState.failed);
      read.parts = savedAfter();
      final second = await MatriboxToneTransferReadback.run(record: failed, backupService: _service(read, tempDir), store: store);
      expect(second.outcome, ToneReadbackOutcome.certified);
    });

    test('disconnect / power-off makes the session STALE; nothing is assumed; a fresh read decides', () async {
      final record = await sentRecord();
      expect((await MatriboxToneTransferCheckpoint.markStaleIfReconnected(record, 'gen-1', store)).state,
          ToneTransferRecordState.liveWriteComplete); // same connection: unchanged
      // also an AWAITING_MANUAL_SAVE session goes STALE after a reconnect (checked on a copy)
      final awaiting = record.copyWith(state: ToneTransferRecordState.awaitingManualSave);
      expect((await MatriboxToneTransferCheckpoint.markStaleIfReconnected(awaiting, 'gen-2', store)).state,
          ToneTransferRecordState.stale);
      final stale = await MatriboxToneTransferCheckpoint.markStaleIfReconnected(record, 'gen-2', store);
      expect(stale.state, ToneTransferRecordState.stale);
      expect((await store.load())!.state, ToneTransferRecordState.stale);
      // a stale session is never "verified"; the readback from stale checks the saved state
      final read = ToneReadChannel(hexParts(bigBeforeRawPartsHex));
      final result = await MatriboxToneTransferReadback.run(record: stale, backupService: _service(read, tempDir), store: store);
      expect(result.outcome, ToneReadbackOutcome.targetMismatch);
      expect((await store.load())!.state, ToneTransferRecordState.failed);
      // a verified session is not touched by a later reconnect
      var again = await sentRecord();
      again = await MatriboxToneTransferCheckpoint.confirmManualSave(again, store);
      await MatriboxToneTransferReadback.run(
        record: again, backupService: _service(ToneReadChannel(savedAfter()), tempDir), store: store,
      );
      final verified = (await store.load())!;
      expect((await MatriboxToneTransferCheckpoint.markStaleIfReconnected(verified, 'gen-9', store)).state,
          ToneTransferRecordState.verified);
    });

    test('earlier stored records (sent / readbackDone) still load; a record without a writable slot never does', () {
      final json = {
        ...(rec.target.toJson().isEmpty ? {} : <String, Object?>{}),
      };
      expect(json, isEmpty);
      final legacy = {
        'planFingerprint': 'f',
        'beforeBackupPath': 'p',
        'beforeBackupSha256': 's',
        'target': rec.target.toJson(),
        'operations': <Object?>[],
        'sentAt': DateTime.utc(2026).toIso8601String(),
        'state': 'readbackDone',
        'readbackOutcome': 'certified',
      };
      // a legacy (implicitly P01) record has no slot identity: it is never loaded, let alone VERIFIED
      expect(MatriboxToneTransferRecord.tryFromJson(legacy), isNull);
      for (final slot in [1, 5, 10, 0, 100, '11']) {
        expect(MatriboxToneTransferRecord.tryFromJson({...legacy, 'targetBank': 'USER', 'targetSlot': slot}), isNull, reason: '$slot');
      }
      expect(MatriboxToneTransferRecord.tryFromJson({...legacy, 'targetBank': 'FACTORY', 'targetSlot': 11}), isNull);
      final base = {
        'targetBank': 'USER',
        'targetSlot': 11,
        'planFingerprint': 'f',
        'beforeBackupPath': 'p',
        'beforeBackupSha256': 's',
        'target': rec.target.toJson(),
        'operations': <Object?>[],
        'sentAt': DateTime.utc(2026).toIso8601String(),
      };
      expect(MatriboxToneTransferRecord.tryFromJson({...base, 'state': 'sent'})!.state, ToneTransferRecordState.liveWriteComplete);
      expect(MatriboxToneTransferRecord.tryFromJson({...base, 'state': 'readbackDone', 'readbackOutcome': 'certified'})!.state,
          ToneTransferRecordState.verified);
      expect(MatriboxToneTransferRecord.tryFromJson({...base, 'state': 'readbackDone', 'readbackOutcome': 'targetMismatch'})!.state,
          ToneTransferRecordState.failed);
    });
  });

  group('single send path and product/certification separation', () {
    test('certification panels are not the productive path', () {
      final page = File('lib/screens/tone_transfer_page.dart').readAsStringSync();
      expect(page, isNot(contains('runFullLiveP01Certification')));
      expect(page, isNot(contains('matribox_angels_certification_panel')));
      expect(page, isNot(contains('matribox_full_live_panel')));
    });
  });
}

MatriboxRawBackupService _service(ToneReadChannel read, Directory dir) =>
    MatriboxRawBackupService(channel: read, backupDirectory: dir);

List<List<int>> savedAfter() {
  final rec = angelsRecommendation();
  final plan = MatriboxToneTransferPlan.build(
    current: beforeLayout(),
    target: rec.target,
    ledger: MatriboxHardwareLedger.product(),
    backupSha256: _hash,
    presetNumber: 11,
    isUserBank: true,
    transportAvailable: true,
    library: rec.library,
  );
  return deviceAfter(plan.operations);
}
