package de.neevel.wyrmtone

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The contract generated by the Dart production path (Sound Engine V2 ->
 * target -> known BEFORE -> plan) is accepted natively as a WHOLE plan and
 * encodes to exactly the messages of the CERTIFIED hardware run. Only the
 * target slot varies (P01 is protected; P11 is the first writable slot); the
 * 11 musical operations stay exactly the certified ones.
 */
class MatriboxToneTransferGoldenTest {
    private fun request() = mapOf(
        "planId" to MatriboxToneTransferGolden.PLAN_ID,
        "targetBank" to "USER",
        "targetSlot" to 11,
        "backupHash" to MatriboxToneTransferGolden.BACKUP_HASH,
        "operations" to MatriboxToneTransferGolden.operations,
    )

    @Test fun `the production contract validates as a whole plan and encodes to exactly the certified hardware messages`() {
        val plan = MatriboxToneTransferPlanValidator.validate(request())
        assertEquals(MatriboxAngelsGolden.messages, plan.operations.map { MatriboxFullLiveCodec.encode(it).joinToString(" ") { b -> "%02x".format(b) } })
        assertEquals(11, plan.operations.size)
        assertEquals(2, plan.operations.count { it is FullLiveOperation.ModelSelect })
        assertEquals(5, plan.operations.count { it is FullLiveOperation.Parameter })
        assertEquals(4, plan.operations.count { it is FullLiveOperation.BlockToggle })
    }

    @Test fun `the frozen FAMILY_EXPANSION_P01_V1 messages are valid closed live-edit messages`() {
        // CERTIFIED hardware run (frozen evidence); the Dart side proves the productive encoder and ledger.
        assertEquals(23, MatriboxFamilyExpansionGolden.messages.size)
        for (hex in MatriboxFamilyExpansionGolden.messages) {
            val message = hex.split(" ").map { it.toInt(16).toByte() }.toByteArray()
            MatriboxFullLiveCodec.validate(message)
        }
    }

    @Test fun `the production contract runs through the session with the productive port contract`() {
        val sent = mutableListOf<FullLiveOperation>()
        val selected = mutableListOf<Int>()
        val port = object : MatriboxToneTransferSendPort {
            override fun selectUserPreset(target: MatriboxWritableUserPreset) { selected.add(target.presetNumber) }
            override fun sendValidated(operation: FullLiveOperation) { sent.add(operation) }
            override fun close() {}
        }
        val session = MatriboxToneTransferSession(
            eligibility = {
                ProbeEligibility(
                    enabled = true, connection = "usb/box", vendor = 0x84ef, product = 0x0054, uniqueUsb = true,
                    uniqueMidi = true, directlyMapped = true, deviceOpen = true, expectedInput = true, monitoring = false,
                )
            },
            openSendPort = { port },
            pause = {},
        )
        val result = session.execute(request())
        assertEquals("SUCCESS", result["outcome"])
        assertEquals(listOf(11, 11), selected)
        assertEquals(MatriboxAngelsGolden.messages, sent.map { MatriboxFullLiveCodec.encode(it).joinToString(" ") { b -> "%02x".format(b) } })
        assertTrue(sent.all { MatriboxToneTransferCatalog.isConfirmed(it) })
    }
}
