package de.neevel.wyrmtone

// GENERATED by tool/generate_angels_kotlin_fixture.dart from the Dart plan. Do not edit.
object MatriboxAngelsGolden {
    val messages: List<String> = listOf(
        "b1 30 7f", // FX1 BLOCK OFF
        "f0 21 25 7f 51 4d 45 32 12 10 02 00 01 01 0a 00 00 00 00 00 00 f7", // FX2 MODEL Boost
        "b1 31 00", // FX2 BLOCK ON
        "f0 21 25 7f 51 4d 45 32 12 10 03 00 02 04 07 00 00 00 00 00 07 00 00 00 00 00 00 00 00 08 06 04 02 f7", // AMP PARAM Gain = 67
        "f0 21 25 7f 51 4d 45 32 12 10 03 00 02 04 07 00 00 00 00 00 07 00 01 00 00 00 00 00 00 06 0c 04 02 f7", // AMP PARAM PRES = 59
        "f0 21 25 7f 51 4d 45 32 12 10 03 00 02 04 07 00 00 00 00 00 07 00 03 00 00 00 00 00 00 02 04 04 02 f7", // AMP PARAM Bass = 41
        "f0 21 25 7f 51 4d 45 32 12 10 03 00 02 04 07 00 00 00 00 00 07 00 04 00 00 00 00 00 00 06 0c 04 02 f7", // AMP PARAM Middle = 59
        "f0 21 25 7f 51 4d 45 32 12 10 03 00 02 04 07 00 00 00 00 00 07 00 05 00 00 00 00 00 00 07 04 04 02 f7", // AMP PARAM Treble = 61
        "f0 21 25 7f 51 4d 45 32 12 10 05 00 01 02 08 00 00 00 00 00 0a f7", // CAB MODEL Sol 4x12
        "b1 34 00", // CAB BLOCK ON
        "b1 35 7f", // EQ BLOCK OFF
    )
}
