package de.neevel.wyrmtone

// GENERATED by tool/generate_family_expansion_kotlin_fixture.dart from the Dart plan. Do not edit.
object MatriboxFamilyExpansionGolden {
    val messages: List<String> = listOf(
        "f0 21 25 7f 51 4d 45 32 12 10 01 00 01 01 0a 00 00 00 00 00 00 f7", // FX1 MODEL Boost
        "f0 21 25 7f 51 4d 45 32 12 10 02 00 01 01 0a 00 00 00 00 00 00 f7", // FX2 MODEL Boost
        "f0 21 25 7f 51 4d 45 32 12 10 02 00 02 01 0a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0b 08 04 01 f7", // FX2 PARAM Gain = 23
        "f0 21 25 7f 51 4d 45 32 12 10 02 00 02 01 0a 00 00 00 00 00 00 00 02 00 00 00 00 00 00 08 00 03 0f f7", // FX2 PARAM Bright = 1
        "f0 21 25 7f 51 4d 45 32 12 10 03 00 01 04 07 00 00 00 00 00 07 f7", // AMP MODEL Sol 100 OD
        "f0 21 25 7f 51 4d 45 32 12 10 04 00 01 01 0d 00 00 00 00 00 00 f7", // NR MODEL Gate 2
        "f0 21 25 7f 51 4d 45 32 12 10 04 00 02 01 0d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0f 08 04 01 f7", // NR PARAM THRE = 31
        "b1 33 00", // NR BLOCK ON
        "f0 21 25 7f 51 4d 45 32 12 10 05 00 01 02 08 00 00 00 00 00 0a f7", // CAB MODEL Sol 4x12
        "f0 21 25 7f 51 4d 45 32 12 10 05 00 02 02 08 00 00 00 00 00 0a 00 01 00 00 00 00 00 00 02 0c 04 02 f7", // CAB PARAM VOL = 43
        "f0 21 25 7f 51 4d 45 32 12 10 06 00 01 03 05 00 00 00 00 00 01 f7", // EQ MODEL Guitar EQ
        "f0 21 25 7f 51 4d 45 32 12 10 06 00 02 03 05 00 00 00 00 00 01 00 01 00 00 00 00 00 00 0b 08 0c 01 f7", // EQ PARAM 400Hz = -23
        "b1 35 00", // EQ BLOCK ON
        "f0 21 25 7f 51 4d 45 32 12 10 07 00 01 00 00 00 00 00 00 00 04 f7", // MOD MODEL Chorus A
        "f0 21 25 7f 51 4d 45 32 12 10 07 00 02 00 00 00 00 00 00 00 04 00 01 00 00 0c 0d 0c 0c 06 0c 04 00 f7", // MOD PARAM Rate = 3.7
        "f0 21 25 7f 51 4d 45 32 12 10 08 00 01 00 0d 00 00 00 00 00 0b f7", // DLY MODEL Warm
        "f0 21 25 7f 51 4d 45 32 12 10 08 00 02 00 0d 00 00 00 00 00 0b 00 01 00 00 00 00 0c 00 03 09 04 04 f7", // DLY PARAM Time = 743
        "f0 21 25 7f 51 4d 45 32 12 10 08 00 02 00 0d 00 00 00 00 00 0b 00 04 00 00 00 00 00 00 08 00 03 0f f7", // DLY PARAM Trail = 1
        "f0 21 25 7f 51 4d 45 32 12 10 09 00 01 00 00 00 00 00 00 00 0c f7", // RVB MODEL Room
        "f0 21 25 7f 51 4d 45 32 12 10 09 00 02 00 00 00 00 00 00 00 0c 00 00 00 00 00 00 00 00 0b 08 04 01 f7", // RVB PARAM Mix = 23
        "f0 21 25 7f 51 4d 45 32 12 10 09 00 02 00 00 00 00 00 00 00 0c 00 02 00 00 00 00 00 00 02 04 04 02 f7", // RVB PARAM Decay = 41
        "f0 21 25 7f 51 4d 45 32 12 10 09 00 02 00 00 00 00 00 00 00 0c 00 03 00 00 00 00 00 00 08 00 03 0f f7", // RVB PARAM Trail = 1
        "b1 38 00", // RVB BLOCK ON
    )
}
