package de.neevel.wyrmtone

// GENERATED by test/matribox_tone_transfer_product_test.dart from the production path
// (Sound Engine V2 -> target -> known BEFORE P01 -> plan -> contract). Do not edit.
object MatriboxToneTransferGolden {
    const val PLAN_ID = "e5842ce300448943a1b4ca5225fc6310532b6af35443897a6f5d252cd87f7611"
    const val BACKUP_HASH = "abababababababababababababababababababababababababababababababab"
    val operations: List<Map<String, Any?>> = listOf(
        mapOf("type" to "DISABLE_BLOCK", "slot" to "FX1"),
        mapOf("type" to "SELECT_MODEL", "slot" to "FX2", "model" to "Boost"),
        mapOf("type" to "ENABLE_BLOCK", "slot" to "FX2"),
        mapOf("type" to "SET_PARAMETER", "slot" to "AMP", "model" to "Sol 100 OD", "parameter" to "Gain", "value" to 67.0),
        mapOf("type" to "SET_PARAMETER", "slot" to "AMP", "model" to "Sol 100 OD", "parameter" to "PRES", "value" to 59.0),
        mapOf("type" to "SET_PARAMETER", "slot" to "AMP", "model" to "Sol 100 OD", "parameter" to "Bass", "value" to 41.0),
        mapOf("type" to "SET_PARAMETER", "slot" to "AMP", "model" to "Sol 100 OD", "parameter" to "Middle", "value" to 59.0),
        mapOf("type" to "SET_PARAMETER", "slot" to "AMP", "model" to "Sol 100 OD", "parameter" to "Treble", "value" to 61.0),
        mapOf("type" to "SELECT_MODEL", "slot" to "CAB", "model" to "Sol 4x12"),
        mapOf("type" to "ENABLE_BLOCK", "slot" to "CAB"),
        mapOf("type" to "DISABLE_BLOCK", "slot" to "EQ"),
    )
}
