"""Metal artists: slug|Name|aliases|parent template|genres|eras|tags|overrides|tunings|roles|kinds

The parent template carries the genre sound; the overrides only state what is characteristic for the
act as a WyrmTone style opinion (never original equipment). Names are reference/search metadata.
"""
from common import C, artist

ROWS = {}

ROWS['metal_traditional'] = ('Metal: Heavy, NWOBHM, Speed, Power', 'Traditioneller Metal: Heavy, NWOBHM, Speed und Power Metal.', [
    'ozzy_osbourne|Ozzy Osbourne|Ozzy|genre.heavy_metal|heavy_metal,hard_rock|1980s,1990s|dark,melodic,riff-driven|g=60,ba=54,mi=62,su=64|eStandard,dStandard',
    'dio|Dio|Ronnie James Dio|genre.heavy_metal|heavy_metal|1980s|epic,melodic,mid-forward|g=58,mi=64,tr=58,su=66|eStandard',
    'accept|Accept||genre.heavy_metal|heavy_metal,speed_metal|1980s|tight,sharp,riff-driven|g=64,ti=70,mi=58,tr=60|eStandard',
    'motorhead|Motörhead||genre.heavy_metal|heavy_metal,hard_rock|1970s,1980s|raw,loud,driving,punky|g=66,sa=64,ba=56,mi=64,ti=52|eStandard',
    'manowar|Manowar||genre.heavy_metal|heavy_metal,power_metal|1980s|epic,loud,bombastic|g=62,ba=56,mi=60,su=66|eStandard',
    'saxon|Saxon||genre.nwobhm|nwobhm,heavy_metal|1980s|driving,raw,riff-driven|g=56,ti=54|eStandard',
    'diamond_head|Diamond Head||genre.nwobhm|nwobhm,heavy_metal|1980s|riff-driven,raw,gritty|g=52,ti=50,mi=66|eStandard',
    'angel_witch|Angel Witch||genre.nwobhm|nwobhm|1980s|raw,dark,vintage|g=52,tr=54,mi=64|eStandard',
    'tygers_of_pan_tang|Tygers of Pan Tang||genre.nwobhm|nwobhm|1980s|melodic,twin-lead,raw|g=54,su=62|eStandard',
    'rainbow|Rainbow||genre.heavy_metal|heavy_metal,hard_rock|1970s|neoclassical,vintage,mid-forward|g=54,mi=66,su=68|eStandard',
    'venom|Venom||genre.nwobhm|nwobhm,black_metal|1980s|raw,dirty,lo-fi|g=64,sa=68,ti=44|eStandard',
    'queensryche|Queensrÿche||genre.heavy_metal|heavy_metal,progressive_metal|1980s|precise,dramatic,melodic|g=54,ti=62,su=70,de=14|eStandard',
    'helloween|Helloween||genre.power_metal|power_metal,speed_metal|1980s,1990s|melodic,fast,twin-lead|g=60,ti=72,su=72|eStandard',
    'blind_guardian|Blind Guardian||genre.power_metal|power_metal,speed_metal|1990s|layered,epic,dense|g=62,ti=74,re=18|eStandard,dStandard',
    'hammerfall|HammerFall||genre.power_metal|power_metal,heavy_metal|1990s,2000s|polished,anthemic,bright|g=58,tr=66,su=74|eStandard,dStandard',
    'sabaton|Sabaton||genre.power_metal|power_metal,heavy_metal|2000s,2010s|anthemic,punchy,direct|g=60,ti=68,ba=50,re=10|dStandard',
    'stratovarius|Stratovarius||genre.power_metal|power_metal|1990s,2000s|neoclassical,bright,fast|g=56,tr=66,su=78|eStandard',
    'gamma_ray|Gamma Ray||genre.power_metal|power_metal,speed_metal|1990s|melodic,driving,bright|g=58,ti=72|eStandard',
    'dragonforce|DragonForce||genre.power_metal|power_metal|2000s|ultra-fast,bright,clean-definition|g=54,ti=76,tr=68,pr=64,su=80|eStandard',
    'rhapsody_of_fire|Rhapsody of Fire|Rhapsody|genre.power_metal|power_metal,symphonic_metal|1990s,2000s|epic,neoclassical,layered|g=54,su=76,re=20|eStandard',
    'sonata_arctica|Sonata Arctica||genre.power_metal|power_metal|2000s|melodic,bright,keyboard-like|g=54,tr=64,su=78|eStandard',
    'edguy|Edguy||genre.power_metal|power_metal,hard_rock|2000s|catchy,bright,punchy|g=56,mi=60|eStandard',
    'powerwolf|Powerwolf||genre.power_metal|power_metal|2000s,2010s|dramatic,punchy,direct|g=60,ti=68,mi=58|dStandard',
    'exciter|Exciter||genre.speed_metal|speed_metal|1980s|raw,fast,dirty|g=66,ti=70,sa=64|eStandard',
    'running_wild|Running Wild||genre.speed_metal|speed_metal,heavy_metal|1980s|driving,melodic,galloping|g=60,ti=68|eStandard',
    'bathory|Bathory||genre.black_metal|black_metal|1980s|raw,lo-fi,primitive|g=68,lofi=20|eStandard',
])

ROWS['metal_thrash_groove'] = ('Metal: Thrash und Groove', 'Thrash- und Groove-Metal-Acts.', [
    'anthrax|Anthrax||genre.thrash_metal|thrash_metal|1980s,1990s|punchy,rhythmic,tight|g=68,ti=88,mi=44|eStandard,dStandard',
    'testament|Testament||genre.thrash_metal|thrash_metal|1980s,1990s|precise,melodic-leads,tight|g=68,ti=84,um=64|eStandard',
    'exodus|Exodus||genre.thrash_metal|thrash_metal|1980s|raw,fast,bay-area|g=72,ti=82,sa=72|eStandard',
    'kreator|Kreator||genre.thrash_metal|thrash_metal|1980s,1990s|aggressive,german-thrash,sharp|g=74,ti=84,tr=62|eStandard',
    'sodom|Sodom||genre.thrash_metal|thrash_metal|1980s|raw,dirty,punky|g=72,sa=74,ti=76,lofi=20|eStandard',
    'destruction|Destruction||genre.thrash_metal|thrash_metal|1980s|raw,fast,sharp|g=72,ti=80,pr=62|eStandard',
    'overkill|Overkill||genre.thrash_metal|thrash_metal|1980s,1990s|gritty,bass-heavy,driving|g=68,ba=52,ti=80|eStandard',
    'sepultura|Sepultura||genre.groove_metal|groove_metal,thrash_metal|1980s,1990s|tribal,downtuned,heavy|g=70,ti=78,ba=58|dStandard,dropC',
    'death_angel|Death Angel||genre.thrash_metal|thrash_metal|1980s,2000s|technical,tight,sharp|g=70,ti=86,um=64|eStandard',
    'violence|Vio-lence||genre.thrash_metal|thrash_metal|1980s|raw,fast,aggressive|g=72,ti=82|eStandard',
    'nuclear_assault|Nuclear Assault||genre.thrash_metal|thrash_metal|1980s|punky,raw,fast|g=70,ti=78,sa=68|eStandard',
    'municipal_waste|Municipal Waste||genre.thrash_metal|thrash_metal|2000s,2010s|party-thrash,raw,fast|g=70,ti=80,lofi=15|eStandard',
    'havok|Havok||genre.thrash_metal|thrash_metal|2010s|modern-thrash,tight,clear|g=70,ti=86,clarity=72|eStandard',
    'power_trip|Power Trip||genre.thrash_metal|thrash_metal|2010s|raw,crossover,aggressive|g=72,ti=82,sa=72|eStandard',
    'annihilator|Annihilator||genre.thrash_metal|thrash_metal|1980s,1990s|technical,precise,melodic|g=68,ti=84,su=62|eStandard',
    'sacred_reich|Sacred Reich||genre.thrash_metal|thrash_metal|1980s,1990s|groovy,riff-driven,direct|g=66,ti=78,ba=50|eStandard',
    'flotsam_and_jetsam|Flotsam and Jetsam||genre.thrash_metal|thrash_metal|1980s|melodic,tight,bright|g=66,ti=80,tr=62|eStandard',
    'machine_head|Machine Head||genre.groove_metal|groove_metal,thrash_metal|1990s,2000s|heavy,groovy,downtuned|g=72,ti=80,ba=56|dropC,dStandard',
    'white_zombie|White Zombie||genre.groove_metal|groove_metal,industrial_metal|1990s|groovy,fuzzy,dirty|g=66,sa=72,ba=58,fuzz=35|dStandard',
    'chimaira|Chimaira||genre.groove_metal|groove_metal,metalcore|2000s|aggressive,tight,modern|g=72,ti=84|dropC',
    'devildriver|DevilDriver||genre.groove_metal|groove_metal,metalcore|2000s|aggressive,groovy,gritty|g=72,ti=80,ba=56|dropC',
    'down|Down||genre.sludge_metal|sludge_metal,groove_metal|1990s,2000s|southern,heavy,gritty|g=62,ti=42,mi=54|dStandard',
    'crowbar|Crowbar||genre.sludge_metal|sludge_metal|1990s|crushing,slow,downtuned|g=70,ti=32,ba=68|dropC,dropB',
])

ROWS['metal_death_black'] = ('Metal: Death, Black, Melodic Death', 'Death-, Black-, Technical-Death- und Melodic-Death-Metal-Acts.', [
    'dark_tranquillity|Dark Tranquillity||genre.melodic_death_metal|melodic_death_metal|1990s,2000s|melodic,gothenburg,bright-leads|g=62,um=68,su=68|dStandard,dropC',
    'at_the_gates|At the Gates||genre.melodic_death_metal|melodic_death_metal,death_metal|1990s|sharp,aggressive,raw|g=70,ti=80,pr=62|dStandard',
    'soilwork|Soilwork||genre.melodic_death_metal|melodic_death_metal,metalcore|2000s|modern,clear,melodic|g=66,ti=86,clarity=72|dropC,dStandard',
    'insomnium|Insomnium||genre.melodic_death_metal|melodic_death_metal,doom_metal|2000s|melancholic,wide,melodic|g=60,ti=70,su=72,re=16|dStandard',
    'kalmah|Kalmah||genre.melodic_death_metal|melodic_death_metal|2000s|fast,melodic,neoclassical|g=64,ti=82,su=70|dStandard',
    'wintersun|Wintersun||genre.melodic_death_metal|melodic_death_metal,folk_metal|2000s|epic,layered,fast|g=62,ti=80,su=76,re=16|dStandard',
    'death|Death||genre.death_metal|death_metal,technical_death_metal|1980s,1990s|technical,clear,progressive|g=70,ti=86,clarity=70|eStandard,dStandard',
    'cannibal_corpse|Cannibal Corpse||genre.death_metal|death_metal|1990s|brutal,heavy,dark|g=78,ti=86,ba=52|dStandard,dropC',
    'morbid_angel|Morbid Angel||genre.death_metal|death_metal|1980s,1990s|chaotic,heavy,dark|g=76,sa=78,ti=80|dStandard',
    'obituary|Obituary||genre.death_metal|death_metal|1980s,1990s|groovy,slow-heavy,murky|g=74,ti=68,ba=58,lm=52|dStandard',
    'carcass|Carcass||genre.death_metal|death_metal,melodic_death_metal|1980s,1990s|gritty,melodic,aggressive|g=72,ti=78,mi=48|dStandard',
    'entombed|Entombed||genre.death_metal|death_metal|1990s|buzzsaw,swedish,raw|g=80,sa=82,ti=76,mi=42|dropC,dStandard',
    'bolt_thrower|Bolt Thrower||genre.death_metal|death_metal|1990s|heavy,marching,murky|g=74,ti=66,ba=58|dStandard',
    'deicide|Deicide||genre.death_metal|death_metal|1990s|brutal,fast,sharp|g=78,ti=88|dropC',
    'suffocation|Suffocation||genre.technical_death_metal|technical_death_metal,death_metal|1990s|brutal,technical,tight|g=76,ti=90|dropC',
    'autopsy|Autopsy||genre.death_metal|death_metal,doom_metal|1980s,1990s|dirty,slow-heavy,raw|g=74,sa=76,ti=56,lofi=25|dStandard',
    'napalm_death|Napalm Death||genre.death_metal|death_metal|1980s,1990s|grind,chaotic,raw|g=78,sa=80,ti=82,lofi=20|eStandard,dStandard',
    'dismember|Dismember||genre.death_metal|death_metal|1990s|buzzsaw,swedish,dense|g=80,sa=82,ti=78,mi=42|dropC',
    'immolation|Immolation||genre.death_metal|death_metal|1990s|dissonant,dark,heavy|g=74,ti=80,tr=50|dStandard',
    'vader|Vader||genre.death_metal|death_metal,thrash_metal|1990s|fast,precise,aggressive|g=74,ti=86|dStandard',
    'hypocrisy|Hypocrisy||genre.death_metal|death_metal,melodic_death_metal|1990s,2000s|melodic,dark,heavy|g=72,ti=80,su=66|dStandard',
    'necrophagist|Necrophagist||genre.technical_death_metal|technical_death_metal|2000s|precise,virtuosic,clear|g=68,ti=92,clarity=88|eStandard,dStandard',
    'gorguts|Gorguts||genre.technical_death_metal|technical_death_metal|1990s,2010s|dissonant,complex,dark|g=72,ti=84|dStandard',
    'cynic|Cynic||genre.technical_death_metal|technical_death_metal,fusion|1990s|jazzy,clean-tones,progressive|g=60,ti=76,clarity=84|eStandard',
    'obscura|Obscura||genre.technical_death_metal|technical_death_metal,progressive_metal|2000s,2010s|technical,melodic,clear|g=68,ti=88,clarity=84|dStandard',
    'beyond_creation|Beyond Creation||genre.technical_death_metal|technical_death_metal|2010s|fluid,technical,precise|g=68,ti=90|dStandard',
    'origin|Origin||genre.technical_death_metal|technical_death_metal|2000s|extreme,fast,precise|g=74,ti=92|dropC',
    'revocation|Revocation||genre.technical_death_metal|technical_death_metal,thrash_metal|2010s|technical,thrashy,tight|g=70,ti=88|dStandard',
    'archspire|Archspire||genre.technical_death_metal|technical_death_metal|2010s|extreme,ultra-precise,clear|g=70,ti=94,clarity=86|dStandard',
    'fleshgod_apocalypse|Fleshgod Apocalypse||genre.technical_death_metal|technical_death_metal,symphonic_metal|2010s|orchestral,brutal,polished|g=72,ti=90,re=10|dStandard',
    'mayhem|Mayhem||genre.black_metal|black_metal|1990s|cold,raw,tremolo-picking|g=76,lofi=50|eStandard',
    'emperor|Emperor||genre.black_metal|black_metal,symphonic_metal|1990s|symphonic,cold,dense|g=74,sa=76,tr=72|eStandard',
    'immortal|Immortal||genre.black_metal|black_metal|1990s|icy,fast,tremolo-picking|g=76,tr=72,lofi=40|eStandard',
    'dimmu_borgir|Dimmu Borgir||genre.black_metal|black_metal,symphonic_metal|1990s,2000s|symphonic,polished,dramatic|g=72,ti=78,clarity=70,re=14|eStandard,dStandard',
    'behemoth|Behemoth||genre.black_metal|black_metal,death_metal|1990s,2000s|brutal,precise,modern|g=74,ti=86,clarity=68|dStandard',
    'darkthrone|Darkthrone||genre.black_metal|black_metal|1990s|raw,lo-fi,primitive|g=76,lofi=65,sa=76|eStandard',
    'satyricon|Satyricon||genre.black_metal|black_metal|1990s,2000s|cold,rhythmic,heavy|g=72,ti=74,lofi=30|eStandard',
    'cradle_of_filth|Cradle of Filth||genre.black_metal|black_metal,gothic_metal|1990s,2000s|theatrical,polished,symphonic|g=70,ti=78,re=16|dStandard',
    'watain|Watain||genre.black_metal|black_metal|2000s|raw,cold,aggressive|g=76,lofi=45|eStandard',
    'marduk|Marduk||genre.black_metal|black_metal|1990s|fast,raw,brutal|g=78,ti=84,lofi=35|eStandard',
    'enslaved|Enslaved||genre.black_metal|black_metal,progressive_metal,viking_metal|1990s,2000s|progressive,epic,wide|g=66,su=72,re=22|eStandard',
    'opeth|Opeth||style.progressive_metal|progressive_metal,death_metal|1990s,2000s|dynamic,dark,progressive|g=62,ti=68,warmth=62,dark=50|dStandard',
])

ROWS['metal_symphonic_folk_gothic'] = ('Metal: Symphonic, Gothic, Folk, Viking', 'Symphonic-, Gothic-, Folk- und Viking-Metal-Acts.', [
    'nightwish|Nightwish||genre.symphonic_metal|symphonic_metal,power_metal|1990s,2000s|epic,layered,polished|g=56,ti=76,re=18|eStandard,dStandard',
    'within_temptation|Within Temptation||genre.symphonic_metal|symphonic_metal,gothic_metal|2000s|polished,smooth,layered|g=52,ti=74,mo=12,re=20|dStandard',
    'epica|Epica||genre.symphonic_metal|symphonic_metal|2000s|dense,precise,orchestral|g=60,ti=80|dStandard',
    'kamelot|Kamelot||genre.symphonic_metal|symphonic_metal,power_metal|2000s|dramatic,polished,melodic|g=56,ti=72,su=70|eStandard,dStandard',
    'delain|Delain||genre.symphonic_metal|symphonic_metal|2000s|polished,smooth,melodic|g=52,ti=72|dStandard',
    'therion|Therion||genre.symphonic_metal|symphonic_metal|1990s,2000s|orchestral,dramatic,dense|g=58,ti=70|eStandard',
    'type_o_negative|Type O Negative||genre.gothic_metal|gothic_metal,doom_metal|1990s|dark,heavy,fuzzy-warm|g=62,ba=64,tr=42,dark=78|dStandard,dropC',
    'paradise_lost|Paradise Lost||genre.gothic_metal|gothic_metal,doom_metal|1990s|melancholic,dark,chorused|g=58,ti=52,su=72|dStandard',
    'my_dying_bride|My Dying Bride||genre.doom_stoner|doom_metal,gothic_metal|1990s|mournful,slow,heavy|g=60,ti=36,su=78,re=22|dStandard',
    'anathema|Anathema||genre.gothic_metal|gothic_metal,progressive_rock|1990s,2000s|emotional,dynamic,atmospheric|g=44,su=70,re=30,mo=26|dStandard',
    'lacuna_coil|Lacuna Coil||genre.gothic_metal|gothic_metal,alternative_metal|2000s|modern,dark,dense|g=62,ti=70,ba=54|dStandard',
    'moonspell|Moonspell||genre.gothic_metal|gothic_metal,black_metal|1990s|dark,dramatic,melodic|g=60,ti=64,re=24|eStandard',
    'ensiferum|Ensiferum||genre.folk_viking_metal|folk_metal,melodic_death_metal|2000s|epic,fast,melodic|g=62,ti=78|dStandard',
    'finntroll|Finntroll||genre.folk_viking_metal|folk_metal,black_metal|2000s|bouncy,dark,dense|g=66,ti=74|dStandard',
    'eluveitie|Eluveitie||genre.folk_viking_metal|folk_metal,melodic_death_metal|2000s|melodic,tight,modern|g=64,ti=80,clarity=72|dStandard',
    'korpiklaani|Korpiklaani||genre.folk_viking_metal|folk_metal|2000s|bouncy,fun,driving|g=54,ti=66|eStandard',
    'turisas|Turisas||genre.folk_viking_metal|folk_metal,symphonic_metal|2000s|epic,cinematic,polished|g=58,ti=72,re=18|eStandard',
    'tyr|Týr||genre.folk_viking_metal|viking_metal,power_metal|2000s|melodic,driving,epic|g=58,ti=72,su=70|eStandard',
])

ROWS['metal_doom_sludge_post'] = ('Metal: Doom, Stoner, Sludge, Post', 'Doom-, Stoner-, Sludge- und Post-Metal-Acts.', [
    'candlemass|Candlemass||genre.doom_stoner|doom_metal|1980s|epic,slow,heavy|g=60,ti=40,su=76|dStandard',
    'saint_vitus|Saint Vitus||genre.doom_stoner|doom_metal|1980s|slow,raw,vintage|g=62,ti=32,lofi=25,vintage=70|eStandard',
    'pentagram|Pentagram||genre.doom_stoner|doom_metal,heavy_metal|1970s|vintage,raw,bluesy|g=54,vintage=80,ti=36|eStandard',
    'electric_wizard|Electric Wizard||genre.doom_stoner|doom_metal,stoner_metal|1990s,2000s|fuzzy,wall-of-sound,murky|g=76,sa=84,ti=26,fuzz=80|dropC,cSharpStandard',
    'sleep|Sleep||genre.doom_stoner|stoner_metal,doom_metal|1990s|heavy,fuzzy,hypnotic|g=70,sa=78,ba=70,fuzz=70|dStandard',
    'kyuss|Kyuss||genre.doom_stoner|stoner_metal|1990s|desert,fuzzy,warm|g=64,ba=66,fuzz=65,warmth=62|dStandard',
    'monster_magnet|Monster Magnet||genre.doom_stoner|stoner_metal,psychedelic_rock|1990s|spacey,fuzzy,riff-driven|g=64,mo=16,fuzz=55|eStandard',
    'clutch|Clutch||genre.doom_stoner|stoner_metal,hard_rock|1990s,2000s|groovy,bluesy,warm|g=54,mi=60,fuzz=30,warmth=60|eStandard',
    'high_on_fire|High on Fire||genre.sludge_metal|sludge_metal,thrash_metal|2000s|aggressive,thick,fast-heavy|g=72,sa=76,ti=54|dropC',
    'melvins|Melvins||genre.sludge_metal|sludge_metal,grunge|1980s,1990s|sludgy,noisy,heavy|g=68,ti=34,lofi=25|dropD',
    'eyehategod|Eyehategod||genre.sludge_metal|sludge_metal|1990s|dirty,feedback,murky|g=72,sa=80,lofi=30,fuzz=50|dStandard',
    'acid_bath|Acid Bath||genre.sludge_metal|sludge_metal|1990s|dark,murky,heavy|g=66,ti=38|dStandard',
    'baroness|Baroness||genre.sludge_metal|sludge_metal,progressive_metal|2000s|melodic,dynamic,warm|g=58,ti=52,su=70,mi=58|dStandard',
    'corrosion_of_conformity|Corrosion of Conformity||genre.sludge_metal|sludge_metal,southern_rock|1990s|groovy,southern,riff-driven|g=58,ti=48,mi=60|dStandard',
    'neurosis|Neurosis||genre.post_metal|post_metal,sludge_metal|1990s|heavy,dynamic,tribal|g=64,ti=44,su=76|dStandard',
    'isis|Isis||genre.post_metal|post_metal|2000s|wide,heavy,dynamic|g=62,ti=42,su=78,width=85|dropC',
    'cult_of_luna|Cult of Luna||genre.post_metal|post_metal,sludge_metal|2000s|heavy,atmospheric,slow|g=64,ti=42,re=40|dStandard',
    'pelican|Pelican||genre.post_metal|post_metal|2000s|instrumental,heavy,melodic|g=58,ti=46,su=74|dropC',
    'russian_circles|Russian Circles||genre.post_metal|post_metal,post_rock|2000s|instrumental,dynamic,heavy|g=52,su=78,de=30,re=44|dropC',
    'mastodon|Mastodon||genre.sludge_metal|sludge_metal,progressive_metal|2000s,2010s|technical,thick,dynamic|g=64,ti=58,mi=54,su=70|dStandard',
])

ROWS['metal_progressive_djent'] = ('Metal: Progressive und Djent', 'Progressive-Metal- und Djent-Acts.', [
    'dream_theater|Dream Theater||style.progressive_metal|progressive_metal|1990s,2000s|virtuosic,clear,layered|g=56,su=74,de=16,clarity=86|eStandard',
    'symphony_x|Symphony X||style.progressive_metal|progressive_metal,power_metal|1990s,2000s|neoclassical,precise,heavy|g=64,ti=76,su=76|eStandard',
    'fates_warning|Fates Warning||style.progressive_metal|progressive_metal|1990s|dynamic,melodic,clean-definition|g=52,ti=62|eStandard',
    'haken|Haken||style.progressive_metal|progressive_metal,djent|2010s|dynamic,modern,layered|g=62,ti=74,clarity=80|eStandard,dStandard',
    'leprous|Leprous||style.progressive_metal|progressive_metal|2010s|moody,dynamic,dark|g=56,ti=66,dark=50|dStandard',
    'between_the_buried_and_me|Between the Buried and Me|BTBAM|style.progressive_metal|progressive_metal,metalcore|2000s|complex,heavy,dynamic|g=66,ti=78|dStandard',
    'pain_of_salvation|Pain of Salvation||style.progressive_metal|progressive_metal|2000s|dynamic,emotional,varied|g=54,ti=62|eStandard',
    'periphery|Periphery||style.modern_djent|djent,progressive_metal|2010s|precise,melodic,modern|g=72,su=64,de=12|dropB,dropA',
    'tesseract|TesseracT||style.modern_djent|djent,progressive_metal|2010s|atmospheric,precise,wide|g=68,su=68,de=20,re=18|dropB',
    'animals_as_leaders|Animals as Leaders||style.modern_djent|djent,progressive_metal|2010s|virtuosic,clear,instrumental|g=62,clarity=90,de=14|dropA',
    'vildhjarta|Vildhjärta||style.modern_djent|djent|2010s|extreme,downtuned,heavy|g=76,ti=96,ba=54|dropA',
    'monuments|Monuments||style.modern_djent|djent,metalcore|2010s|groovy,precise,melodic|g=72|dropB',
    'textures|Textures||style.modern_djent|djent,progressive_metal|2000s|technical,tight,heavy|g=74|dropB',
    'northlane|Northlane||style.modern_djent|djent,metalcore|2010s|atmospheric,heavy,modern|g=70,re=14,de=10|dropB',
    'intervals|Intervals||style.modern_djent|djent,progressive_metal|2010s|melodic,clear,instrumental|g=62,clarity=88|dropB',
    'volumes|Volumes||style.modern_djent|djent,metalcore|2010s|groovy,modern,heavy|g=72|dropB',
])

ROWS['metal_nu_alt_industrial'] = ('Metal: Nu, Alternative, Industrial', 'Nu-, Alternative- und Industrial-Metal-Acts.', [
    'limp_bizkit|Limp Bizkit||genre.nu_metal|nu_metal|1990s,2000s|groovy,bouncy,scooped|g=60,ba=66,mi=34|dropD',
    'deftones|Deftones||genre.alt_metal|alternative_metal,post_metal|1990s,2000s|dark,wide,heavy,dreamy|g=62,ba=60,mo=18,re=26,dark=62,width=70|dropC,cSharpStandard',
    'disturbed|Disturbed||genre.nu_metal|nu_metal,heavy_metal|2000s|tight,punchy,mid-forward|g=66,ti=78,mi=44|dStandard,dropC',
    'godsmack|Godsmack||genre.nu_metal|nu_metal,alternative_metal|1990s,2000s|groovy,dark,heavy|g=62,ba=60,ti=58|dStandard',
    'papa_roach|Papa Roach||genre.nu_metal|nu_metal|2000s|bouncy,punchy,direct|g=60,ti=66|dropD',
    'mudvayne|Mudvayne||genre.nu_metal|nu_metal,progressive_metal|2000s|technical,scooped,heavy|g=68,ti=76,mi=36|dropC,dropB',
    'drowning_pool|Drowning Pool||genre.nu_metal|nu_metal|2000s|aggressive,direct|g=66,ti=70|dropD',
    'stone_sour|Stone Sour||genre.alt_metal|alternative_metal,post_grunge|2000s|dynamic,melodic,heavy|g=56,ti=66|dropD',
    'coal_chamber|Coal Chamber||genre.nu_metal|nu_metal|1990s|groovy,dark,heavy|g=64,ba=62|dropB',
    'faith_no_more|Faith No More||genre.alt_metal|alternative_metal|1980s,1990s|varied,dynamic,funky|g=52,ba=58,ti=62|eStandard',
    'ghost|Ghost||style.dark_modern_metal|heavy_metal,hard_rock|2010s|theatrical,melodic,polished|g=54,ti=66,su=68,re=20|dStandard',
    'jinjer|Jinjer||style.dark_modern_metal|metalcore,groove_metal|2010s|tight,precise,modern|g=68,ti=86|dropC',
    'fear_factory|Fear Factory||genre.industrial_metal|industrial_metal,groove_metal|1990s|machine,tight,gated|g=72,ti=92,gs=80|dStandard,dropC',
    'ministry|Ministry||genre.industrial_metal|industrial_metal,thrash_metal|1990s|aggressive,mechanical,dense|g=70,sa=76,ti=84|dStandard',
    'nine_inch_nails|Nine Inch Nails|NIN|genre.industrial_metal|industrial_metal,alternative_rock|1990s|noisy,layered,distorted|g=58,sa=72,ti=70,lofi=30|eStandard',
    'static_x|Static-X||genre.industrial_metal|industrial_metal,nu_metal|1990s,2000s|mechanical,chugging,tight|g=68,ti=88|dropC',
    'marilyn_manson|Marilyn Manson||genre.industrial_metal|industrial_metal,alternative_rock|1990s|dark,gritty,theatrical|g=58,sa=66,ti=60,dark=60|dStandard',
    'godflesh|Godflesh||genre.industrial_metal|industrial_metal,post_metal|1990s|crushing,mechanical,slow|g=70,ti=60,ba=64|dropC',
    'kmfdm|KMFDM||genre.industrial_metal|industrial_metal|1990s|rhythmic,synthetic,tight|g=60,ti=82,lofi=15|eStandard',
    'rob_zombie|Rob Zombie||genre.industrial_metal|industrial_metal,groove_metal|1990s,2000s|groovy,fuzzy,dark|g=64,ti=68,fuzz=30|dStandard',
])

ROWS['metal_modern'] = ('Metal: Metalcore, Deathcore, Modern', 'Metalcore-, Deathcore- und moderne Metal-Acts.', [
    'as_i_lay_dying|As I Lay Dying||style.melodic_metalcore|metalcore,melodic_metalcore|2000s|melodic,tight,clear|g=72,ti=88|dropC,dStandard',
    'parkway_drive|Parkway Drive||style.melodic_metalcore|metalcore,melodic_metalcore|2000s,2010s|aggressive,tight,modern|g=72,ti=86,ba=48|dropC,dropB',
    'architects|Architects||style.dark_modern_metal|metalcore,djent|2010s|dark,heavy,modern|g=70,ti=86,re=14|dropB,dropC',
    'bring_me_the_horizon|Bring Me the Horizon|BMTH|genre.modern_metal|metalcore,deathcore,alternative_rock|2000s,2010s|dynamic,polished,heavy|g=68,ti=82,re=12|dropC,dropB',
    'august_burns_red|August Burns Red||style.melodic_metalcore|metalcore|2000s|technical,bright-leads,tight|g=68,ti=86,um=66|dropC,dStandard',
    'unearth|Unearth||style.melodic_metalcore|metalcore,melodic_metalcore|2000s|thrashy,tight,aggressive|g=72,ti=86|dropD,dropC',
    'shadows_fall|Shadows Fall||style.melodic_metalcore|metalcore,thrash_metal|2000s|thrashy,melodic,tight|g=70,ti=84|dStandard',
    'atreyu|Atreyu||style.melodic_metalcore|metalcore,post_hardcore|2000s|melodic,emotional,tight|g=66,ti=80|dropC',
    'all_that_remains|All That Remains||style.melodic_metalcore|metalcore,melodic_death_metal|2000s|melodic,polished,tight|g=68,ti=84|dropC',
    'underoath|Underoath||genre.modern_metal|metalcore,post_hardcore|2000s|dynamic,wide,emotional|g=64,ti=78,re=14|dropB,dropC',
    'asking_alexandria|Asking Alexandria||genre.modern_metal|metalcore|2010s|polished,heavy,modern|g=68,ti=84|dropC,dropB',
    'miss_may_i|Miss May I||style.melodic_metalcore|metalcore,deathcore|2010s|aggressive,tight,modern|g=72,ti=88|dropB',
    'while_she_sleeps|While She Sleeps||style.melodic_metalcore|metalcore|2010s|aggressive,anthemic,tight|g=72,ti=86|dropC,dropB',
    'bury_tomorrow|Bury Tomorrow||style.melodic_metalcore|metalcore|2010s|anthemic,tight,modern|g=68,ti=84|dropC',
    'caliban|Caliban||style.melodic_metalcore|metalcore|2000s|german-metalcore,tight,heavy|g=72,ti=84|dropB,dropC',
    'heaven_shall_burn|Heaven Shall Burn||style.melodic_metalcore|metalcore,melodic_death_metal|2000s|aggressive,melodic,tight|g=74,ti=86|dropC',
    'whitechapel|Whitechapel||style.deathcore|deathcore|2000s|brutal,downtuned,tight|g=78,ti=92|dropB,dropA',
    'suicide_silence|Suicide Silence||style.deathcore|deathcore|2000s|brutal,downtuned,heavy|g=78,ti=90,ba=54|dropB,dropA',
    'lorna_shore|Lorna Shore||style.deathcore|deathcore,symphonic_metal|2010s,2020s|extreme,dramatic,polished|g=76,ti=92,re=10|dropA,dropB',
    'carnifex|Carnifex||style.deathcore|deathcore,symphonic_metal|2000s|dark,heavy,dramatic|g=76,ti=90|dropB',
    'thy_art_is_murder|Thy Art Is Murder||style.deathcore|deathcore|2010s|brutal,heavy,tight|g=78,ti=92|dropB,dropA',
    'job_for_a_cowboy|Job for a Cowboy||style.deathcore|deathcore,death_metal|2000s|brutal,dense,tight|g=76,ti=90|dropC,dropB',
    'despised_icon|Despised Icon||style.deathcore|deathcore|2000s|brutal,fast,tight|g=76,ti=90|dropB',
    'chelsea_grin|Chelsea Grin||style.deathcore|deathcore|2010s|brutal,heavy,downtuned|g=78,ti=90|dropA',
    'spiritbox|Spiritbox||style.dark_modern_metal|metalcore,djent,alternative_metal|2010s,2020s|dark,dynamic,atmospheric,modern|g=68,ti=84,dark=60|dropB,dropC',
    'bad_omens|Bad Omens||style.dark_modern_metal|metalcore,alternative_metal|2010s,2020s|dark,polished,modern|g=64,ti=78,dark=58|dropC',
    'sleep_token|Sleep Token||style.dark_modern_metal|alternative_metal,djent|2010s,2020s|dynamic,atmospheric,polished|g=58,ti=72,re=22,de=16|dropC,dropB',
    'motionless_in_white|Motionless in White||style.dark_modern_metal|metalcore,industrial_metal|2010s|dark,heavy,polished|g=68,ti=84|dropB,dropC',
])


def build():
    for pack, spec in ROWS.items():
        name, desc, rows = spec
        C.pack(pack, name, desc, 'STYLE_INSPIRED')
        for row in rows:
            if row:
                artist(row)
