"""Rock, punk, emo, shoegaze and post-rock artists (same row format as artists_metal.py)."""
from common import C, artist

ROWS = {}

ROWS['rock_classic'] = ('Rock: Classic', 'Classic-, Blues-, Southern- und Psychedelic-Rock-Acts.', [
    'the_who|The Who||style.classic_rock_early|classic_rock,hard_rock|1960s,1970s|punchy,power-chords,raw|g=52,ti=48,mi=64,pr=56|eStandard',
    'the_rolling_stones|The Rolling Stones|Rolling Stones|style.classic_rock_early|classic_rock,blues_rock|1960s,1970s|raw,loose,riff-driven,open-tunings|g=40,ti=32,mi=62,lofi=15|eStandard',
    'cream|Cream||style.classic_rock_early|classic_rock,blues_rock|1960s|woody,singing,vintage|g=48,su=74,mi=64,warmth=70|eStandard',
    'eric_clapton|Eric Clapton|Clapton|genre.blues_rock|blues_rock,classic_rock|1960s,1970s,1980s|smooth,singing,warm|g=34,su=66,warmth=72|eStandard',
    'dire_straits|Dire Straits||genre.blues_rock|classic_rock,blues_rock|1970s,1980s|clean-crunch,articulate,snappy|g=22,ti=40,at=70,clarity=82|eStandard',
    'zz_top|ZZ Top||genre.blues_rock|blues_rock,hard_rock|1970s,1980s|gritty,texas,boogie|g=46,sa=52,mi=62,fuzz=25|eStandard',
    'aerosmith|Aerosmith||genre.hard_rock|hard_rock,blues_rock|1970s,1980s|gritty,bluesy,riff-driven|g=54,mi=64,tr=54|eStandard',
    'fleetwood_mac|Fleetwood Mac||genre.classic_rock|classic_rock,blues_rock|1970s|clean-warm,melodic,layered|g=24,ti=36,warmth=68,clarity=72|eStandard',
    'eagles|Eagles||genre.classic_rock|classic_rock,country|1970s|clean-crunch,layered,twin-lead|g=28,ti=40,clarity=78,warmth=60|eStandard',
    'lynyrd_skynyrd|Lynyrd Skynyrd||genre.southern_rock|southern_rock|1970s|triple-lead,warm,singing|g=46,su=72,warmth=66|eStandard',
    'allman_brothers_band|The Allman Brothers Band|Allman Brothers|genre.southern_rock|southern_rock,blues_rock|1970s|singing,warm,twin-lead,slide|g=40,su=78,warmth=70|eStandard',
    'creedence_clearwater_revival|Creedence Clearwater Revival|CCR|genre.southern_rock|classic_rock,southern_rock|1960s,1970s|swampy,twangy,direct|g=34,tr=58,mi=64|eStandard',
    'the_doors|The Doors|Doors|genre.psychedelic_rock|psychedelic_rock,classic_rock|1960s|dark,swirling,vintage|g=32,su=60,dark=45|eStandard',
    'the_kinks|The Kinks|Kinks|genre.garage_rock|garage_rock,classic_rock|1960s|raw,crunchy,riff-driven|g=54,mi=64,lofi=30|eStandard',
    'the_beatles|The Beatles|Beatles|style.classic_rock_early|classic_rock,psychedelic_rock|1960s|jangly,varied,warm|g=30,ti=30,tr=58,mo=16|eStandard',
    'santana|Santana||genre.psychedelic_rock|classic_rock,psychedelic_rock|1970s|singing,sustaining,warm|g=52,su=86,mi=64,warmth=68|eStandard',
    'bad_company|Bad Company||genre.classic_rock|classic_rock,hard_rock|1970s|bluesy,direct,solid|g=44,mi=64|eStandard',
    'free|Free||genre.blues_rock|classic_rock,blues_rock|1970s|raw,bluesy,minimal|g=42,ti=38,mi=64|eStandard',
    'thin_lizzy|Thin Lizzy||genre.hard_rock|hard_rock,classic_rock|1970s|twin-lead,melodic,warm|g=54,su=70,mi=62|eStandard',
    'boston|Boston||style.hard_rock_80s|hard_rock,classic_rock|1970s|polished,layered,sustaining|g=54,su=74,co=32|eStandard',
    'journey|Journey||style.hard_rock_80s|hard_rock|1980s|polished,melodic,singing|g=44,su=76,re=20|eStandard',
    'kansas|Kansas||genre.classic_rock|classic_rock,progressive_rock|1970s|melodic,layered,clean-crunch|g=38,clarity=74|eStandard',
    'foreigner|Foreigner||style.hard_rock_80s|hard_rock,classic_rock|1970s,1980s|polished,punchy,radio|g=50,co=30|eStandard',
    'bruce_springsteen|Bruce Springsteen|Springsteen|genre.classic_rock|classic_rock|1970s,1980s|warm,anthemic,direct|g=32,ti=38,warmth=65|eStandard',
    'tom_petty|Tom Petty|Tom Petty and the Heartbreakers|genre.classic_rock|classic_rock|1970s,1980s|jangly,bright,direct|g=28,tr=60,at=64|eStandard',
    'neil_young|Neil Young|Neil Young and Crazy Horse|genre.garage_rock|classic_rock,garage_rock|1970s,1990s|raw,fuzzy,loose|g=58,sa=64,fuzz=45,lofi=20|dStandard,eStandard',
    'steve_miller_band|Steve Miller Band||genre.classic_rock|classic_rock|1970s|smooth,clean-crunch,warm|g=26,warmth=64|eStandard',
    'steppenwolf|Steppenwolf||genre.classic_rock|classic_rock,hard_rock|1960s|gritty,raw,bluesy|g=48,mi=64|eStandard',
    'grand_funk_railroad|Grand Funk Railroad||genre.hard_rock|hard_rock,classic_rock|1970s|loud,raw,direct|g=54,mi=62|eStandard',
])

ROWS['rock_hard_glam'] = ('Rock: Hard Rock und Glam', 'Hard-Rock-, Glam- und Hair-Metal-Acts.', [
    'bon_jovi|Bon Jovi||genre.glam_metal|glam_metal,hard_rock|1980s|polished,anthemic,bright|g=52,tr=62|eStandard',
    'def_leppard|Def Leppard||genre.glam_metal|glam_metal,hard_rock|1980s|layered,polished,tight|g=54,ti=64,clarity=76|eStandard',
    'motley_crue|Mötley Crüe|Motley Crue|genre.glam_metal|glam_metal,hard_rock|1980s|gritty,raw-glam,punchy|g=60,sa=58,mi=62|eStandard',
    'whitesnake|Whitesnake||genre.hard_rock|hard_rock,blues_rock|1980s|bluesy,polished,warm|g=54,su=70,warmth=60|eStandard',
    'scorpions|Scorpions||genre.hard_rock|hard_rock,heavy_metal|1980s|melodic,tight,bright|g=56,ti=62,su=70|eStandard',
    'europe|Europe||genre.glam_metal|glam_metal,hard_rock|1980s|melodic,bright,neoclassical|g=54,su=74,de=14|eStandard',
    'poison|Poison||genre.glam_metal|glam_metal|1980s|bright,poppy,chorused|g=54,mo=22|eStandard',
    'skid_row|Skid Row||genre.glam_metal|glam_metal,hard_rock|1980s,1990s|raw,aggressive,punchy|g=62,mi=62|eStandard',
    'ratt|Ratt||genre.glam_metal|glam_metal|1980s|bright,tight,riff-driven|g=58,ti=62,tr=64|eStandard',
    'twisted_sister|Twisted Sister||genre.glam_metal|glam_metal,heavy_metal|1980s|anthemic,punchy,raw|g=58,mi=62|eStandard',
    'kiss|Kiss||genre.hard_rock|hard_rock,glam_metal|1970s|punchy,simple,anthemic|g=50,mi=64,tr=56|eStandard',
    'alice_cooper|Alice Cooper||genre.hard_rock|hard_rock,glam_metal|1970s,1980s|theatrical,gritty,raw|g=54,mi=64|eStandard',
    'cinderella|Cinderella||genre.glam_metal|glam_metal,blues_rock|1980s|bluesy,gritty,bright|g=56,tr=62|eStandard',
    'warrant|Warrant||genre.glam_metal|glam_metal|1980s,1990s|polished,catchy,bright|g=52,mo=20|eStandard',
    'dokken|Dokken||genre.glam_metal|glam_metal,heavy_metal|1980s|precise,melodic,tight|g=58,ti=64,su=70|eStandard',
    'quiet_riot|Quiet Riot||genre.glam_metal|glam_metal|1980s|punchy,direct,polished|g=56|eStandard',
    'extreme|Extreme||genre.glam_metal|glam_metal,hard_rock|1990s|funky,virtuosic,tight|g=54,ti=64,clarity=76|eStandard',
    'winger|Winger||genre.glam_metal|glam_metal|1980s,1990s|polished,virtuosic,bright|g=54,tr=64|eStandard',
    'slash|Slash||genre.hard_rock|hard_rock,blues_rock|1990s,2000s|singing,warm,bluesy|g=58,su=78,warmth=64|eStandard',
    'ufo|UFO||genre.hard_rock|hard_rock,heavy_metal|1970s|melodic,vintage,mid-forward|g=52,su=68,mi=64|eStandard',
    'black_stone_cherry|Black Stone Cherry||genre.hard_rock|hard_rock,southern_rock|2000s|modern,thick,groovy|g=58,ba=54|dStandard',
    'airbourne|Airbourne||genre.hard_rock|hard_rock|2000s|raw,loud,energetic|g=56,mi=64|eStandard',
    'rival_sons|Rival Sons||genre.hard_rock|hard_rock,blues_rock|2010s|vintage,warm,gritty|g=48,vintage=75|eStandard',
    'greta_van_fleet|Greta Van Fleet||genre.hard_rock|hard_rock,classic_rock|2010s|vintage,bright,driving|g=50,vintage=78|eStandard',
    'volbeat|Volbeat||genre.hard_rock|hard_rock,rockabilly|2000s|rockabilly-metal,punchy,warm|g=56,mi=62|eStandard,dStandard',
])

ROWS['rock_progressive'] = ('Rock: Progressive', 'Progressive-Rock-Acts.', [
    'rush|Rush||genre.progressive_rock|progressive_rock,hard_rock|1970s,1980s|layered,chorused,precise|g=44,mo=24,clarity=78|eStandard',
    'yes|Yes||genre.progressive_rock|progressive_rock|1970s|bright,twangy,intricate|g=34,tr=60,clarity=76|eStandard',
    'king_crimson|King Crimson||genre.progressive_rock|progressive_rock|1970s,1980s|angular,dissonant,heavy|g=50,sa=56,ti=54|eStandard',
    'porcupine_tree|Porcupine Tree||genre.progressive_rock|progressive_rock,alternative_rock|2000s|layered,moody,dynamic|g=46,mo=22,de=20,re=30|dStandard,eStandard',
    'genesis|Genesis||genre.progressive_rock|progressive_rock|1970s|layered,melodic,warm|g=30,warmth=66,mo=22|eStandard',
    'gentle_giant|Gentle Giant||genre.progressive_rock|progressive_rock|1970s|intricate,dry,clear|g=30,re=14,clarity=78|eStandard',
    'camel|Camel||genre.progressive_rock|progressive_rock|1970s|singing,warm,melodic|g=36,su=78,warmth=70|eStandard',
    'marillion|Marillion||genre.progressive_rock|progressive_rock|1980s|emotional,singing,spacious|g=40,su=78,de=24,re=32|eStandard',
    'steven_wilson|Steven Wilson||genre.progressive_rock|progressive_rock,progressive_metal|2000s,2010s|modern,layered,dynamic|g=46,mo=20,re=30|dStandard',
])

ROWS['rock_grunge_alt'] = ('Rock: Grunge, Post-Grunge, Alternative, Indie', 'Grunge-, Post-Grunge-, Alternative- und Indie-Rock-Acts.', [
    'pearl_jam|Pearl Jam||genre.grunge|grunge,alternative_rock|1990s|warm,dynamic,organic|g=52,warmth=64,mi=58|eStandard',
    'stone_temple_pilots|Stone Temple Pilots|STP|genre.grunge|grunge,alternative_rock|1990s|fuzzy,layered,thick|g=60,fuzz=35,ba=56|dStandard',
    'mudhoney|Mudhoney||genre.grunge|grunge,garage_rock|1980s,1990s|fuzzy,raw,lo-fi|g=68,sa=74,fuzz=55,lofi=40|eStandard',
    'screaming_trees|Screaming Trees||genre.grunge|grunge,psychedelic_rock|1990s|warm,psychedelic,gritty|g=56,warmth=62|eStandard',
    'temple_of_the_dog|Temple of the Dog||genre.grunge|grunge|1990s|warm,melodic,heavy|g=54,warmth=64|dStandard',
    'hole|Hole||genre.grunge|grunge,alternative_rock|1990s|raw,noisy,gritty|g=62,lofi=35|eStandard',
    'l7|L7||genre.grunge|grunge,punk_rock|1990s|raw,heavy,punky|g=64,ti=50|eStandard',
    'bush|Bush||genre.post_grunge|post_grunge,grunge|1990s|dense,polished,heavy|g=58,ba=56|dStandard',
    'silverchair|Silverchair||genre.post_grunge|post_grunge,grunge|1990s,2000s|heavy,dynamic,thick|g=58,ba=56|dStandard,dropD',
    'candlebox|Candlebox||genre.post_grunge|post_grunge|1990s|warm,radio,dynamic|g=52,warmth=60|eStandard',
    'creed|Creed||genre.post_grunge|post_grunge|1990s,2000s|thick,polished,anthemic|g=56,ba=56|dStandard,dropD',
    'nickelback|Nickelback||genre.post_grunge|post_grunge,hard_rock|2000s|polished,heavy,radio|g=58,ti=58|dropD',
    'three_doors_down|Three Doors Down||genre.post_grunge|post_grunge|2000s|warm,radio,melodic|g=50,mo=10|eStandard',
    'staind|Staind||genre.post_grunge|post_grunge,alternative_metal|2000s|dark,heavy,emotional|g=56,ba=58,dark=55|dropC,dropD',
    'puddle_of_mudd|Puddle of Mudd||genre.post_grunge|post_grunge|2000s|thick,radio,direct|g=56|dropD',
    'queens_of_the_stone_age|Queens of the Stone Age|QOTSA|genre.alt_indie|alternative_rock,stoner_metal|1990s,2000s|desert,groovy,fuzzy|g=56,ba=56,fuzz=35,ti=48|dStandard,dropC',
    'smashing_pumpkins|Smashing Pumpkins|Pumpkins|genre.alt_indie|alternative_rock,shoegaze|1990s|wall-of-fuzz,layered,heavy|g=60,sa=70,fuzz=55,width=70|dStandard,dropD',
    'rage_against_the_machine|Rage Against the Machine|RATM|genre.alt_indie|alternative_rock,alternative_metal|1990s|funky,wah-driven,dry|g=54,ti=60,mi=62,re=6|dStandard,dropD',
    'audioslave|Audioslave||genre.alt_indie|alternative_rock,hard_rock|2000s|warm,heavy,dynamic|g=52,warmth=60|dropD',
    'the_strokes|The Strokes|Strokes|style.britpop_indie|indie_rock,garage_rock|2000s|dry,jangly,tight|g=40,ti=50,tr=60,lofi=20,re=8|eStandard',
    'the_white_stripes|The White Stripes|White Stripes|genre.garage_rock|garage_rock,blues_rock|2000s|raw,fuzzy,lo-fi|g=60,sa=66,fuzz=45,lofi=35|eStandard',
    'oasis|Oasis||style.britpop_indie|alternative_rock,indie_rock|1990s|wall-of-sound,anthemic,thick|g=50,sa=56,mi=64|eStandard',
    'blur|Blur||style.britpop_indie|alternative_rock,indie_rock|1990s|angular,quirky,bright|g=46,tr=60|eStandard',
    'the_cure|The Cure||genre.post_punk|post_punk,alternative_rock|1980s|chorused,dark,spacey|g=30,mo=34,re=32,dark=55|eStandard',
    'the_smiths|The Smiths||style.britpop_indie|indie_rock,post_punk|1980s|jangly,bright,arpeggiated|g=20,tr=64,mo=18,clarity=78|eStandard',
    'u2|U2||genre.alt_indie|alternative_rock,post_punk|1980s,1990s|delay-driven,shimmering,anthemic|g=30,de=42,re=30,clarity=80|eStandard',
    'rem|R.E.M.|REM|style.britpop_indie|alternative_rock,indie_rock|1980s,1990s|jangly,warm,arpeggiated|g=22,tr=60,warmth=58|eStandard',
    'pixies|Pixies||genre.alt_indie|alternative_rock,indie_rock|1980s|angular,raw,loud-quiet|g=52,lofi=25,tr=58|eStandard',
    'sonic_youth|Sonic Youth||genre.alt_indie|alternative_rock,indie_rock|1980s,1990s|noisy,dissonant,experimental|g=54,sa=66,lofi=30|eStandard',
    'weezer|Weezer||genre.alt_indie|alternative_rock,pop_punk|1990s|crunchy,bright,catchy|g=54,tr=58,mi=58|dStandard,eStandard',
    'placebo|Placebo||genre.alt_indie|alternative_rock|2000s|edgy,dark,layered|g=52,dark=50|eStandard',
    'interpol|Interpol||genre.post_punk|post_punk,indie_rock|2000s|cold,angular,delay-tinged|g=32,de=18,tr=62|eStandard',
    'kings_of_leon|Kings of Leon||style.britpop_indie|indie_rock,southern_rock|2000s|warm,twangy,gritty|g=44,warmth=58|eStandard',
    'the_killers|The Killers|Killers|style.britpop_indie|indie_rock,alternative_rock|2000s|anthemic,bright,layered|g=42,de=20,re=22|eStandard',
    'franz_ferdinand|Franz Ferdinand||style.britpop_indie|indie_rock,post_punk|2000s|dry,angular,danceable|g=38,tr=62,re=10|eStandard',
    'vampire_weekend|Vampire Weekend||style.britpop_indie|indie_rock|2000s|bright,clean,rhythmic|g=16,tr=62,clarity=80|eStandard',
    'tame_impala|Tame Impala||genre.psychedelic_rock|psychedelic_rock,indie_rock|2010s|phasey,warm,hazy|g=46,mo=36,re=34,de=26|eStandard',
    'foals|Foals||style.britpop_indie|indie_rock|2010s|math-rock,delay-driven,bright|g=32,de=30,tr=64,clarity=80|eStandard',
    'the_black_keys|The Black Keys|Black Keys|genre.garage_rock|garage_rock,blues_rock|2010s|fuzzy,raw,warm|g=60,sa=66,fuzz=50,warmth=60|eStandard',
    'royal_blood|Royal Blood||genre.garage_rock|garage_rock,hard_rock|2010s|bass-heavy,fuzzy,tight|g=62,ba=64,fuzz=45|eStandard',
    'wolf_alice|Wolf Alice||genre.alt_indie|alternative_rock,shoegaze|2010s|dynamic,fuzzy,dreamy|g=50,fuzz=35,re=26|eStandard',
    'biffy_clyro|Biffy Clyro||genre.alt_indie|alternative_rock,post_hardcore|2000s,2010s|dynamic,angular,anthemic|g=56,ti=60|dStandard,dropD',
    'coldplay|Coldplay||genre.clean_pop|alternative_rock,clean_pop|2000s|shimmering,delay-driven,anthemic|g=20,de=38,re=32,mo=20|eStandard',
])

ROWS['punk_emo_posthardcore'] = ('Punk, Pop Punk, Emo, Post-Hardcore', 'Punk-, Pop-Punk-, Emo- und Post-Hardcore-Acts.', [
    'ramones|Ramones||genre.punk_classic|punk_rock|1970s|buzzsaw,downstroke,fast|g=56,ti=64,mi=58|eStandard',
    'sex_pistols|Sex Pistols||genre.punk_classic|punk_rock|1970s|thick,raw,loud|g=58,sa=62,mi=62|eStandard',
    'the_clash|The Clash||genre.punk_classic|punk_rock,post_punk|1970s|raw,bright,rhythmic|g=48,tr=60|eStandard',
    'dead_kennedys|Dead Kennedys||genre.punk_classic|punk_rock|1980s|surfy,raw,angular|g=50,tr=62,lofi=25|eStandard',
    'bad_religion|Bad Religion||genre.punk_classic|punk_rock|1980s,1990s|melodic,fast,tight|g=54,ti=68|eStandard',
    'nofx|NOFX||genre.punk_classic|punk_rock,pop_punk|1990s|melodic,fast,raw|g=52,ti=66|eStandard',
    'descendents|Descendents||genre.punk_classic|punk_rock,pop_punk|1980s|melodic,fast,bright|g=50,tr=60|eStandard',
    'misfits|Misfits||genre.punk_classic|punk_rock|1980s|dark,raw,horror-punk|g=56,dark=45|eStandard',
    'social_distortion|Social Distortion||genre.punk_classic|punk_rock,rockabilly|1980s,1990s|warm,rockabilly-tinged,driving|g=48,warmth=58|eStandard',
    'rancid|Rancid||genre.punk_classic|punk_rock|1990s|raw,rhythmic,tight|g=54,ti=64|eStandard',
    'the_offspring|The Offspring|Offspring|style.pop_punk_modern|pop_punk,punk_rock|1990s|tight,punchy,bright|g=58,ti=66,tr=58|dStandard,eStandard',
    'rise_against|Rise Against||style.pop_punk_modern|punk_rock,pop_punk|2000s|melodic,tight,anthemic|g=58,ti=68|dStandard,dropD',
    'pennywise|Pennywise||genre.punk_classic|punk_rock|1990s|fast,tight,melodic|g=56,ti=68|eStandard',
    'black_flag|Black Flag||genre.punk_classic|punk_rock|1980s|raw,heavy,abrasive|g=62,sa=66,lofi=35|eStandard',
    'minor_threat|Minor Threat||genre.punk_classic|punk_rock|1980s|raw,fast,lo-fi|g=56,lofi=45|eStandard',
    'anti_flag|Anti-Flag||genre.punk_classic|punk_rock|2000s|energetic,tight,direct|g=54,ti=66|eStandard',
    'against_me|Against Me!|Against Me|genre.punk_classic|punk_rock|2000s|energetic,raw,anthemic|g=52,lofi=15|eStandard',
    'flogging_molly|Flogging Molly||genre.punk_classic|punk_rock|2000s|folky,driving,warm|g=40,warmth=58|eStandard',
    'paramore|Paramore||style.pop_punk_modern|pop_punk,emo|2000s,2010s|bright,tight,dynamic|g=52,ti=66,de=12|eStandard,dStandard',
    'fall_out_boy|Fall Out Boy||style.pop_punk_modern|pop_punk,emo|2000s|catchy,tight,bright|g=52,ti=66|eStandard',
    'good_charlotte|Good Charlotte||style.pop_punk_modern|pop_punk|2000s|bright,punchy,radio|g=54|dStandard',
    'simple_plan|Simple Plan||style.pop_punk_modern|pop_punk|2000s|bright,polished,tight|g=52,ti=66|eStandard',
    'all_time_low|All Time Low||style.pop_punk_modern|pop_punk|2000s,2010s|bright,catchy,tight|g=50|eStandard',
    'yellowcard|Yellowcard||style.pop_punk_modern|pop_punk|2000s|bright,melodic,tight|g=52|eStandard',
    'new_found_glory|New Found Glory||style.pop_punk_modern|pop_punk|2000s|melodic,tight,punchy|g=54,ti=68|eStandard',
    'neck_deep|Neck Deep||style.pop_punk_modern|pop_punk|2010s|bright,tight,anthemic|g=52,ti=66|dStandard',
    'the_wonder_years|The Wonder Years||style.pop_punk_modern|pop_punk,emo|2010s|dynamic,anthemic,thick|g=54|dStandard',
    'angels_and_airwaves|Angels & Airwaves||genre.emo|emo,alternative_rock|2000s|delay-driven,spacious,anthemic|g=36,de=40,re=30|eStandard',
    'jimmy_eat_world|Jimmy Eat World||genre.emo|emo,alternative_rock|1990s,2000s|clean-crunch,melodic,layered|g=44,mo=14|eStandard',
    'taking_back_sunday|Taking Back Sunday||genre.emo|emo,post_hardcore|2000s|dynamic,interlocking,bright|g=48|eStandard',
    'dashboard_confessional|Dashboard Confessional||genre.emo|emo|2000s|warm,strummy,expressive|g=24,warmth=60|eStandard',
    'the_used|The Used||genre.emo|emo,post_hardcore|2000s|energetic,thick,dynamic|g=58|dropD',
    'afi|AFI||genre.post_hardcore|post_hardcore,punk_rock|1990s,2000s|dark,melodic,tight|g=58,dark=48|dropD',
    'thursday|Thursday||genre.post_hardcore|post_hardcore,emo|2000s|dynamic,angular,dark|g=56|dropD',
    'saosin|Saosin||genre.post_hardcore|post_hardcore|2000s|clean-drive,melodic,dynamic|g=54|dropD',
    'funeral_for_a_friend|Funeral for a Friend||genre.post_hardcore|post_hardcore,emo|2000s|dynamic,melodic,tight|g=56|dropD',
    'at_the_drive_in|At the Drive-In|At the Drive In|genre.post_hardcore|post_hardcore|2000s|chaotic,angular,raw|g=58,lofi=20|eStandard',
    'the_mars_volta|The Mars Volta|Mars Volta|genre.post_hardcore|post_hardcore,progressive_rock|2000s|chaotic,fuzzy,psychedelic|g=60,fuzz=45|eStandard',
    'fugazi|Fugazi||genre.post_hardcore|post_hardcore,punk_rock|1980s,1990s|angular,dry,raw|g=48,re=6,lofi=20|eStandard',
    'refused|Refused||genre.post_hardcore|post_hardcore,punk_rock|1990s|aggressive,tight,dynamic|g=60,ti=68|dStandard',
    'thrice|Thrice||genre.post_hardcore|post_hardcore|2000s|dynamic,heavy,melodic|g=58|dropD',
    'circa_survive|Circa Survive||genre.post_hardcore|post_hardcore|2000s|dreamy,delay-driven,dynamic|g=46,de=22,re=24|eStandard',
    'coheed_and_cambria|Coheed and Cambria||genre.post_hardcore|post_hardcore,progressive_rock|2000s|melodic,dynamic,bright|g=52,tr=60|dStandard',
    'title_fight|Title Fight||genre.post_hardcore|post_hardcore,shoegaze|2010s|wide,raw,dynamic|g=52,width=60,lofi=15|eStandard',
    'american_football|American Football||genre.emo|emo|1990s|clean,twinkly,intricate|g=10,clarity=82,re=22|eStandard',
    'sunny_day_real_estate|Sunny Day Real Estate||genre.emo|emo|1990s|dynamic,emotive,raw|g=44|eStandard',
    'silverstein|Silverstein||genre.post_hardcore|post_hardcore,metalcore|2000s|tight,dynamic,melodic|g=62,ti=74|dropC,dropD',
    'alexisonfire|Alexisonfire||genre.post_hardcore|post_hardcore|2000s|raw,dynamic,melodic|g=56|dropD',
    'senses_fail|Senses Fail||genre.emo|emo,post_hardcore|2000s|energetic,tight,melodic|g=56|dropD',
    'hawthorne_heights|Hawthorne Heights||genre.emo|emo,post_hardcore|2000s|melodic,bright,tight|g=52|dropD',
    'pierce_the_veil|Pierce the Veil||genre.post_hardcore|post_hardcore,emo|2010s|bright,tight,dynamic|g=54,ti=68|dropD',
    'sleeping_with_sirens|Sleeping with Sirens||genre.post_hardcore|post_hardcore,emo|2010s|polished,bright,dynamic|g=54|dropD',
])

ROWS['ambient_postrock'] = ('Shoegaze, Post-Rock, Ambient', 'Shoegaze-, Dream-Pop-, Post-Rock- und Ambient-Gitarren-Acts.', [
    'my_bloody_valentine|My Bloody Valentine||genre.shoegaze|shoegaze|1990s|wall-of-sound,washy,pitch-bent|g=52,sa=66,mo=50,re=64,width=95|eStandard',
    'slowdive|Slowdive||genre.shoegaze|shoegaze|1990s,2010s|dreamy,washy,shimmering|g=40,mo=48,re=64,de=38|eStandard',
    'ride|Ride||genre.shoegaze|shoegaze,indie_rock|1990s|jangly,washy,driving|g=48,tr=58,mo=32|eStandard',
    'cocteau_twins|Cocteau Twins||genre.shoegaze|shoegaze,ambient|1980s|ethereal,chorused,shimmering|g=14,mo=52,re=66,de=44|eStandard',
    'lush|Lush||genre.shoegaze|shoegaze|1990s|dreamy,chorused,bright|g=36,mo=46,re=48|eStandard',
    'swervedriver|Swervedriver||genre.shoegaze|shoegaze,alternative_rock|1990s|driving,heavy,washy|g=56,re=40|eStandard',
    'deafheaven|Deafheaven||genre.shoegaze|shoegaze,black_metal|2010s|wall-of-sound,tremolo-picking,bright|g=62,sa=70,re=54,tr=64|eStandard,dStandard',
    'beach_house|Beach House||genre.shoegaze|shoegaze,ambient|2000s,2010s|dreamy,shimmering,soft|g=14,re=60,mo=38|eStandard',
    'alcest|Alcest||genre.shoegaze|shoegaze,black_metal|2000s|dreamy,bright,washy|g=48,re=54,mo=40,tr=62|dStandard',
    'diiv|DIIV||genre.shoegaze|shoegaze,indie_rock|2010s|chorused,bright,jangly|g=30,mo=52,re=36,tr=62|eStandard',
    'nothing|Nothing||genre.shoegaze|shoegaze|2010s|heavy,washy,dense|g=60,sa=68,re=50|dStandard',
    'explosions_in_the_sky|Explosions in the Sky||genre.post_rock|post_rock|2000s|swelling,dynamic,shimmering|g=32,de=46,re=52,clarity=68|eStandard',
    'mogwai|Mogwai||genre.post_rock|post_rock|1990s,2000s|dynamic,loud-quiet,fuzzy|g=48,sa=58,fuzz=35|eStandard',
    'godspeed_you_black_emperor|Godspeed You! Black Emperor|GY!BE|genre.post_rock|post_rock|1990s,2000s|drone,dark,swelling|g=44,dark=52,lofi=25|eStandard',
    'sigur_ros|Sigur Rós|Sigur Ros|genre.post_rock|post_rock,ambient|1990s,2000s|bowed,ethereal,vast|g=18,re=68,de=50,width=90|eStandard',
    'this_will_destroy_you|This Will Destroy You||genre.post_rock|post_rock,ambient|2000s|ambient,swelling,heavy|g=40,re=62,de=50|eStandard',
    'toe|toe||genre.post_rock|post_rock,fusion|2000s|clean,intricate,dynamic|g=12,clarity=82,re=28|eStandard',
    'caspian|Caspian||genre.post_rock|post_rock|2000s|epic,swelling,wide|g=44,re=54,de=44|eStandard',
    'tortoise|Tortoise||genre.post_rock|post_rock,jazz|1990s|clean,dry,intricate|g=10,clarity=80,re=18|eStandard',
    'slint|Slint||genre.post_rock|post_rock|1990s|dynamic,dry,angular|g=30,re=10,clarity=76|eStandard',
    'god_is_an_astronaut|God Is an Astronaut||genre.post_rock|post_rock|2000s|epic,delay-driven,melodic|g=36,de=48,re=54|eStandard',
    'sixtyfive_days_of_static|65daysofstatic||genre.post_rock|post_rock|2000s|electronic-tinged,dynamic,bright|g=44,de=36|eStandard',
    'mono|Mono||genre.post_rock|post_rock|2000s|orchestral,swelling,intense|g=48,re=52|eStandard',
    'do_make_say_think|Do Make Say Think||genre.post_rock|post_rock,jazz|2000s|warm,dynamic,layered|g=26,warmth=62,re=36|eStandard',
    'robert_fripp|Robert Fripp||genre.ambient_guitar|ambient,progressive_rock|1970s,1980s|soundscape,sustaining,drone|g=30,su=92,de=56|eStandard',
    'daniel_lanois|Daniel Lanois||genre.ambient_guitar|ambient,clean_pop|1980s,1990s|atmospheric,steel-tinged,warm|g=12,re=58,de=44,warmth=66|eStandard',
    'hammock|Hammock||genre.ambient_guitar|ambient,post_rock|2000s|drone,vast,soft|g=10,re=74,de=52|eStandard',
    'stars_of_the_lid|Stars of the Lid||genre.ambient_guitar|ambient|1990s|drone,slow,vast|g=8,re=78,de=56|eStandard',
    'the_edge|The Edge||genre.clean_pop|alternative_rock,clean_pop|1980s|delay-driven,rhythmic,shimmering|g=20,de=48,re=30,clarity=82|eStandard',
    'the_police|The Police|Police|genre.clean_pop|alternative_rock,post_punk|1980s|chorused,clean,sparse|g=14,mo=38,re=22,clarity=80|eStandard',
    'mac_demarco|Mac DeMarco||genre.lo_fi_guitar|lo_fi,indie_rock|2010s|wobbly,chorused,warm|g=16,mo=50,lofi=75,warmth=65|eStandard',
    'pavement|Pavement||genre.lo_fi_guitar|lo_fi,indie_rock|1990s|scrappy,jangly,lo-fi|g=40,lofi=70,tr=58|eStandard',
    'guided_by_voices|Guided by Voices||genre.lo_fi_guitar|lo_fi,indie_rock|1990s|scrappy,raw,tape|g=44,lofi=80|eStandard',
    'sebadoh|Sebadoh||genre.lo_fi_guitar|lo_fi,indie_rock|1990s|scrappy,lo-fi,raw|g=44,lofi=78|eStandard',
    'real_estate|Real Estate||genre.clean_pop|indie_rock,clean_pop|2010s|shimmering,jangly,warm|g=12,de=26,re=32,mo=20|eStandard',
    'wavves|Wavves||genre.lo_fi_guitar|lo_fi,pop_punk|2000s,2010s|fuzzy,lo-fi,noisy|g=52,lofi=72,fuzz=40|eStandard',
    'snail_mail|Snail Mail||genre.lo_fi_guitar|indie_rock,lo_fi|2010s|clean,dry,twinkly|g=14,lofi=40,re=16|eStandard',
])


def build():
    for pack, spec in ROWS.items():
        name, desc, rows = spec
        C.pack(pack, name, desc, 'STYLE_INSPIRED')
        for row in rows:
            if row:
                artist(row)
