"""Era signatures, albums and a curated song layer.

Songs are NOT generated for every artist. Only well-known titles whose character can be sensibly derived from
the artist (or album/era) are listed; a song entry is minimal and inherits everything from its parent.
Titles, albums and years are reference/search metadata only.
"""
from common import C, era_sig, album, song, entry, tone, lst, NOTE_STYLE

NAMES = {}   # artist slug -> artist name (filled by build.py from existing and new artist entries)

ERAS = [
    # artistslug|label|eraId|Suffix|parent|genres|tags|overrides
    'metallica|modern|modern|Moderne Ära||thrash_metal,heavy_metal|modern,thick,heavy|g=68,ti=76,ba=50,clarity=70',
    'megadeth|1980s|1980s|80er Thrash-Ära||thrash_metal|raw,fast,sharp|g=72,ti=84,sa=70,lofi=15',
    'megadeth|1990s|1990s|90er Ära||thrash_metal,heavy_metal|polished,tight,clear|g=66,ti=80,clarity=74',
    'slayer|1980s|1980s|80er Thrash-Ära||thrash_metal|raw,fast,aggressive|g=78,ti=84,sa=76,lofi=20',
    'iron_maiden|1980s|1980s|80er Ära||heavy_metal|melodic,twin-lead,bright,galloping|g=56,tr=60,su=68',
    'iron_maiden|modern|modern|Moderne Ära||heavy_metal,progressive_metal|modern,layered,wide|g=54,re=16,de=12,clarity=76',
    'black_sabbath|1970s|1970s|70er Ära||doom_metal,heavy_metal|vintage,warm,fuzzy,heavy|g=58,vintage=85,warmth=68,fuzz=35',
    'judas_priest|1980s|1980s|80er Ära||heavy_metal|sharp,precise,twin-lead|g=62,ti=68,pr=62',
    'in_flames|classic|1990s|Klassische Melodic-Death-Ära||melodic_death_metal|melodic,twin-lead,raw|g=66,ti=78,su=68,clarity=62',
    'in_flames|modern|modern|Moderne Ära||alternative_metal,melodic_death_metal|modern,polished,dense|g=60,ti=76,mo=8,re=14,clarity=76',
    'bring_me_the_horizon|early|2000s|Frühe Metalcore-/Deathcore-Ära||deathcore,metalcore|brutal,tight,raw|g=74,ti=88,re=6',
    'bring_me_the_horizon|modern|modern|Moderne Ära||alternative_rock,alternative_metal|modern,polished,dynamic,electronic-tinged|g=58,ti=70,re=20,de=14,mo=10',
    'opeth|early|1990s|Frühe Death-/Prog-Ära||death_metal,progressive_metal|dark,dynamic,heavy|g=68,ti=72,dark=60',
    'opeth|prog|2010s|Progressive-Rock-Ära||progressive_rock|vintage,warm,dynamic|g=36,vintage=72,warmth=70,re=22',
    'death|early|1980s|Frühe Death-Metal-Ära||death_metal|raw,brutal,fast|g=76,ti=80,lofi=20',
    'death|progressive|1990s|Progressive/Technical-Ära||technical_death_metal|technical,clear,precise|g=68,ti=88,clarity=80',
    'sepultura|1980s|1980s|Thrash-/Death-Ära||thrash_metal,death_metal|raw,fast,dirty|g=74,ti=80,sa=74,lofi=25',
    'sepultura|1990s|1990s|Groove-Ära||groove_metal|tribal,heavy,groovy|g=70,ti=76,ba=60',
    'linkin_park|hybrid|2000s|Hybrid-Ära||nu_metal,alternative_rock|modern,tight,polished|g=60,ti=72,clarity=70',
    'linkin_park|modern|modern|Moderne Ära||alternative_rock|modern,dynamic,electronic-tinged|g=44,re=18,de=12,clarity=76',
    'avenged_sevenfold|early|2000s|Frühe Metalcore-Ära||metalcore|raw,tight,aggressive|g=72,ti=84',
    'avenged_sevenfold|modern|2010s|Moderne Hard-Rock-/Metal-Ära||heavy_metal,hard_rock|polished,thick,melodic|g=58,ti=68,su=72',
    'trivium|early|2000s|Frühe Metalcore-Ära||metalcore,thrash_metal|tight,melodic,aggressive|g=72,ti=88',
    'trivium|modern|2010s|Moderne Ära||heavy_metal,metalcore|polished,thick,melodic|g=66,ti=80,su=72',
    'green_day|punk|1990s|Punk-Ära||punk_rock,pop_punk|raw,fast,bright|g=56,ti=64,tr=60',
    'green_day|rock_opera|2000s|Rock-Opern-Ära||alternative_rock,punk_rock|polished,layered,anthemic|g=50,ti=60,re=10,de=8',
    'radiohead|guitar|1990s|Gitarrenbetonte Ära||alternative_rock|dynamic,angular,fuzzy|g=54,sa=60,fuzz=30',
    'radiohead|experimental|2000s|Experimentelle Ära||alternative_rock,experimental|clean,atmospheric,sparse|g=24,re=34,de=26,mo=20',
    'muse|early|2000s|Frühe Ära||alternative_rock,progressive_rock|fuzzy,dramatic,tight|g=62,sa=68,fuzz=50,ti=64',
    'muse|modern|2010s|Moderne Ära||alternative_rock|modern,polished,synth-tinged|g=54,mo=14,de=16,clarity=74',
    'arctic_monkeys|garage|2000s|Garage-Ära||garage_rock,indie_rock|raw,fast,bright|g=52,tr=60,lofi=15',
    'arctic_monkeys|modern|2010s|Moderne Ära||alternative_rock,hard_rock|slick,heavy,riff-driven|g=54,ba=54,mi=62,re=14',
    'red_hot_chili_peppers|funk|1990s|Funk-Rock-Ära||funk,alternative_rock|funky,dry,punchy|g=30,at=74,re=8',
    'red_hot_chili_peppers|melodic|2000s|Melodische Ära||alternative_rock|clean,melodic,layered|g=24,de=14,re=18,mo=14',
    'u2|1980s|1980s|80er Ära||alternative_rock,post_punk|delay-driven,shimmering,anthemic|g=22,de=50,re=32',
    'u2|1990s|1990s|90er Ära||alternative_rock|fuzzy,electronic-tinged,dark|g=46,sa=54,mo=14',
    'acdc|1970s|1970s|70er Ära||hard_rock|raw,vintage,loose|g=50,vintage=78,lofi=15',
    'acdc|1980s|1980s|80er Ära||hard_rock|punchy,tight,polished|g=54,ti=58,co=20',
    'guns_n_roses|1980s|1980s|80er Ära||hard_rock,glam_metal|raw,gritty,bluesy|g=58,sa=60,mi=64',
    'guns_n_roses|1990s|1990s|90er Ära||hard_rock|polished,layered,thick|g=54,re=16,de=10,co=28',
    'aerosmith|1970s|1970s|70er Ära||hard_rock,blues_rock|raw,vintage,bluesy|g=52,vintage=76,lofi=15',
    'aerosmith|1980s|1980s|80er/90er Ära||hard_rock|polished,punchy,radio|g=56,co=26,tr=58',
    'rush|1970s|1970s|70er Ära||progressive_rock,hard_rock|raw,heavy,fast|g=52,ti=56,mi=64',
    'rush|1980s|1980s|80er Ära||progressive_rock|chorused,clean-crunch,precise|g=38,mo=30,clarity=82,re=14',
    'deftones|1990s|1990s|90er Ära||alternative_metal,nu_metal|heavy,raw,groovy|g=64,ti=70,ba=62',
    'deftones|2000s|2000s|2000er Ära||alternative_metal,shoegaze|dreamy,wide,dark|g=56,mo=20,re=32,de=20,width=80',
    'mastodon|early|2000s|Frühe Sludge-Ära||sludge_metal|thick,aggressive,gritty|g=68,sa=72,ti=52',
    'mastodon|modern|2010s|Moderne Ära||progressive_metal,alternative_metal|melodic,dynamic,polished|g=56,ti=62,su=68',
    'nine_inch_nails|1990s|1990s|90er Ära||industrial_metal|noisy,aggressive,dense|g=62,sa=76,lofi=35',
    'nine_inch_nails|2000s|2000s|2000er Ära||industrial_metal,alternative_rock|polished,layered,sparse|g=50,sa=62,lofi=15',
    'ozzy_osbourne|1980s|1980s|80er Ära||heavy_metal|neoclassical,sharp,melodic|g=58,ti=64,su=70',
    'ozzy_osbourne|1990s|1990s|90er Ära||heavy_metal,hard_rock|thick,modern,dark|g=62,ba=56,ti=62',
    'eric_clapton|1960s|1960s|60er Ära||blues_rock,classic_rock|woody,singing,vintage|g=46,su=76,warmth=72,vintage=85',
    'eric_clapton|1970s|1970s|70er Ära||blues_rock|clean,warm,relaxed|g=22,su=62,warmth=76',
    'pearl_jam|1990s|1990s|90er Ära||grunge|raw,dynamic,warm|g=56,sa=60,warmth=62',
    'pearl_jam|2000s|2000s|2000er Ära||alternative_rock|clean,dynamic,polished|g=40,clarity=68',
    'stevie_ray_vaughan|texas|1980s|Texas-Blues-Ära||texas_blues|fat,punchy,spring-reverb|g=46,ba=54,warmth=64',
    'paramore|pop_punk|2000s|Pop-Punk-Ära||pop_punk|bright,tight,dynamic|g=56,ti=68',
    'paramore|new_wave|2010s|New-Wave-Ära||alternative_rock,post_punk|clean,chorused,bright|g=22,mo=22,de=18,clarity=78',
]

ALBUMS = [
    # artistslug|slug|Title|year|era|parent|tags|overrides
    'metallica|ride_the_lightning|Ride the Lightning|1984|1980s|era.metallica.1980s|raw,tight|g=72,ti=84',
    'metallica|black_album|Metallica (The Black Album)|1991|1990s|era.metallica.1990s|thick,polished|g=62,ti=68,ba=52',
    'megadeth|rust_in_peace|Rust in Peace|1990|1990s|era.megadeth.1990s|technical,precise|g=68,ti=86',
    'slayer|reign_in_blood|Reign in Blood|1986|1980s|era.slayer.1980s|raw,fast,brutal|g=80,ti=86',
    'pantera|vulgar_display_of_power|Vulgar Display of Power|1992|1990s||heavy,sharp,scooped|g=74,ti=80,mi=38',
    'iron_maiden|number_of_the_beast|The Number of the Beast|1982|1980s|era.iron_maiden.1980s|galloping,melodic|g=58',
    'judas_priest|british_steel|British Steel|1980|1980s|era.judas_priest.1980s|sharp,direct|g=62,ti=66',
    'black_sabbath|paranoid|Paranoid|1970|1970s|era.black_sabbath.1970s|heavy,vintage|g=58',
    'nirvana|nevermind|Nevermind|1991|1990s||polished-raw,dynamic|g=58,ti=44,co=30',
    'pearl_jam|ten|Ten|1991|1990s|era.pearl_jam.1990s|warm,dynamic|g=52,warmth=66',
    'soundgarden|superunknown|Superunknown|1994|1990s||heavy,dark,dense|g=62,ba=58,dark=55',
    'alice_in_chains|dirt|Dirt|1992|1990s||dark,heavy,harmonized|g=60,ti=48,dark=62',
    'radiohead|ok_computer|OK Computer|1997|1990s|era.radiohead.guitar|dynamic,layered|g=48,re=24',
    'green_day|dookie|Dookie|1994|1990s|era.green_day.punk|bright,fast|g=56,tr=60',
    'blink_182|enema_of_the_state|Enema of the State|1999|1990s||polished,bright,tight|g=52,ti=68,tr=60',
    'def_leppard|hysteria|Hysteria|1987|1980s||layered,polished|g=52,ti=66,co=36',
    'guns_n_roses|appetite_for_destruction|Appetite for Destruction|1987|1980s|era.guns_n_roses.1980s|raw,gritty|g=60',
    'acdc|back_in_black|Back in Black|1980|1980s|era.acdc.1980s|punchy,tight|g=54',
    'led_zeppelin|led_zeppelin_iv|Led Zeppelin IV|1971|1970s||vintage,warm,dynamic|g=42,vintage=85',
    'pink_floyd|dark_side_of_the_moon|The Dark Side of the Moon|1973|1970s||spacious,warm,clean|g=24,de=26,re=32',
    'queen|a_night_at_the_opera|A Night at the Opera|1975|1970s||layered,singing|g=50,su=80',
    'stevie_ray_vaughan|texas_flood|Texas Flood|1983|1980s|era.stevie_ray_vaughan.texas|fat,punchy|g=44',
    'dire_straits|brothers_in_arms|Brothers in Arms|1985|1980s||clean,polished,articulate|g=18,clarity=84',
    'opeth|blackwater_park|Blackwater Park|2001|2000s|era.opeth.early|dynamic,dark|g=64,dark=58',
    'in_flames|the_jester_race|The Jester Race|1996|1990s|era.in_flames.classic|melodic,raw|g=66',
    'in_flames|clayman|Clayman|2000|2000s|era.in_flames.classic|melodic,tight|g=64,ti=80',
    'children_of_bodom|hatebreeder|Hatebreeder|1999|1990s|artist.cob|neoclassical,fast|g=64,su=72',
    'slipknot|iowa|Iowa|2001|2000s||brutal,heavy,downtuned|g=76,ti=76,ba=60',
    'korn|korn_debut|Korn|1994|1990s||downtuned,low,rhythmic|g=62,ba=68',
    'deftones|white_pony|White Pony|2000|2000s|era.deftones.2000s|dreamy,heavy|g=54,re=30',
    'system_of_a_down|toxicity|Toxicity|2001|2000s||dynamic,tight,punchy|g=60,ti=70',
    'rammstein|mutter|Mutter|2001|2000s||mechanical,tight|g=62,ti=84',
    'gojira|from_mars_to_sirius|From Mars to Sirius|2005|2000s||heavy,tight,pick-scrape|g=70,ti=78',
    'meshuggah|destroy_erase_improve|Destroy Erase Improve|1995|1990s||polyrhythmic,tight,heavy|g=72,ti=90',
    'trivium|ascendancy|Ascendancy|2005|2000s|era.trivium.early|melodic,tight|g=72,ti=88',
    'killswitch_engage|the_end_of_heartache|The End of Heartache|2004|2000s||melodic,tight|g=70,ti=86',
    'bring_me_the_horizon|sempiternal|Sempiternal|2013|2010s|era.bring_me_the_horizon.modern|polished,dynamic|g=60,re=16',
    'muse|origin_of_symmetry|Origin of Symmetry|2001|2000s|era.muse.early|fuzzy,dramatic|g=64,fuzz=52',
    'arctic_monkeys|am|AM|2013|2010s|era.arctic_monkeys.modern|slick,heavy|g=54',
    'red_hot_chili_peppers|blood_sugar_sex_magik|Blood Sugar Sex Magik|1991|1990s|era.red_hot_chili_peppers.funk|funky,dry|g=30',
    'foo_fighters|the_colour_and_the_shape|The Colour and the Shape|1997|1990s||dynamic,thick,direct|g=58,ti=56',
    'queens_of_the_stone_age|songs_for_the_deaf|Songs for the Deaf|2002|2000s||fuzzy,heavy,groovy|g=58,fuzz=40',
    'my_bloody_valentine|loveless|Loveless|1991|1990s||wall-of-sound,washy|g=52,re=66,mo=52',
    'slowdive|souvlaki|Souvlaki|1993|1990s||dreamy,shimmering|g=38,re=64,mo=48',
    'explosions_in_the_sky|the_earth_is_not_a_cold_dead_place|The Earth Is Not a Cold Dead Place|2003|2000s||swelling,dynamic|g=32,de=48,re=54',
    'mogwai|young_team|Mogwai Young Team|1997|1990s||dynamic,loud-quiet|g=48',
    'dream_theater|images_and_words|Images and Words|1992|1990s||virtuosic,clear|g=56,su=76',
]

# artistslug -> [(slug, Title, parent album/era id or '', aliases)]
SONGS = {
    'metallica': [('enter_sandman', 'Enter Sandman', 'album.metallica.black_album', ''), ('fade_to_black', 'Fade to Black', 'album.metallica.ride_the_lightning', ''),
                  ('battery', 'Battery', 'album.metallica.master_of_puppets', ''), ('one', 'One', '', '')],
    'megadeth': [('holy_wars', 'Holy Wars... The Punishment Due', 'album.megadeth.rust_in_peace', 'Holy Wars'), ('hangar_18', 'Hangar 18', 'album.megadeth.rust_in_peace', ''),
                 ('symphony_of_destruction', 'Symphony of Destruction', '', '')],
    'slayer': [('raining_blood', 'Raining Blood', 'album.slayer.reign_in_blood', ''), ('angel_of_death', 'Angel of Death', 'album.slayer.reign_in_blood', ''),
               ('south_of_heaven', 'South of Heaven', '', '')],
    'anthrax': [('caught_in_a_mosh', 'Caught in a Mosh', '', ''), ('indians', 'Indians', '', '')],
    'testament': [('the_new_order', 'The New Order', '', '')],
    'kreator': [('pleasure_to_kill', 'Pleasure to Kill', '', '')],
    'sepultura': [('roots_bloody_roots', 'Roots Bloody Roots', 'era.sepultura.1990s', ''), ('refuse_resist', 'Refuse/Resist', 'era.sepultura.1990s', 'Refuse Resist')],
    'pantera': [('walk', 'Walk', 'album.pantera.vulgar_display_of_power', ''), ('cowboys_from_hell', 'Cowboys from Hell', '', ''), ('cemetery_gates', 'Cemetery Gates', '', '')],
    'lamb_of_god': [('redneck', 'Redneck', '', ''), ('laid_to_rest', 'Laid to Rest', '', '')],
    'gojira': [('flying_whales', 'Flying Whales', 'album.gojira.from_mars_to_sirius', ''), ('stranded', 'Stranded', '', '')],
    'meshuggah': [('bleed', 'Bleed', '', ''), ('future_breed_machine', 'Future Breed Machine', '', '')],
    'tool': [('schism', 'Schism', '', ''), ('sober', 'Sober', '', ''), ('forty_six_and_2', 'Forty Six & 2', '', 'Forty Six and 2')],
    'dream_theater': [('pull_me_under', 'Pull Me Under', 'album.dream_theater.images_and_words', ''), ('metropolis', 'Metropolis Pt. 1: The Miracle and the Sleeper', '', 'Metropolis')],
    'opeth': [('blackwater_park', 'Blackwater Park', 'album.opeth.blackwater_park', ''), ('ghost_of_perdition', 'Ghost of Perdition', '', '')],
    'mastodon': [('blood_and_thunder', 'Blood and Thunder', 'era.mastodon.early', '')],
    'black_sabbath': [('paranoid', 'Paranoid', 'album.black_sabbath.paranoid', ''), ('iron_man', 'Iron Man', 'album.black_sabbath.paranoid', ''), ('war_pigs', 'War Pigs', 'album.black_sabbath.paranoid', '')],
    'ozzy_osbourne': [('crazy_train', 'Crazy Train', 'era.ozzy_osbourne.1980s', ''), ('mr_crowley', 'Mr. Crowley', 'era.ozzy_osbourne.1980s', 'Mr Crowley'), ('no_more_tears', 'No More Tears', 'era.ozzy_osbourne.1990s', '')],
    'dio': [('holy_diver', 'Holy Diver', '', ''), ('rainbow_in_the_dark', 'Rainbow in the Dark', '', '')],
    'iron_maiden': [('the_trooper', 'The Trooper', 'era.iron_maiden.1980s', ''), ('run_to_the_hills', 'Run to the Hills', 'album.iron_maiden.number_of_the_beast', ''),
                    ('hallowed_be_thy_name', 'Hallowed Be Thy Name', 'album.iron_maiden.number_of_the_beast', ''), ('fear_of_the_dark', 'Fear of the Dark', '', '')],
    'judas_priest': [('breaking_the_law', 'Breaking the Law', 'album.judas_priest.british_steel', ''), ('painkiller', 'Painkiller', '', '')],
    'accept': [('balls_to_the_wall', 'Balls to the Wall', '', '')],
    'motorhead': [('ace_of_spades', 'Ace of Spades', '', ''), ('overkill', 'Overkill', '', '')],
    'manowar': [('kings_of_metal', 'Kings of Metal', '', '')],
    'helloween': [('eagle_fly_free', 'Eagle Fly Free', '', ''), ('i_want_out', 'I Want Out', '', '')],
    'blind_guardian': [('valhalla', 'Valhalla', '', '')],
    'hammerfall': [('hearts_on_fire', 'Hearts on Fire', '', '')],
    'sabaton': [('primo_victoria', 'Primo Victoria', '', '')],
    'nightwish': [('nemo', 'Nemo', '', ''), ('ghost_love_score', 'Ghost Love Score', '', '')],
    'within_temptation': [('mother_earth', 'Mother Earth', '', '')],
    'children_of_bodom': [('hate_me', 'Hate Me!', 'album.children_of_bodom.hatebreeder', 'Hate Me'), ('everytime_i_die', 'Everytime I Die', '', ''), ('in_your_face', 'In Your Face', '', ''), ('are_you_dead_yet', 'Are You Dead Yet?', '', '')],
    'in_flames': [('only_for_the_weak', 'Only for the Weak', 'album.in_flames.clayman', ''), ('cloud_connected', 'Cloud Connected', 'era.in_flames.classic', '')],
    'at_the_gates': [('slaughter_of_the_soul', 'Slaughter of the Soul', '', '')],
    'arch_enemy': [('nemesis', 'Nemesis', '', ''), ('we_will_rise', 'We Will Rise', '', '')],
    'amon_amarth': [('twilight_of_the_thunder_god', 'Twilight of the Thunder God', '', '')],
    'soilwork': [('stabbing_the_drama', 'Stabbing the Drama', '', '')],
    'death': [('crystal_mountain', 'Crystal Mountain', 'era.death.progressive', '')],
    'cannibal_corpse': [('hammer_smashed_face', 'Hammer Smashed Face', '', '')],
    'morbid_angel': [('chapel_of_ghouls', 'Chapel of Ghouls', '', '')],
    'obituary': [('slowly_we_rot', 'Slowly We Rot', '', '')],
    'carcass': [('heartwork', 'Heartwork', '', '')],
    'behemoth': [('conquer_all', 'Conquer All', '', '')],
    'mayhem': [('freezing_moon', 'Freezing Moon', '', '')],
    'immortal': [('sons_of_northern_darkness', 'Sons of Northern Darkness', '', '')],
    'dimmu_borgir': [('progenies_of_the_great_apocalypse', 'Progenies of the Great Apocalypse', '', '')],
    'electric_wizard': [('dopethrone', 'Dopethrone', '', '')],
    'sleep': [('dopesmoker', 'Dopesmoker', '', '')],
    'kyuss': [('green_machine', 'Green Machine', '', '')],
    'down': [('stone_the_crow', 'Stone the Crow', '', '')],
    'slipknot': [('duality', 'Duality', '', ''), ('wait_and_bleed', 'Wait and Bleed', '', ''), ('psychosocial', 'Psychosocial', '', '')],
    'korn': [('freak_on_a_leash', 'Freak on a Leash', '', ''), ('blind', 'Blind', 'album.korn.korn_debut', '')],
    'system_of_a_down': [('chop_suey', 'Chop Suey!', 'album.system_of_a_down.toxicity', 'Chop Suey'), ('toxicity', 'Toxicity', 'album.system_of_a_down.toxicity', ''), ('byob', 'B.Y.O.B.', '', 'BYOB')],
    'deftones': [('my_own_summer', 'My Own Summer (Shove It)', 'era.deftones.1990s', 'My Own Summer'), ('change', 'Change (In the House of Flies)', 'album.deftones.white_pony', 'Change')],
    'linkin_park': [('in_the_end', 'In the End', 'era.linkin_park.hybrid', ''), ('numb', 'Numb', '', ''), ('one_step_closer', 'One Step Closer', 'era.linkin_park.hybrid', '')],
    'rammstein': [('du_hast', 'Du Hast', '', ''), ('sonne', 'Sonne', 'album.rammstein.mutter', '')],
    'fear_factory': [('replica', 'Replica', '', '')],
    'static_x': [('push_it', 'Push It', '', '')],
    'disturbed': [('down_with_the_sickness', 'Down with the Sickness', '', '')],
    'avenged_sevenfold': [('bat_country', 'Bat Country', '', ''), ('nightmare', 'Nightmare', '', '')],
    'trivium': [('pull_harder_on_the_strings_of_your_martyr', 'Pull Harder on the Strings of Your Martyr', 'album.trivium.ascendancy', ''), ('strife', 'Strife', '', '')],
    'killswitch_engage': [('my_curse', 'My Curse', '', ''), ('the_end_of_heartache', 'The End of Heartache', 'album.killswitch_engage.the_end_of_heartache', '')],
    'as_i_lay_dying': [('nothing_left', 'Nothing Left', '', '')],
    'parkway_drive': [('carrion', 'Carrion', '', ''), ('wild_eyes', 'Wild Eyes', '', '')],
    'architects': [('doomsday', 'Doomsday', '', '')],
    'bring_me_the_horizon': [('shadow_moses', 'Shadow Moses', 'album.bring_me_the_horizon.sempiternal', ''), ('can_you_feel_my_heart', 'Can You Feel My Heart', 'album.bring_me_the_horizon.sempiternal', ''), ('throne', 'Throne', 'era.bring_me_the_horizon.modern', '')],
    'august_burns_red': [('marianas_trench', 'Marianas Trench', '', '')],
    'periphery': [('icarus_lives', 'Icarus Lives!', '', 'Icarus Lives')],
    'spiritbox': [('holy_roller', 'Holy Roller', '', '')],
    'lorna_shore': [('to_the_hellfire', 'To the Hellfire', '', '')],
    'acdc': [('back_in_black', 'Back in Black', 'album.acdc.back_in_black', ''), ('thunderstruck', 'Thunderstruck', 'era.acdc.1980s', ''), ('highway_to_hell', 'Highway to Hell', 'era.acdc.1970s', '')],
    'led_zeppelin': [('black_dog', 'Black Dog', 'album.led_zeppelin.led_zeppelin_iv', ''), ('stairway_to_heaven', 'Stairway to Heaven', 'album.led_zeppelin.led_zeppelin_iv', ''), ('whole_lotta_love', 'Whole Lotta Love', '', '')],
    'deep_purple': [('smoke_on_the_water', 'Smoke on the Water', '', ''), ('highway_star', 'Highway Star', '', '')],
    'queen': [('bohemian_rhapsody', 'Bohemian Rhapsody', 'album.queen.a_night_at_the_opera', ''), ('we_will_rock_you', 'We Will Rock You', '', '')],
    'pink_floyd': [('money', 'Money', 'album.pink_floyd.dark_side_of_the_moon', ''), ('comfortably_numb', 'Comfortably Numb', '', '')],
    'the_who': [('baba_oriley', "Baba O'Riley", '', 'Baba ORiley')],
    'the_rolling_stones': [('satisfaction', "(I Can't Get No) Satisfaction", '', 'Satisfaction')],
    'jimi_hendrix': [('purple_haze', 'Purple Haze', '', ''), ('voodoo_child', 'Voodoo Child (Slight Return)', '', 'Voodoo Child')],
    'cream': [('sunshine_of_your_love', 'Sunshine of Your Love', '', '')],
    'eric_clapton': [('layla', 'Layla', '', ''), ('cocaine', 'Cocaine', 'era.eric_clapton.1970s', '')],
    'dire_straits': [('sultans_of_swing', 'Sultans of Swing', '', ''), ('money_for_nothing', 'Money for Nothing', 'album.dire_straits.brothers_in_arms', '')],
    'zz_top': [('la_grange', 'La Grange', '', ''), ('sharp_dressed_man', 'Sharp Dressed Man', '', '')],
    'aerosmith': [('sweet_emotion', 'Sweet Emotion', 'era.aerosmith.1970s', ''), ('walk_this_way', 'Walk This Way', 'era.aerosmith.1970s', '')],
    'guns_n_roses': [('sweet_child_o_mine', "Sweet Child o' Mine", 'album.guns_n_roses.appetite_for_destruction', 'Sweet Child of Mine'), ('welcome_to_the_jungle', 'Welcome to the Jungle', 'album.guns_n_roses.appetite_for_destruction', ''),
                     ('november_rain', 'November Rain', 'era.guns_n_roses.1990s', '')],
    'van_halen': [('eruption', 'Eruption', '', ''), ('panama', 'Panama', '', '')],
    'bon_jovi': [('livin_on_a_prayer', "Livin' on a Prayer", '', 'Livin on a Prayer')],
    'def_leppard': [('pour_some_sugar_on_me', 'Pour Some Sugar on Me', 'album.def_leppard.hysteria', '')],
    'motley_crue': [('kickstart_my_heart', 'Kickstart My Heart', '', '')],
    'whitesnake': [('here_i_go_again', 'Here I Go Again', '', '')],
    'scorpions': [('rock_you_like_a_hurricane', 'Rock You Like a Hurricane', '', '')],
    'europe': [('the_final_countdown', 'The Final Countdown', '', '')],
    'journey': [('dont_stop_believin', "Don't Stop Believin'", '', 'Dont Stop Believin')],
    'boston': [('more_than_a_feeling', 'More Than a Feeling', '', '')],
    'rush': [('tom_sawyer', 'Tom Sawyer', 'era.rush.1980s', ''), ('yyz', 'YYZ', 'era.rush.1980s', '')],
    'yes': [('roundabout', 'Roundabout', '', '')],
    'king_crimson': [('twenty_first_century_schizoid_man', '21st Century Schizoid Man', '', 'Twenty First Century Schizoid Man')],
    'porcupine_tree': [('trains', 'Trains', '', '')],
    'nirvana': [('smells_like_teen_spirit', 'Smells Like Teen Spirit', 'album.nirvana.nevermind', ''), ('lithium', 'Lithium', 'album.nirvana.nevermind', '')],
    'alice_in_chains': [('rooster', 'Rooster', 'album.alice_in_chains.dirt', ''), ('would', 'Would?', 'album.alice_in_chains.dirt', 'Would')],
    'soundgarden': [('black_hole_sun', 'Black Hole Sun', 'album.soundgarden.superunknown', ''), ('spoonman', 'Spoonman', 'album.soundgarden.superunknown', '')],
    'pearl_jam': [('alive', 'Alive', 'album.pearl_jam.ten', ''), ('jeremy', 'Jeremy', 'album.pearl_jam.ten', '')],
    'stone_temple_pilots': [('plush', 'Plush', '', '')],
    'foo_fighters': [('everlong', 'Everlong', 'album.foo_fighters.the_colour_and_the_shape', ''), ('monkey_wrench', 'Monkey Wrench', 'album.foo_fighters.the_colour_and_the_shape', '')],
    'queens_of_the_stone_age': [('no_one_knows', 'No One Knows', 'album.queens_of_the_stone_age.songs_for_the_deaf', '')],
    'muse': [('plug_in_baby', 'Plug In Baby', 'album.muse.origin_of_symmetry', ''), ('knights_of_cydonia', 'Knights of Cydonia', '', ''), ('hysteria', 'Hysteria', 'era.muse.early', '')],
    'radiohead': [('creep', 'Creep', 'era.radiohead.guitar', ''), ('paranoid_android', 'Paranoid Android', 'album.radiohead.ok_computer', '')],
    'arctic_monkeys': [('do_i_wanna_know', 'Do I Wanna Know?', 'album.arctic_monkeys.am', 'Do I Wanna Know'), ('r_u_mine', 'R U Mine?', 'album.arctic_monkeys.am', 'R U Mine')],
    'the_strokes': [('last_nite', 'Last Nite', '', '')],
    'the_white_stripes': [('seven_nation_army', 'Seven Nation Army', '', '')],
    'smashing_pumpkins': [('cherub_rock', 'Cherub Rock', '', ''), ('today', 'Today', '', '')],
    'red_hot_chili_peppers': [('under_the_bridge', 'Under the Bridge', 'album.red_hot_chili_peppers.blood_sugar_sex_magik', ''), ('give_it_away', 'Give It Away', 'album.red_hot_chili_peppers.blood_sugar_sex_magik', ''),
                              ('scar_tissue', 'Scar Tissue', 'era.red_hot_chili_peppers.melodic', '')],
    'rage_against_the_machine': [('killing_in_the_name', 'Killing in the Name', '', ''), ('bulls_on_parade', 'Bulls on Parade', '', '')],
    'audioslave': [('cochise', 'Cochise', '', '')],
    'green_day': [('basket_case', 'Basket Case', 'album.green_day.dookie', ''), ('american_idiot', 'American Idiot', 'era.green_day.rock_opera', '')],
    'blink_182': [('all_the_small_things', 'All the Small Things', 'album.blink_182.enema_of_the_state', '')],
    'sum_41': [('fat_lip', 'Fat Lip', '', '')],
    'the_offspring': [('come_out_and_play', 'Come Out and Play', '', '')],
    'rise_against': [('savior', 'Savior', '', '')],
    'my_chemical_romance': [('welcome_to_the_black_parade', 'Welcome to the Black Parade', '', '')],
    'paramore': [('misery_business', 'Misery Business', 'era.paramore.pop_punk', '')],
    'ramones': [('blitzkrieg_bop', 'Blitzkrieg Bop', '', '')],
    'sex_pistols': [('anarchy_in_the_uk', 'Anarchy in the U.K.', '', 'Anarchy in the UK')],
    'the_clash': [('london_calling', 'London Calling', '', '')],
    'the_cure': [('just_like_heaven', 'Just Like Heaven', '', '')],
    'my_bloody_valentine': [('only_shallow', 'Only Shallow', 'album.my_bloody_valentine.loveless', '')],
    'slowdive': [('alison', 'Alison', 'album.slowdive.souvlaki', '')],
    'explosions_in_the_sky': [('first_breath_after_coma', 'First Breath After Coma', 'album.explosions_in_the_sky.the_earth_is_not_a_cold_dead_place', '')],
    'mogwai': [('mogwai_fear_satan', 'Mogwai Fear Satan', 'album.mogwai.young_team', '')],
    'bb_king': [('the_thrill_is_gone', 'The Thrill Is Gone', '', '')],
    'stevie_ray_vaughan': [('pride_and_joy', 'Pride and Joy', 'album.stevie_ray_vaughan.texas_flood', ''), ('texas_flood', 'Texas Flood', 'album.stevie_ray_vaughan.texas_flood', '')],
    'gary_moore': [('still_got_the_blues', 'Still Got the Blues', '', '')],
    'john_mayer': [('gravity', 'Gravity', '', '')],
    'prince': [('purple_rain', 'Purple Rain', '', '')],
    'nile_rodgers': [('le_freak', 'Le Freak', '', '')],
    'johnny_cash': [('ring_of_fire', 'Ring of Fire', '', ''), ('folsom_prison_blues', 'Folsom Prison Blues', '', '')],
    'chet_atkins': [('mr_sandman', 'Mr. Sandman', '', 'Mr Sandman')],
    'wes_montgomery': [('four_on_six', 'Four on Six', '', '')],
    'george_benson': [('breezin', "Breezin'", '', 'Breezin')],
    'pat_metheny': [('are_you_going_with_me', 'Are You Going with Me?', '', 'Are You Going with Me')],
    'joe_satriani': [('surfing_with_the_alien', 'Surfing with the Alien', '', '')],
    'steve_vai': [('for_the_love_of_god', 'For the Love of God', '', '')],
    'eric_johnson': [('cliffs_of_dover', 'Cliffs of Dover', '', '')],
    'dick_dale': [('misirlou', 'Misirlou', '', '')],
    'the_ventures': [('walk_dont_run', "Walk, Don't Run", '', 'Walk Dont Run')],
    'stray_cats': [('stray_cat_strut', 'Stray Cat Strut', '', '')],
    'yngwie_malmsteen': [('far_beyond_the_sun', 'Far Beyond the Sun', '', '')],
}


def build_eras():
    for row in ERAS:
        slug, label, era, suffix, parent, genres, tags, ov = [x.strip() for x in row.split('|')]
        name = NAMES[slug]
        era_sig('|'.join([slug, label, era, name, suffix, parent, genres, tags, ov, '', '']))


SLUG_ALIAS = {'children_of_bodom': 'cob'}   # ids of the first seed use children_of_bodom, the artist entry is artist.cob


def build_albums():
    for row in ALBUMS:
        f = [x.strip() for x in row.split('|')]
        aslug, key, title, year, era, parent, tags, ov = f
        real = SLUG_ALIAS.get(aslug, aslug)
        album('|'.join([aslug, key, NAMES[real], title, year, era, parent or 'artist.' + real, tags, ov]))


def build_songs():
    for aslug, items in SONGS.items():
        real = SLUG_ALIAS.get(aslug, aslug)
        name = NAMES[real]
        for key, title, parent, aliases in items:
            song('|'.join([aslug, key, name, title, aliases, parent or 'artist.' + real, '', '', '', '', '']), conf='LOW')
