// Generates the golden hex of every ANGELS_DONT_KILL_P01_V1 message from the
// Dart plan (catalog-resolved models, closed encoder) into the Kotlin test
// fixture. Never hand-transcribed:
//   dart run tool/generate_angels_kotlin_fixture.dart
import 'dart:convert';
import 'dart:io';

import 'package:wyrmtone/presets/canonical_preset.dart';
import 'package:wyrmtone/presets/device_catalog.dart';
import 'package:wyrmtone/presets/matribox_angels_product_plan.dart';
import 'package:wyrmtone/presets/matribox_model_library.dart';

void main() {
  final catalog = DevicePresetCatalog(
    objectMap(jsonDecode(File('assets/catalog/matribox_preset_catalog.json').readAsStringSync())),
  );
  final plan = AngelsProductPlan(library: MatriboxModelLibrary.fromVendor(catalog));
  final buffer = StringBuffer()
    ..writeln('package de.neevel.wyrmtone')
    ..writeln()
    ..writeln('// GENERATED by tool/generate_angels_kotlin_fixture.dart from the Dart plan. Do not edit.')
    ..writeln('object MatriboxAngelsGolden {')
    ..writeln('    val messages: List<String> = listOf(');
  for (final op in plan.operations) {
    final hex = op.bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join(' ');
    buffer.writeln('        "$hex", // ${op.slot.label} ${op.label}');
  }
  buffer
    ..writeln('    )')
    ..writeln('}');
  File('android/app/src/test/kotlin/de/neevel/wyrmtone/MatriboxAngelsGolden.kt').writeAsStringSync(buffer.toString());
  stdout.writeln('written ${plan.operations.length} messages');
}
