// Renders the NATIVE manufacturer table (MatriboxManufacturerCatalog.kt) and the
// reach statistics from ONE source: the normalized manufacturer catalog
// (assets/catalog/matribox_preset_catalog.json, generated from algorithm.xml)
// plus the productive evidence decisions (Evidence V2 over the product ledger).
//
// The native side therefore never re-derives a rule: it receives, per model and
// parameter, the decision (`selectable` / `writable` + reason) and the
// hardware-confirmed wire index (manufacturer ID - 1). A test regenerates this
// text and compares it with the checked-in Kotlin file (staleness guard).
import 'package:wyrmtone/presets/device_catalog.dart';
import 'package:wyrmtone/presets/matribox_chain_catalog.dart';
import 'package:wyrmtone/presets/matribox_chain_slot.dart';
import 'package:wyrmtone/presets/matribox_evidence_v2.dart';
import 'package:wyrmtone/presets/matribox_hardware_evidence.dart';
import 'package:wyrmtone/presets/matribox_model_library.dart';
import 'package:wyrmtone/presets/matribox_transfer_catalog.dart';

const nativeCatalogPath = 'android/app/src/main/kotlin/de/neevel/wyrmtone/MatriboxManufacturerCatalog.kt';

String _kind(MatriboxChainParameter p) => switch (p.kind) {
  MatriboxParameterKind.number => 'N',
  MatriboxParameterKind.signedNumber => 'S',
  MatriboxParameterKind.decimal => 'D',
  MatriboxParameterKind.flag => 'F',
};

String _num(double v) => v == v.roundToDouble() ? v.toStringAsFixed(0) : '$v';

final _forbidden = RegExp(r'[|"\\$\n\r]');

String _clean(String text) {
  if (_forbidden.hasMatch(text)) {
    throw StateError('Zeichen in "$text" sind im nativen Tabellenformat nicht erlaubt.');
  }
  return text;
}

String _reason(String? basis) => basis == null ? '-' : _clean(basis.split(':').first.trim());

/// The decisions of the PRODUCTIVE evidence (product ledger) for every catalog model/parameter.
class NativeDecisions {
  NativeDecisions(this.library, this.evidence);
  final MatriboxModelLibrary library;
  final MatriboxEvidenceV2 evidence;

  factory NativeDecisions.product(DevicePresetCatalog catalog) {
    final library = MatriboxModelLibrary.fromVendor(catalog);
    return NativeDecisions(
      library,
      MatriboxEvidenceV2(library: library, samples: ActiveSamples.fromLedger(MatriboxHardwareLedger.product(), library)),
    );
  }

  EvidenceDecision select(MatriboxChainSlot slot, MatriboxTransferModel m) => evidence.modelSelect(slot, m);

  EvidenceDecision write(MatriboxChainSlot slot, MatriboxTransferModel m, MatriboxChainParameter p) =>
      evidence.parameter(slot, m, p, p.kind == MatriboxParameterKind.flag ? 0 : p.minimum);
}

String renderNativeManufacturerCatalog(DevicePresetCatalog catalog) {
  final decisions = NativeDecisions.product(catalog);
  final out = StringBuffer()
    ..writeln('package de.neevel.wyrmtone')
    ..writeln()
    ..writeln('// GENERATED by tool/generate_native_manufacturer_catalog.dart from')
    ..writeln('// assets/catalog/matribox_preset_catalog.json (manufacturer algorithm.xml) and the')
    ..writeln('// productive Evidence V2 decisions. Do not edit; a Dart test fails when it is stale.')
    ..writeln('//')
    ..writeln('// Line format (raw strings per slot):')
    ..writeln('//   M|name|code|selectable(1/0)|blockedBy')
    ..writeln('//   P|name|wireIndex(=manufacturer ID - 1)|manufacturerId|kind(N,S,D,F)|min|max|step|writable(1/0)|blockedBy')
    ..writeln('internal object MatriboxManufacturerData {');
  for (final slot in MatriboxChainSlot.values) {
    out.writeln('    const val ${slot.name.toUpperCase()} = """');
    for (final m in decisions.library.forSlot(slot)) {
      final d = decisions.select(slot, m);
      out.writeln('M|${_clean(m.name)}|${m.code}|${d.sendable ? 1 : 0}|${d.sendable ? '-' : _reason(d.basis)}');
      for (final p in m.algorithm.parameters) {
        final w = decisions.write(slot, m, p);
        out.writeln(
          'P|${_clean(p.name)}|${p.wireIndex}|${p.xmlId ?? -1}|${_kind(p)}|${_num(p.minimum)}|${_num(p.maximum)}|'
          '${p.step == null ? '-' : _num(p.step!)}|${w.sendable ? 1 : 0}|${w.sendable ? '-' : _reason(w.basis)}',
        );
      }
    }
    out.writeln('"""');
  }
  out.writeln('}');
  return out.toString();
}

class ReachReport {
  ReachReport(this.lines, this.numbers);
  final List<String> lines;
  final Map<String, int> numbers;
}

/// Reach over the manufacturer catalog, in three separate classes:
/// A technically addressable, B productively released (FAMILY/EXACT), C semantically mapped.
ReachReport computeReach(DevicePresetCatalog catalog, Map<MatriboxChainSlot, Set<String>> semanticallyMapped) {
  final d = NativeDecisions.product(catalog);
  final n = <String, int>{
    'algorithms': catalog.algorithms.length,
    'parameters': catalog.algorithms.fold(0, (a, e) => a + e.parameters.length),
  };
  var algBlank = 0, algSelectableA = 0, algSelectableB = 0;
  final algBlockReasons = <String, int>{};
  var pBlank = 0, pInvalidId = 0, pAddressable = 0, pReleased = 0, pReleasedEnd = 0, pOther = 0;
  var pMapped = 0, pMappedReleased = 0;
  final pReasons = <String, int>{};
  const categorySlots = {
    'FX1': MatriboxChainSlot.fx1,
    'FX2': MatriboxChainSlot.fx2,
    'AMP': MatriboxChainSlot.amp,
    'NR': MatriboxChainSlot.nr,
    'CAB': MatriboxChainSlot.cab,
    'EQ': MatriboxChainSlot.eq,
    'MOD': MatriboxChainSlot.mod,
    'DLY': MatriboxChainSlot.dly,
    'RVB': MatriboxChainSlot.rvb,
  };
  for (final a in catalog.algorithms) {
    final slot = categorySlots[a.category]!;
    final blank = (a.name ?? '').isEmpty;
    if (blank) {
      algBlank++;
      algBlockReasons['USER_IR_BLOCKED (leerer Name)'] = (algBlockReasons['USER_IR_BLOCKED (leerer Name)'] ?? 0) + 1;
      pBlank += a.parameters.length;
      continue;
    }
    final model = d.library.byCode(slot, a.code!);
    algSelectableA++;
    final sel = model == null ? null : d.select(slot, model);
    final selectable = sel?.sendable ?? false;
    if (selectable) {
      algSelectableB++;
    } else {
      final key = sel == null ? 'UNBEKANNT' : sel.basis.split(':').first;
      algBlockReasons[key] = (algBlockReasons[key] ?? 0) + 1;
    }
    for (final cp in a.parameters) {
      final p = model?.algorithm.parameters.where((x) => x.name == cp.name).firstOrNull;
      if (p == null) {
        pOther++;
        continue;
      }
      final invalid = p.blockedReason != null;
      if (invalid) {
        pInvalidId++;
      } else {
        pAddressable++;
      }
      final w = invalid ? null : d.write(slot, model!, p);
      final mapped = semanticallyMapped[slot]?.contains(p.name) ?? false;
      if (mapped) pMapped++;
      if (w != null && w.sendable) {
        pReleased++;
        if (selectable) pReleasedEnd++;
        if (mapped) pMappedReleased++;
      } else {
        final reason = invalid
            ? 'ADDRESS_BLOCKED'
            : (w!.level == EvidenceLevel.blocked ? w.basis.split(':').first : 'KEIN_AKTIVER_SAMPLE (${p.kind.name}, Slot ${slot.label})');
        pReasons[reason] = (pReasons[reason] ?? 0) + 1;
      }
    }
  }
  n['algorithmsUserIrBlocked'] = algBlank;
  n['algorithmsTechnicallySelectable'] = algSelectableA;
  n['algorithmsReleased'] = algSelectableB;
  n['parametersInUserIr'] = pBlank;
  n['parametersAddressable'] = pAddressable;
  n['parametersInvalidId'] = pInvalidId;
  n['parametersReleased'] = pReleased;
  n['parametersReleasedEndToEnd'] = pReleasedEnd;
  n['parametersOther'] = pOther;
  n['parametersSemanticallyMapped'] = pMapped;
  n['parametersSemanticallyMappedAndReleased'] = pMappedReleased;
  final sortedReasons = pReasons.entries.toList()..sort((x, y) => y.value.compareTo(x.value));
  final lines = [
    'Algorithmen gesamt: ${n['algorithms']} · Parameter gesamt: ${n['parameters']}',
    'A technisch adressierbar: Algorithmen $algSelectableA (User IR gesperrt: $algBlank), Parameter $pAddressable '
        '(davon in User IR: $pBlank, ungültige/fehlende ID: $pInvalidId, sonstige: $pOther)',
    'B produktiv FAMILY/EXACT: Algorithmen $algSelectableB, Parameter $pReleased (Ende-zu-Ende mit wählbarem Modell: $pReleasedEnd)',
    'B gesperrt nach Grund (Parameter, ohne User IR): ${sortedReasons.map((e) => '${e.key} ${e.value}').join(', ')}',
    'B gesperrt nach Grund (Algorithmen): ${algBlockReasons.entries.map((e) => '${e.key} ${e.value}').join(', ')}',
    'C semantisch abgebildet (Parameter, für den der Tone-Translator im passenden Block eine nicht-heuristische Mapping-Regel hat): $pMapped, davon produktiv freigegeben: $pMappedReleased',
  ];
  return ReachReport(lines, n);
}
