
import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'evaluation_signal.dart';
import 'runtime_signal_wav.dart';

/// A signal that ships inside the app: the exact PCM the validated pipeline feeds to the NAM engine.
/// Its cache identity stays that of the validated signal (`CanonicalSignal`: SHA-256 of the ORIGINAL
/// recording + `wyrmtone-<role>-v1#T15`), so moving the signal into the app invalidates no cache entry.
class RuntimeSignalSpec {
  const RuntimeSignalSpec({
    required this.role,
    required this.asset,
    required this.sampleCount,
    required this.pcmSha256,
  });
  final EvaluationRole role;
  final String asset;

  /// Mono Float32 samples at [evaluationSampleRate].
  final int sampleCount;

  /// SHA-256 of the little-endian Float32 PCM (not of the container file).
  final String pcmSha256;
}

/// Only what the product flow needs: rhythm and lead targets use the 15 s derivation ("T15") of our own
/// dry DI recordings; clean targets use the full clean recording (about 14 s). Generated by
/// `tool/tonematch_runtime/generate_runtime_signals.dart` from the research recordings, which are NOT
/// app assets. Provenance: own guitar DI takes, no song recordings, no third-party material.
abstract final class ToneMatchRuntimeSignals {
  static const all = <RuntimeSignalSpec>[
    RuntimeSignalSpec(
      role: EvaluationRole.rhythm,
      asset: 'assets/tonematch/runtime/wyrmtone-rhythm-v1-t15.wav',
      sampleCount: 744000,
      pcmSha256:
          '6a592f7af0f594bacad4369cb966ee9317e23d010c32e808f0606678299803a5',
    ),
    RuntimeSignalSpec(
      role: EvaluationRole.lead,
      asset: 'assets/tonematch/runtime/wyrmtone-lead-v1-t15.wav',
      sampleCount: 744000,
      pcmSha256:
          'c21ae35c2045bfe2511e635122860648c55acc06bcd36a71fde2c6e320ff1a7d',
    ),
    RuntimeSignalSpec(
      role: EvaluationRole.clean,
      asset: 'assets/tonematch/runtime/wyrmtone-clean-v1-full.wav',
      sampleCount: 685259,
      pcmSha256:
          '8b43e2550d4c424ccbfdf7f8291714e45f36b5e3e1e80aae673644ddf60a7fa0',
    ),
  ];

  static RuntimeSignalSpec spec(EvaluationRole role) =>
      all.firstWhere((s) => s.role == role);
}

/// Loads the signals bundled with the app and verifies them. A missing or damaged signal yields null
/// (the technical reason is only logged): Tone Match then falls back to the description pre-selection.
class BundledToneMatchSignalProvider {
  BundledToneMatchSignalProvider({
    Future<ByteData> Function(String asset)? load,
    void Function(String)? log,
  }) : _load = load ?? rootBundle.load,
       _log = log ?? ((m) => debugPrint('ToneMatch: $m'));
  final Future<ByteData> Function(String asset) _load;
  final void Function(String) _log;
  final _cache = <EvaluationRole, Future<Float32List?>>{};

  Future<Float32List?> samplesFor(EvaluationRole role) =>
      _cache.putIfAbsent(role, () => _read(ToneMatchRuntimeSignals.spec(role)));

  Future<Float32List?> _read(RuntimeSignalSpec spec) async {
    try {
      final data = await _load(spec.asset);
      final samples = RuntimeSignalWav.decode(
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
      );
      if (samples == null || samples.length != spec.sampleCount) {
        _log('signal ${spec.role.name}: unexpected container');
        return null;
      }
      final hash = sha256
          .convert(
            samples.buffer.asUint8List(
              samples.offsetInBytes,
              samples.lengthInBytes,
            ),
          )
          .toString();
      if (hash != spec.pcmSha256) {
        _log('signal ${spec.role.name}: content hash mismatch');
        return null;
      }
      return samples;
    } on Object catch (e) {
      _log('signal ${spec.role.name}: $e');
      return null;
    }
  }
}
