/// Golden corpus for the offline NAM → CloData converter (metadata only).
///
/// A model becomes a GOLDEN reference only when the official Sonicake editor
/// produced both the model output (`HTCache\nam_output_wav.wav`) and the
/// CloData that was sent to the device (reconstructed from a USB capture).
/// Large artifacts stay in the external local capture directory; this file
/// only records where they are, their SHA-256 and their provenance. Nothing
/// here is generated by our own code.
library;

import 'dart:typed_data';

import 'nam_transfer_analysis.dart';
import 'usb_capture_reader.dart';

/// Validation state of a corpus case as recorded by the maintainer. The
/// authoritative result is always the comparison run against the local files.
enum MatriboxGoldenStatus { golden, needsOfficialOutput }

class MatriboxGoldenCase {
  const MatriboxGoldenCase({
    required this.id,
    required this.displayName,
    required this.storedName,
    required this.namSha256,
    required this.outputWav,
    required this.outputWavSha256,
    required this.clodataSha256,
    required this.provenance,
    this.officialClodata,
    this.capture,
    this.captureSha256,
    this.namLocalPath,
    this.referenceWav = 'v3/48000.wav',
    this.referenceWavSha256 =
        'a8da7250698124b564c3d526773dec40269f309d58e88af5ee43670ba4c3cf33',
  });

  final String id;
  final String displayName;

  /// File name handed to the converter (the editor derives the name field
  /// from it).
  final String storedName;
  final String namSha256;

  /// Paths relative to the external capture directory.
  final String referenceWav;
  final String referenceWavSha256;
  final String outputWav;
  final String outputWavSha256;

  /// Official CloData: either an already reconstructed file
  /// ([officialClodata]) or, preferred, the USBPcap [capture] it is
  /// reconstructed from with the V2 parser (source of truth).
  final String? officialClodata;
  final String? capture;
  final String? captureSha256;
  final String clodataSha256;

  /// Location of the imported `.nam` according to the editor log, if it
  /// still exists locally (SHA-256 is checked when present).
  final String? namLocalPath;
  final String provenance;
}

/// External, local, non-repository directory holding the captures.
const matriboxCaptureRoot = 'D:/Develop/wyrmtone-captures';

const matriboxGoldenCorpus = <MatriboxGoldenCase>[
  MatriboxGoldenCase(
    id: 'solid-rhythm-mid-hi',
    displayName: 'Solid Rhythm (Mid Hi)',
    storedName: 'Solid Ryhthm Mid Hi.nam',
    namSha256:
        'ba495fb8c15c00f2a3a268e74f00f49aa7fa06b75d1bde6ec8dc945f38353f24',
    namLocalPath: 'D:/Desktop 3d sachen/Desktop/Solid Ryhthm Mid Hi.nam',
    outputWav: 'v3/nam_output_wav.wav',
    outputWavSha256:
        '1328c1e1ef1c495cdd8db0ea6da9d833598272650990c719f668d429ff2df7b8',
    officialClodata: 'v2/c_clodata.bin',
    clodataSha256:
        'a3fffddfc155a3b5a6f9fd2e56e67a7a0aa01210ed497c022ad4e7a95bd79414',
    provenance:
        'Editor run 2026-09-25 (HTCache copy, output peak 0.307453 in the '
        'editor log); CloData from USB capture C.',
  ),
  MatriboxGoldenCase(
    id: 'gojira-joe-duplantier',
    displayName: 'GOJIRA - JOE DUPLANTIER',
    storedName: 'GOJIRA - JOE DUPLANTIER.nam',
    namSha256:
        '7d70a61abe0c74c280906de2a57882a6f6e988b462f513e06f41882703b82b85',
    namLocalPath: 'D:/Desktop 3d sachen/Desktop/Gojira (Joe Duplantier)/GOJIRA - JOE DUPLANTIER.nam',
    outputWav: 'v3/gojira_nam_output_wav.wav',
    outputWavSha256:
        'a3fd44e4209af0fb7196b2b7c55369243b85f631ab3e6104fdbd06514bb3b0eb',
    officialClodata: 'v2/a_clodata.bin',
    clodataSha256:
        'c3a44e9282b679130104c14d2f97e690e6e3172b7efa0a4b1d47615de19c35b1',
    provenance:
        'HTCache copy of the editor run 2026-09-25 23:59:45 (log: GOJIRA, '
        'output peak 0.252853); CloData from USB captures A and B (identical).',
  ),
  MatriboxGoldenCase(
    id: 'jvm410h-standard',
    displayName: 'Marshall JVM410H Boosted - Full Rig (Standard)',
    storedName: 'Marshall JVM410H Boosted - Full Rig (Standard).nam',
    // The file the editor log names (SlimmableContainer 0.7.0, 294,105 B). A
    // different file of the same name (WaveNet 0.5.4, 283,360 B, SHA-256
    // ed1cca50...) lives under "AMP Presets" and was NOT imported.
    namSha256:
        '8e2c468813e0332d4c0907b2dd3ec120bdc863ac1778b7ddb7f34ed32f0ef859',
    namLocalPath: 'D:/Desktop 3d sachen/Desktop/Marshall JVM410H - 100 Watt Head Boosted/Marshall JVM410H Boosted - Full Rig (Standard).nam',
    outputWav: 'v4/jvm410h_standard/nam_output_wav.wav',
    outputWavSha256:
        '6ccde156e87f0b557379c9dd34878bc119326d6e839c7f8f4c594dd7342a92c8',
    capture: 'v4/jvm410h_standard/transfer.pcapng',
    captureSha256:
        'b986c73680a07e754aa762f20e2ea7983cf9a1343e831ac50dad6a8a212cd945',
    clodataSha256:
        '3613a1aac5f03bcfe69e48fe5af6817c52f8207e8ea88c003a85fe2582eb64e8',
    provenance:
        'Editor run 2026-09-26 23:31:55 (log names the NAM path, output peak '
        '0.224781); HTCache copy 23:32:02; USBPcap capture ends 23:32:32, '
        'transfer 4.5 s before its end.',
  ),
  MatriboxGoldenCase(
    id: 'fender-super-reverb-akg414',
    displayName: 'Fender Super Reverb - EQ Flat, Volume 3, AKG 414',
    storedName: 'Fender Super Reverb_ EQ Flat, Volume 3, AKG 414.nam',
    // IMPORTANT: the editor log names a THIRD file of this name, directly
    // under Desktop (SlimmableContainer 0.7.0, 298,052 B, gain 0.0297) -
    // neither of the two files previously found under "AMP Presets" (the
    // WaveNet 0.5.4 copy, 283,481 B, assumed in V3d, nor the identically
    // named WaveNet copy of the JVM case's kind). That earlier assumption
    // was wrong; this is the file actually imported.
    namSha256:
        'e31984c8e40ed9e07907cada8f933ac26dc90c62ad7621070fa1f42421d44f3c',
    namLocalPath: 'D:/Desktop 3d sachen/Desktop/Fender Super Reverb_ EQ Flat, Volume 3, AKG 414.nam',
    outputWav: 'v4/fender_super_reverb_akg414/nam_output_wav.wav',
    outputWavSha256:
        '0440646121f7d87c43a4ccbe89767a08e7c5e6e1df420d5a8061e88d94372b52',
    capture: 'v4/fender_super_reverb_akg414/transfer.pcapng',
    captureSha256:
        '3a0112f5993bd027ec195a610100abf83c4c1701855677a2d01cde0b8da2c0c2',
    clodataSha256:
        'd41fbafa29973c2d824eb10fb9191651fc5f797108808a643f2c7ed0073366cd',
    provenance:
        'Editor run 2026-09-27 09:40:36 (log names the Desktop-root NAM path, '
        'output peak 0.234904, measured 0.234894); HTCache copy 09:40:43; '
        'USBPcap capture ends 09:41:29, block transfer 12.3...5.9 s before '
        'its end (after the WAV was already written).',
  ),
  MatriboxGoldenCase(
    id: 'fndr-pano-wavenet-054',
    displayName: 'FNDR PANO Clean2 BAL 6V6 CAB (WaveNet 0.5.4, Tanh)',
    storedName: 'FNDR PANO Clean2 BAL 6V6 CAB.nam',
    // First golden with a genuinely different upstream NAM architecture:
    // plain WaveNet 0.5.4 (Tanh, 2 layer arrays 16/8 ch, 13,802 weights), not
    // SlimmableContainer 0.7.0/WaveNet 0.7.0/LeakyReLU like all four earlier
    // cases. Verified independently against the file, not merely assumed.
    namSha256:
        'ee7a370810b71cdad793c31093d4db9f680c9e0c00ef82785de267e129006bdb',
    namLocalPath: 'D:/Desktop 3d sachen/Desktop/AMP Presets/Fender Pano-Verb/FNDR PANO Clean2 BAL 6V6 CAB.nam',
    outputWav: 'v4/fndr_pano_wavenet_054/nam_output_wav.wav',
    outputWavSha256:
        '4dbbe85f5dfeba0cff9189f6b8aab0d2ffa3dc3abaf82dd918a25ef869be8cc7',
    // Note the source file is spelled "tranfer.pcapng" (missing the "s"),
    // not "transfer.pcapng" like the other three capture-based cases.
    capture: 'v4/fndr_pano_wavenet_054/tranfer.pcapng',
    captureSha256:
        'af05533c803e5ab210e6cb2543d7506f7093905a7213062ad62b18125b0d9707',
    clodataSha256:
        '9dbb8d52fd57a2c7341e63db2d15ed2b214f165ade3394a7c2a683d0f716da87',
    provenance:
        'Editor run 2026-09-27 19:24:07 (log names the NAM path, output peak '
        '0.195617, measured 0.195618); HTCache copy 19:24:12; USBPcap '
        'capture ends 19:25:00, block transfer 10.96...4.4 s before its end '
        '(after the WAV was already written). Same logfile.txt also holds '
        'an earlier, unrelated Fender Super Reverb run from that morning.',
  ),
];

/// Candidates without official evidence. They are NOT goldens.
class MatriboxGoldenCandidate {
  const MatriboxGoldenCandidate(
    this.displayName,
    this.relativePath,
    this.namSha256,
    this.characteristics, {
    this.primary = false,
  });

  final String displayName;

  /// Relative to the local NAM library (`D:/Desktop 3d sachen/Desktop`).
  final String relativePath;
  final String namSha256;
  final String characteristics;

  /// V3d primary reference (diverse clean / high-gain evidence wanted).
  final bool primary;
}

// Expected evidence layout of a pending V3d reference, relative to
// [matriboxCaptureRoot]: `v4/<id>/nam_output_wav.wav` and `logfile.txt` (both
// copied from `C:\ProgramData\HTCache` right after the import) plus the
// USBPcap capture `v4/<id>/transfer.pcapng` of the same transfer. The CloData
// is reconstructed from the capture with `analyze-transfer`.

const matriboxGoldenCandidates = <MatriboxGoldenCandidate>[
  // The two other "AKG 414" copies found under "AMP Presets" and directly on
  // Desktop are WaveNet 0.5.4/Tanh, NOT SlimmableContainer 0.7.0 - genuinely
  // different from all four current goldens (which are all SlimmableContainer
  // WaveNet-0.7.0/LeakyReLU). Still useful, still NOT imported.
  MatriboxGoldenCandidate(
    'Fender Super Reverb - EQ Flat, Volume 3, AKG 414 (WaveNet 0.5.4 copy, AMP Presets)',
    'AMP Presets/Fender Super Reverb 1977/Fender Super Reverb_ EQ Flat, Volume 3, AKG 414.nam',
    '88a26b540df878a01500071cfa81415c2d6b97a5621a124445a3fb87d9627364',
    'clean / low gain (0.02), WaveNet 0.5.4 Tanh, 2 layer arrays, 283 KB; '
        'different model from the SlimmableContainer file actually imported '
        'for the golden of the same display name',
    primary: true,
  ),
  MatriboxGoldenCandidate(
    'Fender Super Reverb - EQ Flat, Volume 3, sm57 and AKG 414',
    'AMP Presets/Fender Super Reverb 1977/Fender Super Reverb_ EQ Flat, Volume 3, sm57 and AKG 414.nam',
    'c5206d0ff28092647d8a662bdcedb99e643cd4a128931d922e56d61f50b31382',
    'clean / low gain (0.02), WaveNet 0.5.4, same architecture as the AKG 414 '
        'WaveNet copy above',
  ),
  MatriboxGoldenCandidate(
    'Fender Super Reverb - EQ Flat, Volume 3, sm57',
    'AMP Presets/Fender Super Reverb 1977/Fender Super Reverb_ EQ Flat, Volume 3, sm57.nam',
    '4c782d9f662f1087b96de5cb133de66171f6fc559fd514e19741b2361543db40',
    'clean / low gain (0.03), WaveNet 0.5.4, same architecture as the AKG 414 '
        'WaveNet copy above',
  ),
  MatriboxGoldenCandidate(
    'Marshall JVM410H Boosted - Full Rig (Custom_High Accuracy)',
    'AMP Presets/Marshall JVM410H - 100 Watt Head Boosted (Full Rig_Head)/Marshall JVM410H Boosted - Full Rig (Custom_High Accuracy).nam',
    'ef0860d98d86211713e97a31523062f5b92a8a3f46f1df21ee170ee99503a7cb',
    'WaveNet 0.5.4 Tanh, 3 layer arrays 16/8/8 with large kernels, 505 KB; '
        'NOT imported so far (V3d evidence is the Standard file)',
  ),
  MatriboxGoldenCandidate(
    'Marshall JVM410H Boosted - Full Rig (Standard), WaveNet copy under AMP Presets',
    'AMP Presets/Marshall JVM410H - 100 Watt Head Boosted (Full Rig_Head)/Marshall JVM410H Boosted - Full Rig (Standard).nam',
    'ed1cca5091baa6bb7945814fd5107382a5ca4a56948b7328d057878c7061ec3b',
    'WaveNet 0.5.4 Tanh, 2 layer arrays 16/8, 283 KB; same file name as the '
        'imported Slimmable file but a different model, NOT imported',
  ),
  MatriboxGoldenCandidate(
    'Marshall JVM410H Boosted (Lite)',
    'AMP Presets/Marshall JVM410H - 100 Watt Head Boosted (Full Rig_Head)/Marshall JVM410H Boosted - Full Rig (Lite).nam',
    '5f4f8bc23ef63fe012c3a5d44010d7334aab9b4f7dd578a22cde7f9715261300',
    'smallest architecture (12/6 channels), 134 KB',
  ),
  MatriboxGoldenCandidate(
    'Boogie Mark V Lead',
    'AMP Presets/Boogie Mark V - Rhythm, Lead and Clean/Lead.nam',
    'c18221463e72a56caaf78859dcb683ed63fa8b06cddffd7fa09400c427ed5a83',
    'high gain, WaveNet 0.5.0 without metadata, 408 KB',
  ),
  MatriboxGoldenCandidate(
    'Bugera 6262 1 Hit Quitter',
    'AMP Presets/Bugera 6262 1 Hit Quitter.nam',
    '5317db991837474c45a76a36e56768e20eb3ca95ad3c39efb3018feac017f807',
    'high gain (0.83), WaveNet 0.5.2, 296 KB',
  ),
  MatriboxGoldenCandidate(
    'Solid Rhythm Fat',
    'Solid Rhythm Fat.nam',
    'cbb597343dfdc75c3dd0621c7987e5fefe8ccc58cd5deceb76290fd687aa82c4',
    'SlimmableContainer 0.7.0 like both goldens, quieter (loudness -21.3)',
  ),
];

/// Byte comparison of two CloData buffers.
class MatriboxCloDataDiff {
  MatriboxCloDataDiff(List<int> expected, List<int> actual)
    : expectedLength = expected.length,
      actualLength = actual.length {
    final common = expected.length < actual.length
        ? expected.length
        : actual.length;
    var run = -1;
    for (var i = 0; i < common; i++) {
      if (expected[i] == actual[i]) {
        matching++;
        run = -1;
        continue;
      }
      differing++;
      firstDifference ??= i;
      if (run >= 0 && regions.last.end == i) {
        regions.last = (start: regions.last.start, end: i + 1);
      } else {
        regions.add((start: i, end: i + 1));
      }
      run = i;
    }
  }

  final int expectedLength;
  final int actualLength;
  int matching = 0;
  int differing = 0;
  int? firstDifference;

  /// Contiguous differing regions, `[start, end)`.
  final List<({int start, int end})> regions = [];

  bool get identical =>
      expectedLength == actualLength && differing == 0 && matching > 0;

  @override
  String toString() =>
      'size $actualLength/$expectedLength, matching $matching, differing '
      '$differing in ${regions.length} region(s), first difference '
      '${firstDifference == null ? '-' : '0x${firstDifference!.toRadixString(16)}'}';
}

/// Reconstructs the official CloData from a USBPcap capture with the
/// validated V2 parser (independent of the converter).
Uint8List matriboxCloDataFromCapture(Uint8List pcapng) {
  final analysis = analyzeCloneTransfers({'X': readUsbCapture(pcapng)});
  final clo = analysis.artifacts['x_clodata.bin'];
  if (clo == null) {
    throw const FormatException('Capture does not contain a complete CloData.');
  }
  return clo;
}
