package de.neevel.wyrmtone

// GENERATED by tool/generate_native_manufacturer_catalog.dart from
// assets/catalog/matribox_preset_catalog.json (manufacturer algorithm.xml) and the
// productive Evidence V2 decisions. Do not edit; a Dart test fails when it is stale.
//
// Line format (raw strings per slot):
//   M|name|code|selectable(1/0)|blockedBy
//   P|name|wireIndex(=manufacturer ID - 1)|manufacturerId|kind(N,S,D,F)|min|max|step|writable(1/0)|blockedBy
internal object MatriboxManufacturerData {
    const val FX1 = """
M|Skreamer|50331648|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Blues OD|50331657|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|COMP|0|1|-
P|Sustain|0|1|N|0|99|-|1|-
P|Output|1|2|N|0|99|-|1|-
M|COMP2|1|1|-
P|Sustain|0|1|N|0|99|-|1|-
P|Attack|1|2|N|0|99|-|1|-
P|Output|2|3|N|0|99|-|1|-
P|Clip|3|4|N|0|99|-|1|-
M|AC Sim|16777217|1|-
P|Body|0|1|N|0|99|-|1|-
P|Top|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
P|Mode|3|4|N|0|99|-|0|ENUM_UNCONFIRMED
M|Touch-W|16777231|1|-
P|Sense|0|1|N|0|99|-|1|-
P|Range|1|2|N|0|99|-|1|-
P|Q|2|3|N|0|99|-|1|-
P|Mix|3|4|N|0|99|-|1|-
P|Mode|4|5|N|0|99|-|0|ENUM_UNCONFIRMED
M|Auto-W|16777237|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|VOL|2|3|N|0|99|-|1|-
P|Low|3|4|N|0|99|-|1|-
P|Q|4|5|N|0|99|-|1|-
P|High|5|6|N|0|99|-|1|-
P|Sync|6|7|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|UK-W|83886081|1|-
P|Range|0|1|N|0|99|-|1|-
P|Q|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Cry-W|83886088|1|-
P|Range|0|1|N|0|99|-|1|-
P|Q|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Octaver|16777249|1|-
P|L-OCT|0|1|N|0|99|-|1|-
P|H-OCT|1|2|N|0|99|-|1|-
P|Dry|2|3|N|0|99|-|1|-
M|Dual Melody|16777251|1|-
P|H-Pitch|0|1|N|0|24|-|1|-
P|L-Pitch|1|2|S|-24|0|-|0|Nur Vendor-Katalog (Index, Bereich).
P|Dry|2|3|N|0|99|-|1|-
P|H-VOL|3|4|N|0|99|-|1|-
P|L-VOL|4|5|N|0|99|-|1|-
M|Pitch|16777252|1|-
P|H-Pitch|0|1|N|0|12|-|1|-
P|L-Pitch|1|2|S|-12|0|-|0|Nur Vendor-Katalog (Index, Bereich).
P|Wet|2|3|N|0|99|-|1|-
P|Dry|3|4|N|0|99|-|1|-
P|Range|4|5|N|0|99|-|1|-
M|Tape Mod|16777267|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Mix|1|2|N|0|99|-|1|-
P|Output|-1|3|N|0|99|-|0|ADDRESS_BLOCKED
P|H-Cut|3|4|N|0|99|-|1|-
M|Ring Mod|16777263|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Freq|1|2|N|0|99|-|1|-
P|Fine|2|3|S|-50|50|-|0|Nur Vendor-Katalog (Index, Bereich).
P|Tone|3|4|N|0|99|-|1|-
M|Filter|16777241|1|-
P|Step 1|0|1|N|0|99|-|1|-
P|Step 2|1|2|N|0|99|-|1|-
P|Step 3|2|3|N|0|99|-|1|-
P|Step 4|3|4|N|0|99|-|1|-
P|Rate|4|5|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|Sync|5|6|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Boost|26|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Bright|2|3|F|0|99|-|1|-
M|Butter OD|50331650|1|-
P|Gain|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Super OD|50331654|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Dist Plus|50331711|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
P|Mode|3|4|N|0|99|-|0|ENUM_UNCONFIRMED
P|Blend|4|5|N|0|99|-|1|-
M|JP Dist|50331690|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Shark|50331696|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Dark Mouse|50331691|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Filter|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Fuzz Cream|50331682|1|-
P|Sustain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Red Fuzz|50331684|1|-
P|Fuzz|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Bass Dist|50331712|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Blend|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
"""
    const val FX2 = """
M|Skreamer|50331648|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Blues OD|50331657|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|COMP|0|1|-
P|Sustain|0|1|N|0|99|-|1|-
P|Output|1|2|N|0|99|-|1|-
M|COMP2|1|1|-
P|Sustain|0|1|N|0|99|-|1|-
P|Attack|1|2|N|0|99|-|1|-
P|Output|2|3|N|0|99|-|1|-
P|Clip|3|4|N|0|99|-|1|-
M|AC Sim|16777217|1|-
P|Body|0|1|N|0|99|-|1|-
P|Top|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
P|Mode|3|4|N|0|99|-|0|ENUM_UNCONFIRMED
M|Touch-W|16777231|1|-
P|Sense|0|1|N|0|99|-|1|-
P|Range|1|2|N|0|99|-|1|-
P|Q|2|3|N|0|99|-|1|-
P|Mix|3|4|N|0|99|-|1|-
P|Mode|4|5|N|0|99|-|0|ENUM_UNCONFIRMED
M|Auto-W|16777237|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|VOL|2|3|N|0|99|-|1|-
P|Low|3|4|N|0|99|-|1|-
P|Q|4|5|N|0|99|-|1|-
P|High|5|6|N|0|99|-|1|-
P|Sync|6|7|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|UK-W|83886081|1|-
P|Range|0|1|N|0|99|-|1|-
P|Q|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Cry-W|83886088|1|-
P|Range|0|1|N|0|99|-|1|-
P|Q|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Octaver|16777249|1|-
P|L-OCT|0|1|N|0|99|-|1|-
P|H-OCT|1|2|N|0|99|-|1|-
P|Dry|2|3|N|0|99|-|1|-
M|Dual Melody|16777251|1|-
P|H-Pitch|0|1|N|0|24|-|1|-
P|L-Pitch|1|2|S|-24|0|-|0|Nur Vendor-Katalog (Index, Bereich).
P|Dry|2|3|N|0|99|-|1|-
P|H-VOL|3|4|N|0|99|-|1|-
P|L-VOL|4|5|N|0|99|-|1|-
M|Pitch|16777252|1|-
P|H-Pitch|0|1|N|0|12|-|1|-
P|L-Pitch|1|2|S|-12|0|-|0|Nur Vendor-Katalog (Index, Bereich).
P|Wet|2|3|N|0|99|-|1|-
P|Dry|3|4|N|0|99|-|1|-
P|Range|4|5|N|0|99|-|1|-
M|Tape Mod|16777267|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Mix|1|2|N|0|99|-|1|-
P|Output|-1|3|N|0|99|-|0|ADDRESS_BLOCKED
P|H-Cut|3|4|N|0|99|-|1|-
M|Ring Mod|16777263|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Freq|1|2|N|0|99|-|1|-
P|Fine|2|3|S|-50|50|-|0|Nur Vendor-Katalog (Index, Bereich).
P|Tone|3|4|N|0|99|-|1|-
M|Filter|16777241|1|-
P|Step 1|0|1|N|0|99|-|1|-
P|Step 2|1|2|N|0|99|-|1|-
P|Step 3|2|3|N|0|99|-|1|-
P|Step 4|3|4|N|0|99|-|1|-
P|Rate|4|5|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|Sync|5|6|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Boost|26|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Bright|2|3|F|0|99|-|1|-
M|Butter OD|50331650|1|-
P|Gain|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Super OD|50331654|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Dist Plus|50331711|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
P|Mode|3|4|N|0|99|-|0|ENUM_UNCONFIRMED
P|Blend|4|5|N|0|99|-|1|-
M|JP Dist|50331690|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Shark|50331696|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Dark Mouse|50331691|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Filter|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Fuzz Cream|50331682|1|-
P|Sustain|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
M|Red Fuzz|50331684|1|-
P|Fuzz|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Bass Dist|50331712|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Blend|1|2|N|0|99|-|1|-
P|VOL|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
"""
    const val AMP = """
M|Brit 800|117440565|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Sol 100 OD|117440583|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Sol 100 LD|117440601|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|TWD Deluxe|117440513|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|Output|2|3|N|0|99|-|1|-
M|B-Man N|117440515|1|-
P|VOL|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Output|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Dark Double|117440516|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Output|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
P|Bright|5|6|F|0|99|-|1|-
M|Calif Star CL|117440537|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Voks 30N|117440529|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Cut|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bright|3|4|F|0|99|-|1|-
M|Bog SV CL|117440538|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
P|Bright|5|6|F|0|99|-|1|-
M|Jazz 120|117440532|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Bass|1|2|N|0|99|-|1|-
P|Middle|2|3|N|0|99|-|1|-
P|Treble|3|4|N|0|99|-|1|-
P|Bright|4|5|F|0|99|-|1|-
M|Superb CL|117440533|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Doctor CL|117440539|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Cut|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Brit 45|117440554|1|-
P|VOL|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Output|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Brit 50JP|117440559|1|-
P|VOL 1|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Output|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
P|VOL 2|6|7|N|0|99|-|1|-
M|Flyman B1|117440576|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Doctor OD|117440585|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Cut|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Bog SV OD|117440573|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|B-Man B|117440548|1|-
P|VOL|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Output|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Voks 30TB|117440551|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Cut|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
P|Char|5|6|N|0|99|-|0|ENUM_UNCONFIRMED
M|Supero 2|117440552|1|-
P|VOL  1|0|1|N|0|99|-|1|-
P|Tone 1|1|2|N|0|99|-|1|-
P|VOL  2|2|3|N|0|99|-|1|-
P|Tone 2|3|4|N|0|99|-|1|-
P|Output|4|5|N|0|99|-|1|-
M|Superb OD|117440584|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Calif Star OD|117440586|1|-
P|Gain|1|2|N|0|99|-|1|-
P|PRES|2|3|N|0|99|-|1|-
P|Master|3|4|N|0|99|-|1|-
P|Bass|4|5|N|0|99|-|1|-
P|Middle|5|6|N|0|99|-|1|-
P|Treble|6|7|N|0|99|-|1|-
M|Calif IIC+|117440569|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Dizzy VH|117440613|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Eng 120|117440607|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Halen 51|117440602|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Master|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
P|PRES|6|7|N|0|99|-|1|-
M|Calif IV|117440597|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Calif DualV|117440616|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Calif DualM|117440617|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Dragon LD|117440611|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Flyman B1+|117440605|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Tanger R100|117440595|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Master|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
M|Bog XT Blue|117440621|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|Bog XT Red|117440622|1|-
P|Gain|0|1|N|0|99|-|1|-
P|PRES|1|2|N|0|99|-|1|-
P|Master|2|3|N|0|99|-|1|-
P|Bass|3|4|N|0|99|-|1|-
P|Middle|4|5|N|0|99|-|1|-
P|Treble|5|6|N|0|99|-|1|-
M|A BassVT|117440627|1|-
P|Gain|0|1|N|0|99|-|1|-
P|Bass|1|2|N|0|99|-|1|-
P|Middle|2|3|N|0|99|-|1|-
P|MRange|3|4|N|0|99|-|0|ENUM_UNCONFIRMED
P|Treble|4|5|N|0|99|-|1|-
P|Master|5|6|N|0|99|-|1|-
M|A BassFT|134217845|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Bass|1|2|N|0|99|-|1|-
P|Treble|2|3|N|0|99|-|1|-
M|F-2Bass|134217846|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Bright|1|2|F|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
M|Voks Bass|117440629|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Bass|1|2|N|0|99|-|1|-
P|Treble|2|3|N|0|99|-|1|-
M|Calif Bass|117440631|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Master|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
M|AC Preamp|134217850|1|-
P|VOL|0|1|N|0|99|-|1|-
P|Tone|1|2|N|0|99|-|1|-
P|Balance|2|3|N|0|99|-|1|-
P|EQ Freq|3|4|N|0|99|-|1|-
P|EQ Q|4|5|N|0|99|-|1|-
P|EQ Gain|5|6|N|0|99|-|1|-
M|Clone 1|251658240|1|-
P|Gain|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
M|Clone 2|251658241|1|-
P|Gain|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
M|Clone 3|251658242|1|-
P|Gain|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
M|Clone 4|251658243|1|-
P|Gain|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
M|Clone 5|251658244|1|-
P|Gain|0|1|N|0|99|-|1|-
P|VOL|1|2|N|0|99|-|1|-
P|Bass|2|3|N|0|99|-|1|-
P|Middle|3|4|N|0|99|-|1|-
P|Treble|4|5|N|0|99|-|1|-
"""
    const val NR = """
M|Gate 1|27|1|-
P|THRE|0|1|N|0|99|-|1|-
M|Gate 2|29|1|-
P|THRE|0|1|N|0|99|-|1|-
P|ATK|1|2|N|0|99|-|1|-
P|Rel|2|3|N|0|99|-|1|-
"""
    const val CAB = """
M|BritGN 4x12|167772194|1|-
P|VOL|1|2|N|0|99|-|1|-
M|User IR 7|168820742|0|USER_IR_BLOCKED
P|VOL|1|2|N|0|99|-|0|USER_IR_BLOCKED
M|Supero 1x6|167772160|1|-
P|VOL|1|2|N|0|99|-|1|-
M|TWD 1x8|167772161|1|-
P|VOL|1|2|N|0|99|-|1|-
M|TWD-P 1x10|167772162|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Bog SV 1x12|167772166|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Viblux 1x12|167772164|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Voks 1x12|167772168|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Calif 1x12|167772172|1|-
P|VOL|1|2|N|0|99|-|1|-
M|TWD 2x12|167772187|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Double 2x12|167772178|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Star 2x12|167772185|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Rock 2x12|167772188|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Jazz 2x12|167772177|1|-
P|VOL|1|2|N|0|99|-|1|-
M|BritGN 2x12|167772179|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Free 2x12|167772186|1|-
P|VOL|1|2|N|0|99|-|1|-
M|B-Man 4x10|167772190|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Brit75 4x12|167772208|1|-
P|VOL|1|2|N|0|99|-|1|-
M|BritLD 4x12|167772191|1|-
P|VOL|1|2|N|0|99|-|1|-
M|BritDK 4x12|167772203|1|-
P|VOL|1|2|N|0|99|-|1|-
M|BritMD 4x12|167772193|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Bog 4x12|167772199|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Dizzy 4x12|167772206|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Eng 4x12|167772198|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Halen 4x12|167772192|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Sol 4x12|167772200|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Calif 4x12|167772209|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Dual 4x12|167772196|1|-
P|VOL|1|2|N|0|99|-|1|-
M|WAM 4x12|167772204|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Tanger 4x12|167772201|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Watt 4x12|167772202|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Calif 2x10|167772213|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Work 4x10|167772217|1|-
P|VOL|1|2|N|0|99|-|1|-
M|A Bass 4x10|167772216|1|-
P|VOL|1|2|N|0|99|-|1|-
M|A Bass 8x10|167772219|1|-
P|VOL|1|2|N|0|99|-|1|-
M|D|167772220|1|-
P|VOL|1|2|N|0|99|-|1|-
M|OM|167772222|1|-
P|VOL|1|2|N|0|99|-|1|-
M|Jumbo|167772223|1|-
P|VOL|1|2|N|0|99|-|1|-
M|GA|167772225|1|-
P|VOL|1|2|N|0|99|-|1|-
"""
    const val EQ = """
M|Bass EQ|16777274|1|-
P|50Hz|0|1|S|-50|50|-|1|-
P|120Hz|1|2|S|-50|50|-|1|-
P|400Hz|2|3|S|-50|50|-|1|-
P|800Hz|3|4|S|-50|50|-|1|-
P|2kHz|4|5|S|-50|50|-|1|-
P|VOL|5|6|N|0|99|-|1|-
M|Guitar EQ|16777269|1|-
P|125Hz|0|1|S|-50|50|-|1|-
P|400Hz|1|2|S|-50|50|-|1|-
P|800Hz|2|3|S|-50|50|-|1|-
P|1.6kHz|3|4|S|-50|50|-|1|-
P|4kHz|4|5|S|-50|50|-|1|-
P|VOL|5|6|N|0|99|-|1|-
"""
    const val MOD = """
M|Flanger|67108881|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|PreDly|2|3|N|0|99|-|1|-
P|FdBk|3|4|N|0|99|-|1|-
P|Sync|4|5|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Chorus A|67108864|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|Tone|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Chorus B|67108872|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|Level|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Detune|16777257|1|-
P|Detune|0|1|S|-50|50|-|0|Nur Vendor-Katalog (Index, Bereich).
P|Wet|1|2|N|0|99|-|1|-
P|Dry|2|3|N|0|99|-|1|-
M|Phaser|67108889|1|-
P|Rate|0|1|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|Sync|1|2|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Vibrato|67108885|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|Sync|2|3|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Vibe|67108895|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|Sync|2|3|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Tremolo|67108897|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|Sync|2|3|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Sine Trem|67108902|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|VOL|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
M|Bias Trem|67108904|1|-
P|Depth|0|1|N|0|99|-|1|-
P|Rate|1|2|D|0.1|10|0.1|0|BIND_UNRESOLVED
P|VOL|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Bias|4|5|N|0|99|-|1|-
"""
    const val DLY = """
M|Sweep|184549382|1|-
P|Mix|0|1|N|0|99|-|1|-
P|FdBk|1|2|N|0|99|-|1|-
P|Time|2|3|N|20|4000|-|0|BIND_UNRESOLVED
P|Swp Depth|3|4|N|0|99|-|1|-
P|Swp Rate|4|5|N|0|99|-|0|BIND_UNRESOLVED
P|Swp Sync|5|6|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Time Sync|6|7|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|7|8|F|0|99|-|1|-
M|Warm|184549389|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Time|1|2|N|20|4000|-|0|BIND_UNRESOLVED
P|FdBk|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|4|5|F|0|99|-|1|-
M|Pure|184549376|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Time|1|2|N|20|4000|-|0|BIND_UNRESOLVED
P|FdBk|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|4|5|F|0|99|-|1|-
M|Mag|184549378|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Time|1|2|N|20|4000|-|0|BIND_UNRESOLVED
P|FdBk|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|4|5|F|0|99|-|1|-
M|Tube|184549387|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Time|1|2|N|20|4000|-|0|BIND_UNRESOLVED
P|FdBk|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|4|5|F|0|99|-|1|-
M|999 Echo|184549394|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Time|1|2|N|20|4000|-|0|BIND_UNRESOLVED
P|FdBk|2|3|N|0|99|-|1|-
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|4|5|F|0|99|-|1|-
M|Reverse|184549395|1|-
P|Mix|0|1|N|0|99|-|1|-
P|FdBk|1|2|N|0|99|-|1|-
P|Time|2|3|N|20|4000|-|0|BIND_UNRESOLVED
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|4|5|F|0|99|-|1|-
M|Slap|184549381|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Time|1|2|N|20|300|-|0|BIND_UNRESOLVED
P|FdBk|2|3|N|0|99|-|1|-
P|Trail|4|5|F|0|99|-|1|-
M|Rack|184549396|1|-
P|Mix|0|1|N|0|99|-|1|-
P|FdBk|1|2|N|0|99|-|1|-
P|Time|2|3|N|20|4000|-|0|BIND_UNRESOLVED
P|Mod|3|4|N|0|99|-|1|-
P|Tone|4|5|N|0|99|-|1|-
P|Sync|5|6|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|6|7|F|0|99|-|1|-
M|Ping Pong|184549380|1|-
P|Mix|0|1|N|0|99|-|1|-
P|FdBk|1|2|N|0|99|-|1|-
P|Time|2|3|N|20|4000|-|0|BIND_UNRESOLVED
P|Sync|3|4|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|4|5|F|0|99|-|1|-
M|Tape|184549388|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Time|1|2|N|20|4000|-|0|BIND_UNRESOLVED
P|FdBk|2|3|N|0|99|-|1|-
P|Tone|3|4|N|0|99|-|1|-
P|Sync|5|6|F|0|99|-|0|SYNC_SEMANTICS_UNKNOWN
P|Trail|6|7|F|0|99|-|1|-
"""
    const val RVB = """
M|Mod RVB|201326600|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Pre Delay|1|2|N|0|100|-|1|-
P|Decay|2|3|N|0|99|-|1|-
P|Lo End|3|4|S|-50|50|-|0|Capture kennt diesen Parameter, kein aktiver signedNumber-Sample in RVB.
P|Hi End|4|5|S|-50|50|-|0|Capture kennt diesen Parameter, kein aktiver signedNumber-Sample in RVB.
P|Trail|5|6|F|0|99|-|1|-
M|Room|201326592|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Pre Delay|1|2|N|0|100|-|1|-
P|Decay|2|3|N|0|99|-|1|-
P|Trail|3|4|F|0|99|-|1|-
M|Hall|201326593|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Pre Delay|1|2|N|0|100|-|1|-
P|Decay|2|3|N|0|99|-|1|-
P|Trail|3|4|F|0|99|-|1|-
M|Church|201326594|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Pre Delay|1|2|N|0|100|-|1|-
P|Decay|2|3|N|0|99|-|1|-
P|Trail|3|4|F|0|99|-|1|-
M|Plate|201326595|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Decay|1|2|N|0|100|-|1|-
P|H-Damp|2|3|N|0|99|-|1|-
P|Trail|3|4|F|0|99|-|1|-
M|Spring|201326596|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Decay|1|2|N|0|100|-|1|-
P|Tone|2|3|N|0|99|-|1|-
P|Trail|3|4|F|0|99|-|1|-
M|Sky|201326598|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Decay|1|2|N|0|99|-|1|-
P|Trail|2|3|F|0|99|-|1|-
M|Sea|201326599|1|-
P|Mix|0|1|N|0|99|-|1|-
P|Decay|1|2|N|0|99|-|1|-
P|Trail|2|3|F|0|99|-|1|-
"""
}
