package de.neevel.wyrmtone

/**
 * Native evidence table of the productive Tone Transfer. It is the manufacturer
 * catalog (Sonicake algorithm.xml, normalized) together with the PRODUCTIVE
 * evidence decision per model and parameter, generated by
 * tool/generate_native_manufacturer_catalog.dart into [MatriboxManufacturerData]
 * (Evidence V2 over the hardware ledger: the certified Angels run and the
 * certified FAMILY_EXPANSION_P01_V1 run). Dart's evidence claims are never
 * trusted; Dart only names slot, model and parameter, everything else is
 * resolved here:
 *
 * - the algorithm code comes from the manufacturer data, never from Dart;
 * - the wire parameter index is `manufacturer ID - 1` (hardware-confirmed rule),
 *   there is no idx fallback and no CAB special case;
 * - a model or parameter is sendable only if its decision is FAMILY/EXACT
 *   confirmed (bind/Sync, enumerations, User IR, missing samples stay blocked);
 * - the value is checked against the manufacturer type, range and step;
 * - block CC is confirmed for all nine slots (controller derived from the slot).
 */
internal object MatriboxToneTransferCatalog {
    enum class Kind { NUMBER, SIGNED, DECIMAL, FLAG }

    data class ManufacturerParameter(
        val name: String,
        val wireIndex: Int,
        val manufacturerId: Int,
        val kind: Kind,
        val min: Float,
        val max: Float,
        val step: Float?,
        /** Table decision AND the addressing rule holds (wire == ID - 1, ID >= 1). */
        val writable: Boolean,
        val blockedBy: String?,
    )

    data class ManufacturerModel(
        val slot: ChainSlot,
        val name: String,
        val code: Int,
        val selectable: Boolean,
        val blockedBy: String?,
        val parameters: List<ManufacturerParameter>,
    ) {
        fun parameter(name: String): ManufacturerParameter? = parameters.firstOrNull { it.name == name }
    }

    private fun data(slot: ChainSlot): String = when (slot) {
        ChainSlot.FX1 -> MatriboxManufacturerData.FX1
        ChainSlot.FX2 -> MatriboxManufacturerData.FX2
        ChainSlot.AMP -> MatriboxManufacturerData.AMP
        ChainSlot.NR -> MatriboxManufacturerData.NR
        ChainSlot.CAB -> MatriboxManufacturerData.CAB
        ChainSlot.EQ -> MatriboxManufacturerData.EQ
        ChainSlot.MOD -> MatriboxManufacturerData.MOD
        ChainSlot.DLY -> MatriboxManufacturerData.DLY
        ChainSlot.RVB -> MatriboxManufacturerData.RVB
    }

    private fun kindOf(letter: String): Kind = when (letter) {
        "N" -> Kind.NUMBER
        "S" -> Kind.SIGNED
        "D" -> Kind.DECIMAL
        "F" -> Kind.FLAG
        else -> throw IllegalStateException("Unbekannte Werteart $letter")
    }

    private fun parse(slot: ChainSlot): List<ManufacturerModel> {
        val models = mutableListOf<ManufacturerModel>()
        var header: List<String>? = null
        var parameters = mutableListOf<ManufacturerParameter>()
        fun flush() {
            header?.let {
                models.add(
                    ManufacturerModel(slot, it[1], it[2].toInt(), it[3] == "1", it[4].takeIf { r -> r != "-" }, parameters.toList()),
                )
            }
            parameters = mutableListOf()
        }
        for (line in data(slot).lines()) {
            if (line.isBlank()) continue
            val f = line.split('|')
            when (f[0]) {
                "M" -> { flush(); header = f }
                "P" -> {
                    val wire = f[2].toInt()
                    val id = f[3].toInt()
                    // the ONE addressing rule; a row that violates it can never be written
                    val addressed = id >= 1 && wire == id - 1
                    parameters.add(
                        ManufacturerParameter(
                            name = f[1],
                            wireIndex = wire,
                            manufacturerId = id,
                            kind = kindOf(f[4]),
                            min = f[5].toFloat(),
                            max = f[6].toFloat(),
                            step = f[7].takeIf { s -> s != "-" }?.toFloat(),
                            writable = f[8] == "1" && addressed,
                            blockedBy = if (f[8] == "1" && !addressed) "ADDRESS_BLOCKED" else f[9].takeIf { r -> r != "-" },
                        ),
                    )
                }
                else -> throw IllegalStateException("Ungültige Tabellenzeile: $line")
            }
        }
        flush()
        return models
    }

    private val table: Map<ChainSlot, List<ManufacturerModel>> by lazy { ChainSlot.values().associateWith { parse(it) } }

    val models: List<ManufacturerModel> get() = ChainSlot.values().flatMap { table.getValue(it) }

    fun model(slot: ChainSlot, name: String): ManufacturerModel? = table.getValue(slot).firstOrNull { it.name == name }

    fun modelByCode(slot: ChainSlot, code: Int): ManufacturerModel? = table.getValue(slot).firstOrNull { it.code == code }

    /** (slot, enabled) block toggles: the CC family is confirmed for all nine slots, both directions. */
    val confirmedToggles: Set<Pair<ChainSlot, Boolean>> =
        ChainSlot.values().flatMap { listOf(it to true, it to false) }.toSet()

    /** null when [value] is a valid manufacturer value for [parameter], else the reason. */
    fun valueProblem(parameter: ManufacturerParameter, value: Float): String? {
        if (!value.isFinite()) return "Wert ist nicht endlich."
        if (parameter.kind == Kind.FLAG) {
            return if (value == 0f || value == 1f) null else "Flag muss 0 oder 1 sein."
        }
        if (value < parameter.min || value > parameter.max) return "Wert $value außerhalb ${parameter.min}..${parameter.max}."
        val step = parameter.step
        if (step != null && step > 0f) {
            val steps = (value - parameter.min) / step
            if (kotlin.math.abs(steps - Math.round(steps)) > 1e-3f) return "Wert $value liegt nicht im Herstellerraster $step."
        }
        return null
    }

    /** Independent re-check of an already validated operation (used again by the port). */
    fun isConfirmed(operation: FullLiveOperation): Boolean = when (operation) {
        is FullLiveOperation.ModelSelect -> {
            val model = modelByCode(operation.slot, operation.code)
            model != null && model.selectable && model.name == operation.name
        }
        is FullLiveOperation.Parameter -> {
            val model = modelByCode(operation.slot, operation.code)
            val parameter = model?.parameter(operation.name)
            model != null && parameter != null && parameter.writable &&
                parameter.wireIndex == operation.index && valueProblem(parameter, operation.value) == null
        }
        is FullLiveOperation.BlockToggle -> (operation.slot to operation.enabled) in confirmedToggles
    }
}
