/// Evidence policy V2: machine-decidable evidence FAMILIES instead of one
/// exact hardware key per song operation.
///
/// This is the decision model of the PRODUCTIVE tone transfer (the Dart plan
/// gates every operation with it) and its rules are mirrored, data-driven, by
/// the native table (MatriboxManufacturerCatalog.kt, generated by
/// tool/generate_native_manufacturer_catalog.dart from the same decisions).
/// A family is productive only through the ACTIVE samples of the hardware
/// ledger ([MatriboxHardwareLedger.product]): the certified Angels run and the
/// certified FAMILY_EXPANSION_P01_V1 run. It sends nothing itself.
///
/// Levels, weakest first (only the last two allow a send):
/// - BLOCKED               never allowed (or refused by a structural check)
/// - STRUCTURE_CONFIRMED   the message structure is byte-exact against capture
/// - CATALOG_CONFIRMED     the vendor catalog knows algorithm/parameter/range
///                         and the category matches the slot (NOT hardware)
/// - CAPTURE_CONFIRMED     an editor capture contains exactly this identity
/// - ACTIVE_SAMPLE_CONFIRMED  one WyrmTone send of this exact identity was
///                         verified (recorded per operation, not a rule)
/// - FAMILY_CONFIRMED      a rule over device + slot + catalog + protocol
///                         family + ACTIVE samples covers this operation
/// - EXACT_OPERATION_CONFIRMED  this very operation was sent and verified
///
/// Values are never certified: only the identity (slot, model, parameter,
/// value kind) is. The value is checked against the catalog range.
library;

import 'matribox_chain_catalog.dart';
import 'matribox_chain_slot.dart';
import 'matribox_full_live_plan.dart';
import 'matribox_hardware_evidence.dart';
import 'matribox_model_library.dart';
import 'matribox_transfer_catalog.dart';

enum EvidenceLevel {
  blocked,
  structureConfirmed,
  catalogConfirmed,
  captureConfirmed,
  activeSampleConfirmed,
  familyConfirmed,
  exactOperationConfirmed;

  /// Only family and exact evidence may be sent.
  bool get sendable => this == familyConfirmed || this == exactOperationConfirmed;
}

class EvidenceDecision {
  const EvidenceDecision(this.level, this.family, this.basis, {this.missing});

  final EvidenceLevel level;

  /// Protocol family or rule name, e.g. `MODEL_SELECT_SLOT_FAMILY`.
  final String family;
  final String basis;

  /// The smallest active sample that would upgrade a non-sendable decision.
  final String? missing;

  bool get sendable => level.sendable;
}

/// Where the wire identity of a sampled operation came from BEFORE the active
/// send. A sample of a catalog-only identity is stronger evidence for other
/// catalog-only identities than a sample of a capture-confirmed one.
enum SampleSource { capture, catalogOnly }

class SelectSample {
  const SelectSample(this.slot, this.algorithmId, this.source);
  final MatriboxChainSlot slot;
  final String algorithmId;
  final SampleSource source;
}

class ParameterSample {
  const ParameterSample(this.slot, this.algorithmId, this.parameter, this.kind, this.source);
  final MatriboxChainSlot slot;
  final String algorithmId;
  final String parameter;
  final MatriboxParameterKind kind;
  final SampleSource source;
}

class ToggleSample {
  const ToggleSample(this.slot, this.enabled);
  final MatriboxChainSlot slot;
  final bool enabled;
}

/// ACTIVE hardware samples (real sends, verified after manual device save).
class ActiveSamples {
  const ActiveSamples({this.selects = const [], this.parameters = const [], this.toggles = const []});

  final List<SelectSample> selects;
  final List<ParameterSample> parameters;
  final List<ToggleSample> toggles;

  /// Derived from the hardware ledger; nothing is hard-coded here.
  factory ActiveSamples.fromLedger(MatriboxHardwareLedger ledger, MatriboxModelLibrary library) {
    MatriboxTransferModel? find(MatriboxChainSlot slot, String algorithmId) =>
        library.forSlot(slot).where((m) => m.algorithm.id == algorithmId).firstOrNull;
    MatriboxChainSlot? slotOf(String name) => MatriboxChainSlot.values.where((s) => s.name == name).firstOrNull;

    final selects = <SelectSample>[];
    for (final key in ledger.exactModels) {
      final cut = key.indexOf(':');
      final slot = slotOf(key.substring(0, cut));
      final model = slot == null ? null : find(slot, key.substring(cut + 1));
      if (slot == null || model == null) continue;
      selects.add(SelectSample(slot, model.algorithm.id, _source(model.selectEvidence)));
    }
    final parameters = <ParameterSample>[];
    for (final key in ledger.exact) {
      final first = key.indexOf(':');
      final last = key.lastIndexOf(':');
      final slot = slotOf(key.substring(0, first));
      final model = slot == null ? null : find(slot, key.substring(first + 1, last));
      final name = key.substring(last + 1);
      final parameter = model?.algorithm.parameters.where((p) => p.name == name).firstOrNull;
      if (slot == null || model == null || parameter == null) continue;
      parameters.add(ParameterSample(slot, model.algorithm.id, name, parameter.kind, _source(model.parameterEvidence)));
    }
    final toggles = <ToggleSample>[];
    for (final key in ledger.exactToggles) {
      final parts = key.split(':');
      final slot = slotOf(parts.first);
      if (slot != null) toggles.add(ToggleSample(slot, parts.last == 'true'));
    }
    return ActiveSamples(selects: selects, parameters: parameters, toggles: toggles);
  }

  static SampleSource _source(TransferProtocolEvidence e) =>
      e == TransferProtocolEvidence.captureConfirmed ? SampleSource.capture : SampleSource.catalogOnly;

  /// The samples a SUCCESSFUL run of [operations] would add (projection only).
  ActiveSamples projected(List<FullLiveOperation> operations, MatriboxModelLibrary library) {
    final s = [...selects];
    final p = [...parameters];
    final t = [...toggles];
    for (final op in operations) {
      final model = library.byCode(op.slot, op.algorithm?.code ?? -1);
      switch (op.kind) {
        case FullLiveOperationKind.modelSelect:
          if (model != null) s.add(SelectSample(op.slot, model.algorithm.id, _source(model.selectEvidence)));
        case FullLiveOperationKind.parameter:
          if (model != null) {
            p.add(ParameterSample(op.slot, model.algorithm.id, op.parameter!.name, op.parameter!.kind, _source(model.parameterEvidence)));
          }
        case FullLiveOperationKind.blockToggle:
          t.add(ToggleSample(op.slot, op.enabled!));
      }
    }
    return ActiveSamples(selects: s, parameters: p, toggles: t);
  }
}

/// Message families and their fixed status, independent of any sample.
abstract final class MatriboxMessageFamilies {
  static const structureConfirmed = {
    'MODEL_SELECT (12 10 SS 00 01, 22 B)',
    'PARAMETER_WRITE (12 10 SS 00 02, 34 B)',
    'BLOCK_TOGGLE (CC B1 30..38)',
  };
  static const blocked = {
    'METADATA (12 11)': 'nie von WyrmTone gesendet',
    'STORE (12 12)': 'WyrmTone sendet kein Store; Speichern ist der manuelle Geräteschritt',
    'FACTORY_WRITE': 'Factory-Presets werden nie beschrieben',
    'USER_P02_PLUS': 'V1 schreibt nur User P01',
    'RESTORE_RETRY': 'kein Restore, kein Retry',
    'RAW_SYSEX': 'kein Roh-SysEx aus der UI',
  };

  static EvidenceDecision decide(String family) {
    if (blocked.containsKey(family)) {
      return EvidenceDecision(EvidenceLevel.blocked, family, blocked[family]!);
    }
    if (structureConfirmed.contains(family)) {
      return EvidenceDecision(EvidenceLevel.structureConfirmed, family, 'Nachrichtenaufbau byte-genau gegen den Capture.');
    }
    return EvidenceDecision(EvidenceLevel.blocked, family, 'Unbekannte Nachrichtenfamilie.');
  }
}

/// What may count as vendor catalog data and what it may be used for.
abstract final class MatriboxCatalogTrust {
  /// Vendor catalog fields that may be used productively as IDENTITY/RANGE
  /// input to an evidence family (they are still not hardware evidence).
  static const productive = [
    'algorithm.name, algorithm.category (slot compatibility)',
    'algorithm.code (u32 payload of MODEL SELECT and PARAMETER WRITE)',
    'parameter.name, parameter.xmlId (wire index = xmlId - 1, hardware-confirmed)',
    'parameter.minimum / maximum / step / default (range check and defaults)',
    'parameter.xmlControlType (Switch with menu IDs {0,1} -> flag 0/1)',
  ];

  /// Fields or derivations that stay BLOCKED / UNKNOWN even after the family promotion.
  static const stillBlocked = [
    'User IR codes (blank names): not selectable',
    'bind / Sync: a bound value means something else when Sync is on (note values unknown)',
    'Combox (enumeration) parameters: no hardware sample, menu semantics unconfirmed',
    'Switches whose menu IDs are not {0,1}',
    'semantic meaning of ATK / Rel / Tone / Bright (no direction/unit in the catalog)',
    'any musical suitability of a model',
  ];
}

/// Threshold: kind evidence in this many distinct non-CAB slots covers the
/// remaining non-CAB slots (the slot byte is the only structural difference).
const crossSlotKindThreshold = 3;

/// Distinct active block controllers, both polarities, needed for the CC family.
const blockFamilyMinControllers = 3;

class MatriboxEvidenceV2 {
  MatriboxEvidenceV2({required this.library, required this.samples});

  final MatriboxModelLibrary library;
  final ActiveSamples samples;

  bool _known(MatriboxChainSlot slot, MatriboxTransferModel model) {
    final byCode = library.byCode(slot, model.code);
    return byCode != null && byCode.algorithm.name == model.algorithm.name;
  }

  EvidenceDecision modelSelect(MatriboxChainSlot slot, MatriboxTransferModel model) {
    const family = 'MODEL_SELECT_SLOT_FAMILY';
    if (model.name.isEmpty || model.name.startsWith('User IR') || model.algorithm.id.startsWith('userIr')) {
      return EvidenceDecision(EvidenceLevel.blocked, family, 'USER_IR_BLOCKED: User IR bleibt gesperrt.');
    }
    if (!model.selectable || !model.algorithm.sendableInFullLive) {
      return EvidenceDecision(EvidenceLevel.blocked, family, '${model.name} ist nicht selektierbar (nur dokumentiert).');
    }
    if (!model.algorithm.slots.contains(slot)) {
      return EvidenceDecision(EvidenceLevel.blocked, family, '${model.name} gehört nicht in die Kategorie von ${slot.label}.');
    }
    if (!_known(slot, model)) {
      return EvidenceDecision(EvidenceLevel.blocked, family, 'Algorithmus ${model.name} ist nicht im Original-Katalog: keine freie ID.');
    }
    final inSlot = samples.selects.where((s) => s.slot == slot).toList();
    if (inSlot.any((s) => s.algorithmId == model.algorithm.id)) {
      return EvidenceDecision(EvidenceLevel.exactOperationConfirmed, family, 'Exakt dieses Modell in ${slot.label} gesendet und verifiziert.');
    }
    final captured = model.selectEvidence == TransferProtocolEvidence.captureConfirmed;
    // catalog-only identity needs a catalog-only sample; a captured one needs any sample
    final covering = captured ? inSlot : inSlot.where((s) => s.source == SampleSource.catalogOnly).toList();
    if (covering.isNotEmpty) {
      return EvidenceDecision(
        EvidenceLevel.familyConfirmed,
        family,
        'Aktiver Sample in ${slot.label} (${covering.first.algorithmId}); Katalog-Code, Kategorie = Slot, Encoder byte-genau.',
      );
    }
    final missing = captured
        ? 'ein aktiver MODEL SELECT in ${slot.label}'
        : 'ein aktiver MODEL SELECT eines nur-Katalog-Modells in ${slot.label}';
    return EvidenceDecision(
      captured ? EvidenceLevel.captureConfirmed : EvidenceLevel.catalogConfirmed,
      family,
      captured ? 'Capture kennt dieses Modell, kein aktiver Sample in ${slot.label}.' : 'Nur Vendor-Katalog (Code, Kategorie).',
      missing: missing,
    );
  }

  bool _sameParameter(MatriboxChainParameter a, MatriboxChainParameter b) =>
      a.name == b.name && a.wireIndex == b.wireIndex && a.catalogIndex == b.catalogIndex;

  /// Structural/semantic blocks that no sample can lift: invalid address, bind/Sync, enumerations.
  String? _parameterBlock(MatriboxTransferModel model, MatriboxChainParameter parameter) {
    if (parameter.blockedReason != null) return 'ADDRESS_BLOCKED: ${parameter.blockedReason}';
    if (parameter.wireIndex < 0) return 'ADDRESS_BLOCKED: kein gültiger Wire-Index';
    if (parameter.bind != null) {
      return 'BIND_UNRESOLVED: ${parameter.name} ist an "${parameter.bind}" gebunden; seine Bedeutung bei aktivem Sync ist unbekannt.';
    }
    if (model.algorithm.parameters.any((q) => q.bind == parameter.name)) {
      return 'SYNC_SEMANTICS_UNKNOWN: ${parameter.name} schaltet die Bedeutung gebundener Parameter um.';
    }
    if (parameter.controlType == 'Combox') {
      return 'ENUM_UNCONFIRMED: ${parameter.name} ist eine Auswahlliste (Combox); Menüwerte sind nicht hardware-belegt.';
    }
    if (parameter.controlType == 'Switch') {
      final ids = [...parameter.menuIds]..sort();
      if (ids.length != 2 || ids[0] != 0 || ids[1] != 1) {
        return 'SWITCH_MENU_UNCONFIRMED: ${parameter.name} hat Menü-IDs $ids statt {0,1}.';
      }
    }
    return null;
  }

  EvidenceDecision parameter(
    MatriboxChainSlot slot,
    MatriboxTransferModel model,
    MatriboxChainParameter parameter,
    double value,
  ) {
    const family = 'PARAMETER_FLOAT32_KIND_FAMILY';
    if (model.name.isEmpty || model.name.startsWith('User IR') || model.algorithm.id.startsWith('userIr')) {
      return EvidenceDecision(EvidenceLevel.blocked, family, 'USER_IR_BLOCKED: User IR bleibt gesperrt (auch seine Parameter).');
    }
    if (!model.algorithm.slots.contains(slot)) {
      return EvidenceDecision(EvidenceLevel.blocked, family, '${model.name} gehört nicht in die Kategorie von ${slot.label}.');
    }
    if (!_known(slot, model)) {
      return EvidenceDecision(EvidenceLevel.blocked, family, 'Algorithmus ${model.name} ist nicht im Original-Katalog.');
    }
    if (!model.algorithm.parameters.any((p) => _sameParameter(p, parameter))) {
      return EvidenceDecision(EvidenceLevel.blocked, family, 'Unbekannter Parameter ${parameter.name} für ${model.name}.');
    }
    final structural = _parameterBlock(model, parameter);
    if (structural != null) return EvidenceDecision(EvidenceLevel.blocked, family, structural);
    if (!parameter.accepts(value)) {
      return EvidenceDecision(
        EvidenceLevel.blocked,
        family,
        '${parameter.name}=$value außerhalb ${parameter.kind == MatriboxParameterKind.flag ? '0/1' : '${parameter.minimum}..${parameter.maximum}'}.',
      );
    }
    final step = parameter.step;
    if (step != null && step > 0) {
      final steps = (value - parameter.minimum) / step;
      if ((steps - steps.roundToDouble()).abs() > 1e-6) {
        return EvidenceDecision(EvidenceLevel.blocked, family, '${parameter.name}=$value liegt nicht im Herstellerraster $step.');
      }
    }
    if (samples.parameters.any((s) => s.slot == slot && s.algorithmId == model.algorithm.id && s.parameter == parameter.name)) {
      return EvidenceDecision(EvidenceLevel.exactOperationConfirmed, family, 'Exakt dieser Parameter gesendet und verifiziert (Wert nur per Katalogbereich geprüft).');
    }
    final captured = model.parameterEvidence == TransferProtocolEvidence.captureConfirmed;
    final kind = parameter.kind;
    bool covers(ParameterSample s) => s.kind == kind && (captured || s.source == SampleSource.catalogOnly);
    final inSlot = samples.parameters.where((s) => s.slot == slot && covers(s)).toList();
    if (inSlot.isNotEmpty) {
      return EvidenceDecision(
        EvidenceLevel.familyConfirmed,
        family,
        '${kind.name}-Sample in ${slot.label} (${inSlot.first.algorithmId}/${inSlot.first.parameter}); Index aus Katalog, Wert im Katalogbereich.',
      );
    }
    {
      // The addressing rule (wire = ID - 1) is generic, so CAB is no special slot any more.
      final slots = {
        for (final s in samples.parameters)
          if (covers(s)) s.slot,
      };
      if (slots.length >= crossSlotKindThreshold) {
        return EvidenceDecision(
          EvidenceLevel.familyConfirmed,
          '$family (cross-slot)',
          '${kind.name}-Samples in ${slots.length} Slots (${slots.map((s) => s.label).join(', ')}); der Slot-Byte ist der einzige Unterschied.',
        );
      }
    }
    return EvidenceDecision(
      captured ? EvidenceLevel.captureConfirmed : EvidenceLevel.catalogConfirmed,
      family,
      captured ? 'Capture kennt diesen Parameter, kein aktiver ${kind.name}-Sample in ${slot.label}.' : 'Nur Vendor-Katalog (Index, Bereich).',
      missing: 'ein aktiver ${kind.name}-Parameterwrite ${captured ? '' : 'auf einem nur-Katalog-Parameter '}in ${slot.label}'

    );
  }

  EvidenceDecision blockToggle(MatriboxChainSlot slot, bool enabled) {
    const family = 'BLOCK_CC_FAMILY';
    if (samples.toggles.any((t) => t.slot == slot && t.enabled == enabled)) {
      return EvidenceDecision(EvidenceLevel.exactOperationConfirmed, family, 'Block ${slot.label} ${enabled ? 'ON' : 'OFF'} exakt gesendet und verifiziert.');
    }
    final controllers = {for (final t in samples.toggles) t.slot};
    final hasOn = samples.toggles.any((t) => t.enabled);
    final hasOff = samples.toggles.any((t) => !t.enabled);
    if (controllers.length >= blockFamilyMinControllers && hasOn && hasOff) {
      return EvidenceDecision(
        EvidenceLevel.familyConfirmed,
        family,
        'CC-Familie: ${controllers.length} aktive Controller (${controllers.map((s) => s.label).join(', ')}), ON und OFF belegt, '
        'Controller = 0x2F + Slot im Capture 9/9 konsistent.',
      );
    }
    return const EvidenceDecision(
      EvidenceLevel.captureConfirmed,
      family,
      'Capture 9/9 konsistent, aber zu wenige aktive Controller/Polaritäten.',
      missing: 'aktive ON- und OFF-Toggles auf mindestens drei verschiedenen Slots',
    );
  }
}

/// Principal reach of a family state over the vendor catalog: how many of the
/// catalog's algorithms and parameters are sendable at all. This says nothing
/// about musical suitability.
class EvidenceCoverage {
  const EvidenceCoverage({
    required this.algorithms,
    required this.algorithmsSendable,
    required this.parameters,
    required this.parametersSendable,
    required this.parametersEndToEnd,
    required this.perSlotSelectable,
  });

  final int algorithms;
  final int algorithmsSendable;
  final int parameters;
  /// Parameter writes allowed for the model as such (it may already be active).
  final int parametersSendable;

  /// Parameter writes whose model can ALSO be selected: full select + write.
  final int parametersEndToEnd;
  final Map<MatriboxChainSlot, bool> perSlotSelectable;
}

const _coverageSlots = <String, MatriboxChainSlot>{
  'FX1': MatriboxChainSlot.fx1,
  'FX2': MatriboxChainSlot.fx2,
  'AMP': MatriboxChainSlot.amp,
  'NR': MatriboxChainSlot.nr,
  'CAB': MatriboxChainSlot.cab,
  'EQ': MatriboxChainSlot.eq,
  'MOD': MatriboxChainSlot.mod,
  'DLY': MatriboxChainSlot.dly,
  'RVB': MatriboxChainSlot.rvb,
};

/// Counts, over every catalog algorithm/parameter entry, what the evidence
/// state would allow. A parameter is sendable if its model can be selected in
/// its category slot AND the parameter itself is family/exact confirmed.
EvidenceCoverage evidenceCoverage(
  Iterable<({String category, int code, String name, List<int> parameterIndices})> catalog,
  MatriboxEvidenceV2 evidence,
) {
  var algorithms = 0, algorithmsSendable = 0, parameters = 0, parametersSendable = 0, parametersEndToEnd = 0;
  final slotOk = {for (final s in MatriboxChainSlot.values) s: false};
  for (final entry in catalog) {
    final slot = _coverageSlots[entry.category];
    algorithms++;
    parameters += entry.parameterIndices.length;
    final model = slot == null ? null : evidence.library.byCode(slot, entry.code);
    if (slot == null || model == null) continue;
    final select = evidence.modelSelect(slot, model);
    if (select.sendable) {
      algorithmsSendable++;
      slotOk[slot] = true;
    }
    for (final index in entry.parameterIndices) {
      final p = model.algorithm.parameters.where((x) => x.catalogIndex == index).firstOrNull;
      if (p == null) continue;
      if (evidence.parameter(slot, model, p, p.kind == MatriboxParameterKind.flag ? 0 : p.minimum).sendable) {
        parametersSendable++;
        if (select.sendable) parametersEndToEnd++;
      }
    }
  }
  return EvidenceCoverage(
    algorithms: algorithms,
    algorithmsSendable: algorithmsSendable,
    parameters: parameters,
    parametersSendable: parametersSendable,
    parametersEndToEnd: parametersEndToEnd,
    perSlotSelectable: slotOk,
  );
}
